### ISSUE TITLE
Code license

### ISSUE THREAD

**Issue by luislavena** [gliderlabs/docker-alpine#1]
Hello.

Thank you for releasing this to the world and making it available for everybody to benefit!

I was peeking around some of the scripts and considering it's usage for mini-containers/base, but before I do that, we need to know the licensing terms the code is made available.

Having a clear mention of the licensing on both `README.md` and the presence of a `LICENSE` file will be very helpful.

Once again, thank you for releasing this! :heart: :heart: :heart:

**Comment by luislavena** [comment]
Hello @andyshinn, can you provide the licensing information for this repository and code?

Thank you.

**Comment by andyshinn** [comment]
Pinging @progrium for comment on license. I think we're going to say this is BSD (and will add a proper `LICENSE` file and information to the `README.md`. I'll commit after confirmation.

**Comment by progrium** [comment]
Yep, BSD like all the others. Thanks for noting the lack of license.

On Wed, Jan 28, 2015 at 12:07 PM, Andy Shinn <notifications@github.com>
wrote:

> Pinging @progrium <https://github.com/progrium> for comment on license. I
> think we're going to say this is BSD (and will add a proper LICENSE file
> and information to the README.md. I'll commit after confirmation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/docker-alpine/issues/1#issuecomment-71884276>
> .
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by andyshinn** [comment]
Added in 9c8369189f3c9c2c261a2098c344c0c1648d2c8f.
