### ISSUE TITLE
curl is dependent on lua??

### ISSUE THREAD

**Issue by dynnamitt** [gliderlabs/docker-alpine#10]
Why do curl need lua?

(not needed in opkg)

/ # apk-install curl
fetch http://dl-4.alpinelinux.org/alpine/v3.1/main/x86_64/APKINDEX.tar.gz
(1/8) Installing run-parts (4.4-r0)
(2/8) Installing openssl (1.0.1k-r0)
(3/8) Installing lua5.2-libs (5.2.3-r0)
(4/8) Installing lua5.2 (5.2.3-r0)
(5/8) Installing lua5.2-posix (32-r1)
(6/8) Installing ca-certificates (20141019-r0)
(7/8) Installing libssh2 (1.4.3-r0)
(8/8) Installing curl (7.39.0-r0)
Executing busybox-1.22.1-r14.trigger
Executing ca-certificates-20141019-r0.trigger
OK: 8 MiB in 23 packages

**Comment by progrium** [comment]
I think that's a question for the package maintainer.

On Sun, Feb 22, 2015 at 2:54 AM, Kjetil Flovild-Midtlie <
notifications@github.com> wrote:

> Why do curl need lua?
>
> (not needed in opkg)/ # apk-install curl
> fetch http://dl-4.alpinelinux.org/alpine/v3.1/main/x86_64/APKINDEX.tar.gz
> (1/8) Installing run-parts (4.4-r0)
> (2/8) Installing openssl (1.0.1k-r0)
> (3/8) Installing lua5.2-libs (5.2.3-r0)
> (4/8) Installing lua5.2 (5.2.3-r0)
> (5/8) Installing lua5.2-posix (32-r1)
> (6/8) Installing ca-certificates (20141019-r0)
> (7/8) Installing libssh2 (1.4.3-r0)
> (8/8) Installing curl (7.39.0-r0)
> Executing busybox-1.22.1-r14.trigger
> Executing ca-certificates-20141019-r0.trigger
> OK: 8 MiB in 23 packages
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/docker-alpine/issues/10>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by jbergknoff** [comment]
In case it helps, `curl` [depends on](http://git.alpinelinux.org/cgit/aports/tree/main/curl/APKBUILD) `ca-certificates` which [depends on](http://git.alpinelinux.org/cgit/aports/tree/main/ca-certificates/APKBUILD) lua.

**Comment by Barthalion** [comment]
Lua 5.2 is a dependency because we're using custom script for updating CA certificates. It shouldn't be too hard to rewrite it in POSIX sh though.

**Comment by ncopa** [comment]
we replaced the ca-sertificates script to lua instead of shell due to significant performance improvement: http://bugs.alpinelinux.org/issues/2846#note-4

Lua is not that big. ~300k or so. Be happy its not perl or python (40M minimum) ;)

Shouldn't be too hard to replace it with C code in case someone cares enough.

**Comment by andyshinn** [comment]
I'm going to close this. While I would love to have a smaller C binary dependency, it is something that should be in the upstream issue tracker at https://bugs.alpinelinux.org. I totally agree with the idea for the minimilast Docker image. But it isn't something we can solve in this repository.
