### ISSUE TITLE
Syncthing 64-bit binary fails to run entirely

### ISSUE THREAD

**Issue by PHLAK** [gliderlabs/docker-alpine#100]
I'm unable to run the Syncthing built for Linux amd64 on my docker Alpine environment.  The "386" build works fine.

        $ docker run -it --rm --privilaged alpine:latest /bin/sh
    / # apk add --update ca-certificates strace tar wget
        [ OUTPUT REMOVED FOR CONVINIENCE ]
    / # cd /tmp/
    /tmp # wget https://github.com/syncthing/syncthing/releases/download/v0.12.2/syncthing-linux-amd64-v0.12.2.tar.gz
        [ OUTPUT REMOVED FOR CONVINIENCE ]
    /tmp # tar -xzvf syncthing-linux-amd64-v0.12.2.tar.gz 
        [ OUTPUT REMOVED FOR CONVINIENCE ]
    /tmp # cd syncthing-linux-amd64-v0.12.2/
    /tmp/syncthing-linux-amd64-v0.12.2 # ./syncthing
    /bin/sh: ./syncthing: not found
    /tmp/syncthing-linux-amd64-v0.12.2 # strace ./syncthing
    execve("./syncthing", ["./syncthing"], [/* 7 vars */]) = -1 ENOENT (No such file or directory)
    writev(2, [{"strace: exec: No such file or di"..., 39}, {"\n", 1}], 2strace: exec: No such file or directory
    ) = 40
    writev(2, [{"", 0}, {NULL, 0}], 2)      = 0
    getpid()                                = 24
    exit_group(1)                           = ?
    +++ exited with 1 +++
    /tmp/syncthing-linux-amd64-v0.12.2 # ldd syncthing
        /lib64/ld-linux-x86-64.so.2 (0x5643cc1ff000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x5643cc1ff000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x5643cc1ff000)
    Error relocating syncthing: __vfprintf_chk: symbol not found

**Comment by andyshinn** [comment]
It would appear that it is compiled against and externally linked to glibc (`__vfprintf_chk` being an internal glibc symbol). Have you tried building it yourself based on their docs at http://docs.syncthing.net/dev/building.html?

**Comment by andyshinn** [comment]
Closing as this is likely a glibc thing which is related to #11. Feel free to reopen if that is not the case.
