### ISSUE TITLE
how to change the alpinelinux 's $LANG ?

### ISSUE THREAD

**Issue by lioncui** [gliderlabs/docker-alpine#102]
i want to set the LANG=zh_CN , but it had no obvious effect .
how ?

thanks all

**Comment by andyshinn** [comment]
Did you figure out your issue? If so, can you post the answer so someone else can find it? Otherwise, some more information on what program typically uses the `LANG` variable could help. Is this something glibc usually uses? Or maybe just the `gettext` package?

**Comment by lioncui** [comment]
@andyshinn 
Thank your response, i did't fix this issue already given up, I finally specify the character set encoding inside the program.
I try to install the glib-lang package, system have a dircetory as `usr/share/locale`, but there is still no effect. 
So, close.
