### ISSUE TITLE
Alpine Liunux v3.3

### ISSUE THREAD

**Issue by msaraiva** [gliderlabs/docker-alpine#103]
Hi,

Alpine Linux v.3.3 has been released. Is there any plan to have the v3.3 tag at docker hub any time soon?

Many thanks for this image.
-marlus

**Comment by andyshinn** [comment]
Where are you seeing this? I didn't see any official announcement yet, nor is it on their homepage.

**Comment by msaraiva** [comment]
I guess it's already possible to upgrade to v3.3 because the repositories are already set up. See: 
<https://github.com/msaraiva/alpine-erlang/issues/2#issuecomment-156019962>

The packages are indeed available as you can see here:
<http://dl-2.alpinelinux.org/alpine/v3.3/community/x86_64/>

But you're right, there was no official announcement yet. I'm closing the issue.

Thanks again!

**Comment by andyshinn** [comment]
Based on what I've seen come through the aports mailing list, it is delayed a bit due to a bug in pspell. We'll cut a new image a week or so after release (we're going to try building an even slimmer base for 3.3). See #32.

**Comment by msaraiva** [comment]
Great job! Looking forward to test the new image.

**Comment by ncopa** [comment]
The v3.3 release candidate 1 is out and v3.3 repositories are available for testing. We will branch 3.3-stable (and release 3.3.0) within a week or two.
