### ISSUE TITLE
musl is 'missing' even when installed

### ISSUE THREAD

**Issue by benson-basis** [gliderlabs/docker-alpine#106]
I'm trying to run a Java program with some native code hanging out the side, using Oracle Java8. I've installed glibc, and libstdc++, and musl,  and now I'm faced with the following:

```
java.lang.UnsatisfiedLinkError: /data/roots/btroot/rlp/lib/amd64-glibc25-gcc41/libbtutiljni.so: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
```

This might be related to #11 .

**Comment by frol** [comment]
@benson-basis I won't say that running glibc on Alpine is the right thing, but yes, it was done in #11. Have you tried to use any of the Oracle Java8 images mentioned there? Try [`frolvlad/alpine-oraclejdk8`](https://hub.docker.com/r/frolvlad/alpine-oraclejdk8/) and also provide the output of the following commands:

```
ldd "/data/roots/btroot/rlp/lib/amd64-glibc25-gcc41/libbtutiljni.so"
```

```
LD_TRACE_LOADED_OBJECTS=1 /usr/glibc/usr/lib/ld-linux-x86-64.so.2 "/data/roots/btroot/rlp/lib/amd64-glibc25-gcc41/libbtutiljni.so"
```

**Comment by andyshinn** [comment]
I agree, if this is related to Java in Alpine lets just keep it in #11. The short answer is that glibc compiled application like Oracle Java won't work on musl. The long answer is #11.

**Comment by benson-basis** [comment]
Indeed, one of the suggestions from #11 did the job.
