### ISSUE TITLE
need/want  squashfs tools 7zip 

### ISSUE THREAD

**Issue by necrose99** [gliderlabs/docker-alpine#108]
FROM 32bit/debian:jessie make that ALPINE 32. 

MAINTAINER Gentoo Docker Team

ADD http://www.busybox.net/downloads/binaries/latest/busybox-i686 /busybox

<code># This one should be present by running the build.sh script
ADD build.sh /</code>

RUN apt-get update && apt-get install -y \
	wget bzip2  <RUN  Emerge -v sys-fs/squashfs-tools app-arch/p7zip (apt get p7zip , squashfs tools) dump REALY Large iso , run updater (fork of gentoo) 
VOLUME /usr/portage , ie **PACKAGES**  
ADD in Sabayon-Linux BOSONS Wreaker circle CI , pull the now empty container but retained Binaries pull bins into local host or webhost rinse repeat. and or on github push. new package build it!! 

RUN /build.sh x86-hardened  Gentoo I've tried to tweak their script and docker file 70 ways till sunday no dice. 

ANYhow 1st goal is a CHROOT jail , thats loadable on demand. 
OF late the poor BIN server just isnt keeping up with user demand. 
as well CHROOT/sandbox for testing stability of packages on local host. 
</i>I'm getting sick of casting spells and chanting as the drive recovery tools spin...paying to the disk drive gods , after testing that one "Harmless" version bump --KERBLEWY .</I>
3rd nd would be to abuse all the hacker tools in the distro , laptop + Rainbow tables ZZZZZZZ
**docker Cluster** +Rainbow tables , cloud security pen-testing , and or some other crazy use of security sciences , cytpto studies etc. 

## **My FURY**: 
FROM 32bit/debian:jessie or the built Gentoo images (which i could overlay haven't the tools, and having to make a nested container to unpack a 3 or 4 container oh joy... ) 
and trying to stuff them into debian32  and or Busy-box 64 is also an EPIC FAIL. 
Dockerhub dies on build.  A: is too Light , B CAN be done to gentoo but I have to make 4 more containers or so. IE AMD64 /I686 Default or HARDENED sub Flavors. Less I add ARM or ARM 64
 ** C: Minimal light but JUST RIGHT and slightly extendable when needed ** 
so far trying to add to the Gentoo containers apt-get packages = Spectacular FAIL adding to the base unpacker Image. >/my-distro-temp  , KILL debian/busybox move distro to root /

# Setup the (virtually) current runlevel
RUN echo "default" > /run/openrc/softlevel

# Setup the rc_sys
RUN sed -e 's/#rc_sys=""/rc_sys="lxc"/g' -i /etc/rc.conf

# Setup the net.lo runlevel
RUN ln -s /etc/init.d/net.lo /run/openrc/started/net.lo

# Setup the net.eth0 runlevel
RUN ln -s /etc/init.d/net.lo /etc/init.d/net.eth0
RUN ln -s /etc/init.d/net.eth0 /run/openrc/started/net.eth0

#Add Layman
Run emerge --sync
RUN emerge -v =dev-lang/python-2* =dev-lang/python-3* 
RUN Emerge -v git layman potage
RUN  Emerge -v sys-fs/squashfs-tools app-arch/p7zip

**Comment by andyshinn** [comment]
I'm not sure what your question is. Are you looking for the https://pkgs.alpinelinux.org/package/main/x86_64/p7zip and https://pkgs.alpinelinux.org/package/main/x86_64/squashfs-tools packages?

**Comment by scalp42** [comment]
Also please make sure to wrap your output within ```

**Comment by necrose99** [comment]
namely I Want to add 7zip  & Squash tools 
https://github.com/gentoo/gentoo-docker-images/blob/master/x86/Dockerfile

RUN apt-get update && apt-get install -y \
	wget bzip2 p7zip squashfs-tools            Gentoo's debian precursor fails so miserably. 
(tried slipping it in FAIL) 

hardened I had to do from scratch , however 
unsquashfs -f -d /newworldorder/    newworldorder/filesystem.squashfs 
then stuffing into tarball ie dropbox upload at every Quarter quell of a change on 4 iso's is Tedious. 

Pentoo.ch 4 iso's     (Gentoo based) also more SECURITY toys  a number of things one could do besides a build-farm docker-esq chroot for packages being built. 
Symlink-latest-.iso's 

adding back portage via volume container , laymans in image so resyning the overlays tree is trivial. 

A: do like Gentoo's debian precursor alpine? if it will easily Add packages I want might make life easier. 
B: fetch the iso's 
C: chainsaw open iso & Nuke the iso file  newworldorder/tmp2
D: crack open into ./ of newworldorder the squashfs files content. 
E: self destruct , rflap move of files and dirs from newworldorder/

To many steps dockerhub will DIE.

**Comment by andyshinn** [comment]
How is this related to the Alpine Linux Docker image? Are you trying to move to Alpine? Unfortunately, I still don't understand your question. If you are looking to add 7zip and squashfs support in Alpine, you just need to do `apk -U add suqashfs-tools p7zip` to get the utilities.

**Comment by necrose99** [comment]
**I Will try to use alpine instead its smaller , will build a 32 bit and 64 bit root.fs seed. 
as its small light minimal but not as so too minimal** to hang myself. 
*apk -U add suqashfs-tools p7zip  add in tools*  , 
http://www.pentoo.ch/isos/latest-iso-symlinks/ 

** *my question is simply to find  better means of doing doing much the same as below* **, but with an ISO
squashfile and not having a remote build die from time out. 
alpine loads fast so I might be able to do thus, and seems better suited for the job.  many thanks.

** FROM 32bit/debian:jessie (adding more tools deps seams to choke and die) **
** 64 bit  FROM busybox,  (not yet in tools aint yet in busybox )** 
Alpine As a base per-container is rather a means to the same end, however more tools. but with less bloat, than using ubuntoo or debian. re-using the gentoo containers is well not working much as builds are slow , and time out and die. 

https://github.com/gentoo/gentoo-docker-images/blob/master/amd64-hardened/build.sh
 as i need a few tools to crack a 2 gig iso open , dump the squash into temp root , prior to alpine die , mv root step. 

Debian bootstrap still yields a 256 meg tarballs. 
**and from scratch Pentoo  2 gig tarballs. no fun** plus i have to constantly update by dumping iso sqashfs >>> tar.bz 
no its a Gentoo base but for the main containers Gentoo uses currently however building onto a container with 2-4 gigs worth of build steps not exactly good. or having to layer them up with 4 supported arches.  x88-default & hardened.  or AMD64 default &hardened 
**Basically Package build containers**.  but against a full-er kit and or usable for advance crypto studies. 
https://github.com/gentoo/gentoo-docker-images/blob/master/amd64-hardened/build.sh
<code>
suffix=$3 # e.g. -hardened
arch=$1
busybox_version=$2
dist="http://distfiles.gentoo.org/releases/${arch}/autobuilds/"
stage3="$(wget -q -O- ${dist}/latest-stage3-${arch}${suffix}.txt | tail -n 1 | cut -f 1 -d ' ')" 
##(replace with iso's instead) 

mkdir newWorldOrder; cd newWorldOrder  (append mkdir /isotemp) 
echo "Downloading and extracting ${stage3}..." ##(make that iso) 
wget -q -c "${dist}/${stage3}" get the iso.
bunzip2 -c $(basename ${stage3}) | tar --exclude "./etc/hosts" --exclude "./sys/*" -xf -
rm -f $(basename ${stage3}) ### replace with 7zip & squashfs unpack /newWorldOrder 
##sleep 120 going to need a min or 2 to unpack kill iso unpacksquashfs to /"nWO"
## permit Self Distruct to commence. 
wget -q -O /busybox "http://www.busybox.net/downloads/binaries/latest/busybox-${busybox_version}"
chmod +x /busybox
/busybox rm -rf /lib* /usr /var /bin /sbin /opt /mnt /media /root /home /run /tmp
/busybox cp -fRap lib* /
/busybox cp -fRap bin boot home media mnt opt root run sbin tmp usr var /
/busybox cp -fRap etc/* /etc/
cd /
#commit suicide
/busybox rm -rf newWorldOrder /busybox /build.sh /linuxrc
## {stage3 convert to iso reference. ) 
latest_stage3=$(curl "${base_url}/latest-stage3-amd64-hardened.txt" 2>/dev/null | grep -v '#' | awk '{print $1}')
stage3=$(basename "${latest_stage3}")

# Self destruct
rm -f /Dockerfile /build.sh

echo "Bootstrapped ${stage3} into /:"
ls --color -lah
</code>
