### ISSUE TITLE
Capacity to specify timezones by env var

### ISSUE THREAD

**Issue by paurullan** [gliderlabs/docker-alpine#113]
It would be great to be able to specify which timezone you run the container by just injecting the environment variable like in Debian:

```bash
 TZ: "Europe/Madrid"
```

**Comment by andyshinn** [comment]
This appears to already be supported by musl: http://wiki.musl-libc.org/wiki/Environment_Variables#TZ. Do you have an example that is not working?

**Comment by paurullan** [comment]
@andyshinn thanks for the tip! It seems you have to install the `tzdata` package or specify in the POSIX way. On a running Debian/Ubuntu you can find that information for example in `/usr/share/zoneinfo/Europe/Madrid`.

In my case it was easier to change the env var:
```
TZ: "Europe/Madrid" → "CET-1CEST,M3.5.0,M10.5.0/3"
```

http://stackoverflow.com/tags/timezone/info
https://pkgs.alpinelinux.org/package/main/x86_64/tzdata

**Comment by gdhnz** [comment]
This doesn't appear to be working on alpine:latest as the tzdata package is not installed.

Once the tzdata package is installed, it correctly sets the timezone from the TZ environment variable.
```
# date
Fri Mar 31 03:41:11 GMT 2017
/ # apk --update add tzdata
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
(1/1) Installing tzdata (2016i-r0)
Executing busybox-1.25.1-r0.trigger
OK: 9 MiB in 16 packages
/ # date
Fri Mar 31 16:41:36 NZDT 2017
```
