### ISSUE TITLE
[Alpine 3.3 regression] Missing busybox-suid package

### ISSUE THREAD

**Issue by frol** [gliderlabs/docker-alpine#121]
`busybox-suid` package provides correctly working `/usr/bin/su` (`/bin/su` exists, but since `/bin/busybox` doesn't have suid bit, it just doesn't work for regular users (`su: must be suid to work properly`)), `/usr/bin/passwd`, `/usr/bin/crontab`, and `/usr/bin/traceroute`.

/cc @andyshinn

**Comment by andyshinn** [comment]
Lets just move discussion to #122.
