### ISSUE TITLE
Marshmallow  for lg stylio

### ISSUE THREAD

**Issue by obsservationsmade3** [gliderlabs/docker-alpine#124]
Anyone  have a roll your  own around

**Comment by andyshinn** [comment]
Is this related to the Alpine Linux Docker image?

**Comment by obsservationsmade3** [comment]
No i am a newbue

**Comment by obsservationsmade3** [comment]
Sorry  for wrong post

Sent from Yahoo Mail on Android 
 
  On Sat, Dec 26, 2015 at 2:08 PM, Andy Shinn<notifications@github.com> wrote:   
Closed #124.
