### ISSUE TITLE
php-fpm package

### ISSUE THREAD

**Issue by kabudu** [gliderlabs/docker-alpine#125]
Alpine Linux does not appear to have the php-fpm package (either that or I've missed it!) which is essential for php users of nginx. What is the general process for getting packages added to Alpine Linux?

**Comment by andyshinn** [comment]
It exists for me:

```console
$ dri alpine apk --no-cache add php-fpm
fetch http://dl-4.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-4.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/4) Installing php-common (5.6.16-r0)
(2/4) Installing pcre (8.38-r0)
(3/4) Installing libxml2 (2.9.3-r0)
(4/4) Installing php-fpm (5.6.16-r0)
Executing busybox-1.24.1-r7.trigger
OK: 15 MiB in 15 packages
```

Generally, you submit patches to the aports git repository at http://git.alpinelinux.org/cgit/aports/ to add new packages. Packages usually start out in the `testing` repository and then later get promoted to `main` or `community`. They have also been know to take pull requests at https://github.com/alpinelinux/aports and copy the patch to their git repository.

**Comment by kabudu** [comment]
Great, thanks @andyshinn. I was going off of the list on the package index, here: https://pkgs.alpinelinux.org/packages. I didn't actually try it out, but it's good to know that it does exist already! Thanks for the break down on the process of getting new packages added.

**Comment by andyshinn** [comment]
It is actually a sub package of the php package. Check out the APKBUILD file.
