### ISSUE TITLE
32bit docker image?

### ISSUE THREAD

**Issue by julrichkieffer** [gliderlabs/docker-alpine#131]
All current docker images assume a 64-bit architecture. However, as I need a docker image with a 32-bit base OS, I was wondering:
 - can you provide a repository to a 32-bit supported image of Alpine, or alternatively
 - can you provide a dockerfile so I can build a 32-bit base image?

With this image, I'll create containers to run native Linux, Java 8 (wildfly) and .Net Core apps on MacOS X and 32-bit Ubuntu hosts (bare metal).

**Comment by andyshinn** [comment]
We don't have a way to provide any 32 bit images as we build on CircleCI which is 64 bit (I don't think we can request 32 bit VMs). Have you tried just cloning this repository and using the builder with a 32 bit host? During an image build, it should use the x86 packages if running on a 32 bit host.

**Comment by moul** [comment]
Hi @julrichkieffer, for non x86_64 images, you can give a look at [multiarch/alpine](https://hub.docker.com/r/multiarch/alpine/)

```console
$ docker run -it --rm multiarch/alpine:x86-v3.3 /bin/sh
# apk add file
(1/1) Installing file (5.25-r0)
Executing busybox-1.24.1-r7.trigger
lOK: 9 MiB in 17 packages
# file /bin/busybox
/bin/busybox: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-i386.so.1, stripped
```

However, `multiarch/alpine` support will stay very basic, you will probably to tweak the image a little bit to get something similar to the official `alpine` image.

See [update.sh](https://github.com/multiarch/alpine/blob/master/update.sh) for build details.

Tested on an `x86_64`, no `binfmt-support` required

**Comment by tianon** [comment]
Check out https://hub.docker.com/r/i386/alpine/ -- I managed to build 3.x images successfully using this repository's source. :smile: (https://hub.docker.com/r/armhf/alpine/ is possibly of interest too, built in the same way)

Source is at https://github.com/tianon/jenkins-groovy/blob/master/dsl/docker-multiarch/images/alpine.groovy; a tiny bit hacky, but it does the job. :+1:
