### ISSUE TITLE
How to add aufs support?

### ISSUE THREAD

**Issue by rkononov** [gliderlabs/docker-alpine#135]
I want to launch docker inside Alpine and unfortunately aufs is not present in most recent distibution.
Thanks.

**Comment by andyshinn** [comment]
This is a better question for upstream. Aufs is not in the mainline kernel and is essentialy a patch that would need to be added. I would try their [IRC channel](irc://irc.freenode.net/alpine-linux) or [mailing lists](http://lists.alpinelinux.org/).

**Comment by rkononov** [comment]
Thanks! (fixed issue by updating host os)
