### ISSUE TITLE
mongodb-3.2.1 failed to start mongo client on alpine:edge

### ISSUE THREAD

**Issue by zh-lab** [gliderlabs/docker-alpine#137]
```
alpine            edge                  002d302994b7        6 days ago          4.802 MB
```
```
docker run --rm -it alpine:edge sh

/ # 
/ # apk add mongodb --update-cache --repository http://dl-4.alpinelinux.org/alpine/edge/testing
fetch http://dl-4.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-4.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-4.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  so:libwiredtiger-2.6.0.so (missing):
    required by: mongodb-3.0.6-r0[so:libwiredtiger-2.6.0.so]
```

**Comment by andyshinn** [comment]
At first glance it looks like the MongoDB package needs to be rebuilt against wiredtiger 2.7.0 as it was bumped. Wiredtiger 2.6.0 doesn't appear to be available anymore. I'll try to bump the revision of MongoDB package soon unless someone else gets to it before me (the pkgrel just needs to be bumped).

**Comment by zh-lab** [comment]
MongoDB package is upgrade to mongodb-3.2.1 now, and it works ok.
@andyshinn thx! :smile:

**Comment by dangoodman** [comment]
Great, I was waiting for it too.

However, I'm not able to run `mongo` shell:
```
/ # mongo
MongoDB shell version: 3.2.1
too much recursion
exception: Failed to initialize JSContext
```

Is that the case for you too?

**Comment by zh-lab** [comment]
@dangoodman Yes,I have that case too.

**Comment by franz-josef-kaiser** [comment]
Can confirm that behavior with a build of `mvertes/alpine-mongo` as well. 

Sources: [Docker Hub](https://hub.docker.com/r/mvertes/alpine-mongo/) | [GitHub](https://github.com/mvertes/docker-alpine-mongo).

**Comment by franz-josef-kaiser** [comment]
@mvertes opened a [ticket in the Alpine Bug Tracker](http://bugs.alpinelinux.org/issues/5117) for that.

**Comment by franz-josef-kaiser** [comment]
Update: @mvertes fixed that bug upstream. Already got merged by Alpine devs in should be in the rolling release via `alpine:edge`. Should get closed here as well with *props* for @mvertes

**Comment by andyshinn** [comment]
Thanks for the updates. Is this something we can close out since we have patches upstream now?

**Comment by franz-josef-kaiser** [comment]
Well, Mr. Tiger should work now :)
