### ISSUE TITLE
List of possible tests to add

### ISSUE THREAD

**Issue by andyshinn** [gliderlabs/docker-alpine#14]
Some tests that I have been thinking of or have bitten me while messing with the build script:

* Proper timezone.
* Existence (or absence) of `apk-install` script.
* Cleanup of APKINDEX.
* Correct version.
* A package installs cleanly.
* Mirror is set correctly.

**Comment by jumanjiman** [comment]
> Proper timezone.

in https://github.com/docker-library/official-images/issues/390 (UTC all the things)

`date +%Z`

**Comment by andyshinn** [comment]
I have a test for this at https://github.com/gliderlabs/docker-alpine/blob/master/test/test_alpine-3.1.bats#L16-L20. Closed via 8e068e3a29e7d5323f4ac90d42f64590c9482acb.
