### ISSUE TITLE
Create images for ARM

### ISSUE THREAD

**Issue by fjcuadrado** [gliderlabs/docker-alpine#140]
Already there are a lot of cheap devices based on ARM (like raspberry pi) which can run docker (thanks hypriot team) and it would be really awesome to have updated alpine docker images, now you can use the one created by hypriot team but that image is 3.2 version).

Thanks for all your work!

**Comment by tianon** [comment]
GitHub's email gateway appears to be struggling today:

https://hub.docker.com/r/armhf/alpine/ might be of some interest here :smile:

**Comment by moul** [comment]
Here are two alternatives I created:

- https://hub.docker.com/r/multiarch/alpine/: minimal alpine image for x86_64, x86 and armhf
- https://hub.docker.com/r/scaleway/alpine/: based on the first one, contains more packages, used to generate the baremetal rootfs of Scaleway C1 servers

**Comment by fjcuadrado** [comment]
Thanks!

**Comment by andyshinn** [comment]
Similar to #131, we don't have a good way to build ARM images right now. But both Scaleway and armhf orgs are perfectly suitable ARM images at the moment.
