### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by matiasinsaurralde** [gliderlabs/docker-alpine#147]
Hi, when I run ```npm install -g gulp``` I get this, any clues?
```
npm ERR! Linux 4.1.18-boot2docker
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "gulp"
npm ERR! node v5.7.1
npm ERR! npm  v3.7.5
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:80
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/app/npm-debug.log
```
I thought it was a SSL issue, so I tried running ```npm config set strict-ssl false && npm config set registry http://registry.npmjs.org```, and I'm getting the same error.

**Comment by mattaitchison** [comment]
Are you able to post the contents of `/root/app/npm-debug.log`?

**Comment by andyshinn** [comment]
`getaddrinfo` errors are usually name resolution problems due to VirtualBox DNS proxy. Are you on Mac OS X using Docker Machine by any chance? See if https://github.com/boot2docker/boot2docker/issues/451#issuecomment-65432123 helps.

**Comment by matiasinsaurralde** [comment]
It seems it's a boot2docker issue, I rebooted the vm and it went fine!
Thank you!
