### ISSUE TITLE
Erro on apk add py-psycopg2

### ISSUE THREAD

**Issue by ebertti** [gliderlabs/docker-alpine#150]
Hi, can someone help me please?

I'm getting a error on running this command:
``` bash
RUN apk add --no-cache py-psycopg2

ERROR: unsatisfiable constraints:
  py-psycopg2 (missing):
    required by: world[py-psycopg2]
The command '/bin/sh -c apk add --no-cache py-psycopg2' returned a non-zero code: 1
````

I'm using this docker-image:

**FROM python:2.7.11-alpine**

**Comment by andyshinn** [comment]
That package is in the `testing` repository: https://pkgs.alpinelinux.org/package/testing/x86/py-psycopg2. You'll need to do something like:

```
apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing py-psycopg2
```

**Comment by numkem** [comment]
I've had to use `FROM alpine:edge` in order to make it work. What @andyshinn no longer worked.
