### ISSUE TITLE
permission problem

### ISSUE THREAD

**Issue by cdpb** [gliderlabs/docker-alpine#151]
Hi folks,

can someone support me with this issue:
http://stackoverflow.com/questions/35459276/nginx-alpine-docker-fails-without-previous-ls

is there a developer who can confirm or disconfirm if it is a alpine problem or not.

Regards

cdpb

**Comment by andyshinn** [comment]
I'm confused about what you are asking in regards to permissions. Are you asking why the nginx mkdir fails? You need to provide some more information to be able to debug (nginx.conf and other files) or a more minimal `Dockerfile` to reproduce. I can't reproduce that specific problem after removing all your `COPY` commands:

```
# su radicale -c 'nginx -t'
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Comment by cdpb** [comment]
thanks for investigate so far.
I'm confused because of this `ls`, it should not affect any permissions, but after I execute it, everything seems to be normal. The nginx.conf is also part of the gist, the rest of the files is in Radicale upstream repo ( https://github.com/Kozea/Radicale ). The only missing file is `radicale.passwd` ... I'll provide one to you inside the gist

**Comment by andyshinn** [comment]
I understand the issue now. I can reproduce it. I'm not sure yet where the problem lies. I'll spin up an Alpine VM to see if it is reproducible outside Docker.

**Comment by cdpb** [comment]
I already did this test with a native VM. I can't reproduce it, but maybe there is something special in the docker image that didn't occur in the native alpine image? However, maybe you will find the root cause

**Comment by cdpb** [comment]
Fixed with `overlayfs` rather than `AUFS` docker storage driver, thx for investigate @andyshinn
