### ISSUE TITLE
How can I install script command in alpine

### ISSUE THREAD

**Issue by kooksee** [gliderlabs/docker-alpine#160]
I like tiny alpine very much, while I can't install script command in alpine. when I am working on the terminal,I  record what I have done in the terminal. but now ,feel little sad.

**Comment by andyshinn** [comment]
Can you give an example of what you are trying to do?

**Comment by snc** [comment]
Just install the `util-linux` package and you will get the `script` command.

**Comment by andyshinn** [comment]
Closing as this has been answered. If the previous answer isn't working then please reopen.

**Comment by ogbofjnr** [comment]
The problem is that installing it will take 350mb, which make no sense of using alpine. Is there a way to install only one command?

**Comment by ITJamie** [comment]
+1 on script being in a massive package. would be nice to see it get split

**Comment by ericwq** [comment]
try util-linux-misc, it's 3.7mb.
