### ISSUE TITLE
BusyBox ash MAILPATH HISTFILE

### ISSUE THREAD

**Issue by jasonmader** [gliderlabs/docker-alpine#163]
The BusyBox shell in Alpine Linux checks for new mail, but by default it checks for the existance of the file named `MAILPATH` in the current working directory when the environment variable of the same name isn’t set. The shell also saves a history file by default. Both features can be disabled in the ash build for BusyBox, which seems like a good idea for a container OS.

There’s also a file `/etc/profile.d/color_path` that would never be executed by the for loop in `/etc/profile` because the extension is not .sh

```
stat("MAILPATH", 0x7ffe0554bc98)        = -1 ENOENT (No such file or directory)

#if ENABLE_ASH_MAIL
    { VSTRFIXED|VTEXTFIXED|VUNSET, "MAIL"      , changemail      },
    { VSTRFIXED|VTEXTFIXED|VUNSET, "MAILPATH"  , changemail      },
#endif

open("/root/.ash_history", O_RDONLY)    = 3

#if ENABLE_FEATURE_EDITING_SAVEHISTORY
    { VSTRFIXED|VTEXTFIXED|VUNSET, "HISTFILE"  , NULL            },
#endif

```

[ash.c](https://git.busybox.net/busybox/tree/shell/ash.c)

**Comment by andyshinn** [comment]
I'm not sure what the question is here. What are the proposed fixes? Keep in mind, Alpine is not a container OS. This is a Docker image built using Alpine Linux (which is a normal Linux distribution) as a base. If the changes proposed make sense for a normal Linux desktop or server as well, then we can request them upstream.

**Comment by jasonmader** [comment]
At the very least, the default of having the ash shell check for the existence of a file named "MAILPATH" in the current working directory seems unexpected.

And the dangling unused file `color_path` might have been meant to be named `color_path.sh`

**Comment by frol** [comment]
As to `color_path` (BTW, it seems that you have mistyped as it is `color_prompt`), according to the comments on the top of the file, it is intended to be named like that:

```
# rename this file to color_prompt.sh to actually enable it
```

P.S. [I have been curious about this file before](http://bugs.alpinelinux.org/issues/5109).

**Comment by andyshinn** [comment]
I'm going to close this as it isn't much we can change in this image. It might be an issue worth bringing up in the Alpine bug tracker at http://bugs.alpinelinux.org/projects/alpine/issues. But we don't build BusyBox specifically for this image so it isn't something we can change.
