### ISSUE TITLE
When will :edge become :latest?

### ISSUE THREAD

**Issue by thockin** [gliderlabs/docker-alpine#165]
:edge has the DNS fixes we need to use Alpine in Kubernetes - what has to happen for :edge to get promoted?

**Comment by tianon** [comment]
If https://bugs.alpinelinux.org/versions/102 is accurate, then Alpine 3.4 is in progress and possibly scheduled for as soon as 2016-05-03. :smile:

**Comment by thockin** [comment]
thanks!

**Comment by PuKoren** [comment]
+1 for publishing!

We really need the DNS resolving fix of edge in production 👍 (Docker Cloud)

**Comment by bjartek** [comment]
Any ETA on this?

**Comment by andyshinn** [comment]
The 3.4 repo is up (http://dl-cdn.alpinelinux.org/alpine/v3.4/) but it is still in the process of building all the packages and fixing build failures. I'd guess we're about another 1 to 2 weeks away from a release.

**Comment by bjartek** [comment]
This can be closed now?

**Comment by mattaitchison** [comment]
docker-library/official-images#1801
