### ISSUE TITLE
official image lacks apk-install

### ISSUE THREAD

**Issue by jumanjiman** [gliderlabs/docker-alpine#17]
is this by accident or on purpose?

if accident, then a big :+1: for https://github.com/gliderlabs/docker-alpine/issues/14

```
user@wormhole:~$ docker pull alpine:latest
511136ea3c5a: Already exists 
b0b08730b93c: Already exists 
alpine:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Status: Image is up to date for alpine:latest
user@wormhole:~$ docker run --rm -t alpine:latest find / -name apk-install
user@wormhole:~$ 
```

**Comment by progrium** [comment]
official image maintainers wouldn't allow it. our version gliderlabs/alpine will continue to be available built from same source but with apk-install

**Comment by jumanjiman** [comment]
ack, thx!

**Comment by franz-josef-kaiser** [comment]
Please ignore the last reference – had a typo `17` vs `137` when referencing issues.
