### ISSUE TITLE
sha256sum does not work on alpine

### ISSUE THREAD

**Issue by dinogun** [gliderlabs/docker-alpine#174]
With sha256sum / md5sum, I see the following error for a downloaded file.
sha256sum: WARNING: 1 of 1 computed checksums did NOT match
However the same file from the same network location works fine on ubuntu.
Doing a local copy instead of downloading from the network still gives the same error.

**Comment by frol** [comment]
`md5sum` has been working fine for me since over a year ago. I have just also tested `sha256sum` on several files and everything is fine.

**Comment by dinogun** [comment]
Looked at this a little bit more closely, it appears that sha256sum expects two spaces between the sum and the filename on Alpine, whereas it works even with a single space on ubuntu.

~ # echo "a66b20423b7d849aa8ef448b98b41d18c45a30bf3fe952cc2ba4760600b18087  docker-1.10.0" | sha256sum -c -
docker-1.10.0: OK
~ # echo "a66b20423b7d849aa8ef448b98b41d18c45a30bf3fe952cc2ba4760600b18087 docker-1.10.0" | sha256sum -c -
sha256sum: WARNING: 1 of 1 computed checksums did NOT match

The error is not descriptive either which is what threw me off. Thanks anyway !

**Comment by helpermethod** [comment]
@dinogun Thank you so much, this was driving me crazy!

**Comment by henning-schild** [comment]
Why is this "Closed", that stupid two spaces thing is a workaround and not a solution! It seems to be coming from busybox and deserves a fix rather than tons of projects adding a "fake space" to please alpine/busybox.

**Comment by mycodedoesnotcompile2** [comment]
The correct fix is to install the `coreutils` package on alpine, in order to use the GNU implementation of `sha256sum`, overriding the crappy `busybox` implementation.

**Comment by henning-schild** [comment]
In busybox >= 1.36.1 it should be fixed

https://github.com/mirror/busybox/commit/3ad3aa6441ebaf817137051de2b74cb6b4379e7f
