### ISSUE TITLE
alpinelinux.org is down completely

### ISSUE THREAD

**Issue by waits** [gliderlabs/docker-alpine#175]
I see #164 about CDN performance being poor, but today I'm unable to access it at all. In fact, every `*.alpinelinux.org` domain is down. I can't get any DNS queries through from any machine (tried a few remote VMs too). Looks like the domain is still registered though.

```
$ nslookup alpinelinux.org 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find alpinelinux.org: SERVFAIL

$ nslookup dl-cdn.alpinelinux.org 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find alpinelinux.org: SERVFAIL
```

```
$ nslookup
> set querytype=soa
> alpinelinux.org
** server can't find alpinelinux.org: SERVFAIL
```

**Comment by mattaitchison** [comment]
You can still access the CDN via http://alpine.gliderlabs.com

**Comment by waits** [comment]
Thanks. Is that what everyone should use from now on?

**Comment by frol** [comment]
It seems to be back up and running now.

**Comment by waits** [comment]
Yep, thanks!

**Comment by kabudu** [comment]
It was working for me just a moment ago and now it's not. Possibly propagation flapping?

```
$ nslookup alpinelinux.org
;; Got SERVFAIL reply from 8.8.8.8, trying next server
Server:         8.8.4.4
Address:        8.8.4.4#53

** server can't find alpinelinux.org: SERVFAIL
```

**Comment by ncopa** [comment]
should be fixed now.

**Comment by kabudu** [comment]
Thanks, but it looks like it's gone again! :/

**Comment by waits** [comment]
Still working from all of my GCE servers. Maybe the NS records haven't propagated everywhere yet.
