### ISSUE TITLE
IO ERROR when running "apk update"

### ISSUE THREAD

**Issue by jaschweder** [gliderlabs/docker-alpine#176]
I'm having troubles when running `apk update` command, I can curl them perfecly, any idead of what this can be ?
```sh
/ # apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.3/main: IO ERROR
WARNING: Ignoring APKINDEX.5a59b88b.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.3/community: IO ERROR
WARNING: Ignoring APKINDEX.7c1f02d6.tar.gz: No such file or directory
2 errors; 31 distinct packages available
```

**Comment by frol** [comment]
I have seen such symptoms a long time ago (around Docker 1.6 release), and it was related to Docker storage engine, something along these lines: http://stackoverflow.com/questions/35459276/nginx-alpine-docker-fails-without-previous-ls#comment60030171_35459276

**Comment by jaschweder** [comment]
There was some firewall troubles in my current connection, thanks for all folks :smile:

**Comment by boddumanohar** [comment]
@jaschweder  I too have the same error, I my firewall doesn't support http:// protocol. How do I force docker fetch to use `https://`

so the line
`fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz` should change to 
`fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz` 

How do I force docker to use https by default

**Comment by bravacor** [comment]
I had the same issue as above:

bare-metal-host:~# apk update
fetch http://mirror.math.princeton.edu/pub/alpinelinux/armhf/APKINDEX.tar.gz
ERROR: http://mirror.math.princeton.edu/pub/alpinelinux/: No such file or directory
WARNING: Ignoring APKINDEX.bcf95d26.tar.gz: No such file or directory
fetch http://mirror.math.princeton.edu/pub/alpinelinux/v3.8/main/armhf/APKINDEX.tar.gz
fetch http://mirror.math.princeton.edu/pub/alpinelinux/v3.8/community/armhf/APKINDEX.tar.gz
v3.8.4-46-gd19f2800a1 [http://mirror.math.princeton.edu/pub/alpinelinux/v3.8/main]
v3.8.4-44-g70fa4e605a [http://mirror.math.princeton.edu/pub/alpinelinux/v3.8/community]
1 errors; 9337 distinct packages available


I solved this by setting my /etc/apk/repositories file as such:

#http://mirror.math.princeton.edu/pub/alpinelinux/
http://mirror.math.princeton.edu/pub/alpinelinux/v3.8/main
http://mirror.math.princeton.edu/pub/alpinelinux/v3.8/community
