### ISSUE TITLE
make-4.1-r0: BAD signature

### ISSUE THREAD

**Issue by tifayuki** [gliderlabs/docker-alpine#177]
```
(15/40) Installing make (4.1-r0)
ERROR: make-4.1-r0: BAD signature
```

I tried install build-base in the Dockerfile and get an error of the make package, which is submitted like a couple hours ago(http://nl.alpinelinux.org/alpine/edge/main/x86_64/)

`make-doc-4.1-r0.apk	2016-May-26 15:49:52	354.8K	application/x-tgz`

**Comment by wannabesrevenge** [comment]
+1 Also getting this error. Running boot2docker on OSX

**Comment by ncopa** [comment]
i had to downgrade make from 4.2 -> 4.1. The package got rebuilt but cache had old version so signature check failed. I am working around it by bumping pkgrel. `make-4.1-r1` should be find.

This issue can be closed.

**Comment by blackgear** [comment]
make-4.2-r0: BAD signature again...

```
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM alpine:edge
 ---> 79c898d40088
Step 2 : RUN apk --update add make
 ---> Running in 33deadff99b2
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/1) Installing make (4.2-r0)
ERROR: make-4.2-r0: BAD signature
1 errors; 5 MiB in 11 packages
The command '/bin/sh -c apk --update add make' returned a non-zero code: 1
```
Maybe there is something wrong with the package management ?

**Comment by ncopa** [comment]
@blackgear can you please try again? `make-4.2-r1` should be ok.

**Comment by blackgear** [comment]
@ncopa It works, thanks :+1:

**Comment by anthedung** [comment]
Hi, I have this same issue again, the package seems to have been recently updated "30-Apr-2018 20:01", please kindly check. Thanks.

fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.5/main: BAD archive
WARNING: Ignoring APKINDEX.c51f8f92.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.5/community: BAD archive
WARNING: Ignoring APKINDEX.d09172fd.tar.gz: No such file or directory
fetch http://dl-4.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-4.alpinelinux.org/alpine/edge/community: BAD archive
WARNING: Ignoring APKINDEX.e76b60f6.tar.gz: No such file or directory

**Comment by ncopa** [comment]
I am not able to reproduce.

@clandmeter can you please have a look at this?

**Comment by clandmeter** [comment]
Hi

You are having issues on both dl-cdn and dl-4?
From the error report this looks more like a network/system issue.

Which command did you run to generate this error?

**Comment by anthedung** [comment]
Hi, it's part of my Dockerfile.build. Here was the command I run 
RUN echo "@edge http://dl-4.alpinelinux.org/alpine/v3.6/community" >> /etc/apk/repositories && apk update

**Comment by clandmeter** [comment]
I cannot reproduce this issue so my guess its something local like I mentioned before.
