### ISSUE TITLE
Failed to build golang 1.4.3 on Alpine 3.4

### ISSUE THREAD

**Issue by dochang** [gliderlabs/docker-alpine#182]
I tried to build golang 1.6 on `alpine:3.4` image but it failed on bootstraping.

It can be built on `alpine:3.3`.

I put `Dockerfile` at this [gist][].

[gist]: https://gist.github.com/dochang/4d47de0ac3f2cd83c2c7ad4728328928

The error log:

```
/usr/local/bootstrap/go/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
/usr/local/bootstrap/go/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
runtime/cgo(.text): unexpected relocation type 298
runtime/cgo(.text): unexpected relocation type 298
```

**Comment by mattaitchison** [comment]
I think this is related to golang/go#13114. 

Can you try using the changes from alpinelinux/aports@b63af710f28488e8ed7dec4c38c79f2964c02bb1 to see if they resolve this issue?

**Comment by dochang** [comment]
The patch fixes this bug! Thank you!
