### ISSUE TITLE
can't use service or rc-service

### ISSUE THREAD

**Issue by luisrudge** [gliderlabs/docker-alpine#183]
![image](https://cloud.githubusercontent.com/assets/941075/15807950/de296bde-2b40-11e6-8612-684702a7c165.png)

**Comment by luisrudge** [comment]
I just found https://github.com/gliderlabs/docker-alpine/issues/26 and it seems to be the same question.. So, what should I do to run the docker daemon inside an alpine docker image?

**Comment by westy92** [comment]
I'm trying to run a service inside of the docker `alpine:edge` image but am getting the same result.

For context:
```
cat /etc/*-release
3.4.0
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.4.0
PRETTY_NAME="Alpine Linux v3.4"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

```
rc-service
bash: rc-service: command not found
```

**Comment by luisrudge** [comment]
yeah, docker images based on alpine don't have service or rc-service enabled.

**Comment by dondre** [comment]
How to enable?

**Comment by riccardoravaro** [comment]
rc-service is part of openrc, install openrc

`apk add openrc --no-cache`

**Comment by ORESoftware** [comment]
Alpine is so great lol

**Comment by simmessa** [comment]
I'm also having this problem, any ideas?

```
bash-4.4# service docker start
 * WARNING: docker is already starting
```

Thanks!

**Comment by ncopa** [comment]
openrc is normally started via `/sbin/init`. But running an init system in docker is normally not recommended.

**Comment by m0ar** [comment]
I'm hitting these errors as well. Any progress @rm-rf-etc ?

**Comment by unihon** [comment]
> I'm also having this problem, any ideas?
> 
> ```
> bash-4.4# service docker start
>  * WARNING: docker is already starting
> ```
> Thanks!

Do you know the answer now?

**Comment by yorushika** [comment]
I'm tired about this stuff. Yes, it's "small" and "secure", yes it is because even me the root user of it cannot do anything I want in it.

**Comment by marzdgzmn** [comment]
> I'm tired about this stuff. Yes, it's "small" and "secure", yes it is because even me the root user of it cannot do anything I want in it.

Time to turn around and go back. hehe

**Comment by wollf01** [comment]
Any update on this issue? 
I am getting the same problem.

**Comment by cafesanu** [comment]
Same issue. I'm on alpine 3.9. So I did
```
apk add --no-cache docker openrc
service docker start
```
ouput:
```
 * WARNING: docker is already starting
```
But it's not!
```
$ ps
PID   USER     TIME  COMMAND
    1 root      0:00 /dev/init -- /bin/sh
    6 root      0:00 /bin/sh
   62 root      0:00 /bin/bash
  309 root      0:00 ps
```

```

**Comment by comunitius** [comment]
Same issue. I'm on alpine 3.9. So I did
```
apk add --no-cache docker openrc
service docker start
```
ouput:
```
 * WARNING: docker is already starting
```
But it's not!
```
$ ps
PID   USER     TIME  COMMAND
    1 root      0:00 /dev/init -- /bin/sh
    6 root      0:00 /bin/sh
   62 root      0:00 /bin/bash
  309 root      0:00 ps
```

**Comment by graywolf** [comment]
I'm not sure why you care so much about the `service docker start`... What is wrong with

```
+   $ docker run -it --init --rm --privileged --volume /var/lib/docker alpine
/ # apk add --no-cache docker
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/12) Installing ca-certificates (20190108-r0)
(2/12) Installing libseccomp (2.4.1-r0)
(3/12) Installing runc (1.0.0_rc8-r0)
(4/12) Installing containerd (1.2.9-r0)
(5/12) Installing libmnl (1.0.4-r0)
(6/12) Installing libnftnl-libs (1.1.3-r0)
(7/12) Installing iptables (1.8.3-r0)
(8/12) Installing tini-static (0.18.0-r0)
(9/12) Installing device-mapper-libs (2.02.184-r0)
(10/12) Installing docker-engine (18.09.8-r0)
(11/12) Installing docker-cli (18.09.8-r0)
(12/12) Installing docker (18.09.8-r0)
Executing docker-18.09.8-r0.pre-install
Executing busybox-1.30.1-r2.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 278 MiB in 26 packages
/ # dockerd >/tmp/docker.stdout 2>/tmp/docker.stderr &
/ # docker run --init --rm -it alpine
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
9d48c3bd43c5: Pull complete
Digest: sha256:72c42ed48c3a2db31b7dafe17d275b634664a708d901ec9fd57b1529280f01fb
Status: Downloaded newer image for alpine:latest
/ # echo 'This is inside nested docker'
This is inside nested docker
/ # touch /xxx
/ # ls -l /xxx
-rw-r--r--    1 root     root             0 Sep 20 22:58 /xxx
/ # / # echo 'This is inside the original container'
This is inside the original container
/ # ls -l /xxx
ls: /xxx: No such file or directory
/ #
```

?

**Comment by johnkawakami** [comment]
This isn't for this project, but I had to deal with this annoyance in an apache container.

A the end of my Dockerfile, I have this.
`COPY start.sh .`

`CMD /bin/sh /start.sh`

Then start.sh contains:

```
#! /bin/sh

rc-status

touch /run/openrc/softlevel

rc-service apache2 start

cd /var/log/apache2

tail -f access.log error.log
```

So, the magic is in getting rid of some of the configuration from the container, and putting it into the start script.

The start script does the last-minute config. `rc-status` causes /run/openrc to be built, so the touch command will work. `rc-service apache2 start` starts the server, because it wasn't running, because openrc was complaining that it wasn't run as init.

It's painful.

**Comment by graywolf** [comment]
There's also https://github.com/dockage/alpine/blob/master/3.9/openrc/Dockerfile . You then could just

```
rc-update add apache2
```

in you dockerfile and not touch ENTRYPOINT/CMD. It will start the openrc in the container as normal boot would.

**Comment by LeslieSun** [comment]
So has the issue not progressed so far?

**Comment by graywolf** [comment]
This issue is closed, so I'm not sure any progress can be expected.

What progress would you like to see? There generally should not be a need to run openrc in docker container.

**Comment by fluxx-sleblanc** [comment]
I'm running a couple of different processes in an alpine docker container and watch their output with rsyslog. I wanted to use openrc so that I could reload rsyslogd after log file rotation - however, I discovered that I could simply have rsyslog output directly to /proc/1/fd/0, instead of a log file. 
So, no need for openrc, I can simply run whatever processes I need directly in the entrypoint script.

Just posting this here in case someone lands on this page while searching for a similar problem.

**Comment by webchi** [comment]
I've thought that I'm clever one ... nope xD
```
 $ rc-update add docker boot && service docker restart
  * service docker added to runlevel boot
  * WARNING: docker is already starting
```

**Comment by MorenoGentili** [comment]
Instead of using `rc-service`,  you can/should just run `supervisord` and then let it spawn any additional process in foreground.
See this sample.
https://github.com/TrafeX/docker-php-nginx

**Comment by domibay-hugo** [comment]
I figured out this **Workaround** to be able to start **Secondary Services**
[Workaround for Secondary Services](https://github.com/gliderlabs/docker-alpine/issues/437#issuecomment-662501986)

**Comment by tarek-chen** [comment]
> stopped



> What then is the process for getting docker running?
> 
> ```
> ~ # apk add openrc --no-cache
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
> (1/2) Installing openrc (0.35.5-r4)
> Executing openrc-0.35.5-r4.post-install
> (2/2) Installing docker-openrc (18.06.1-r0)
> Executing busybox-1.28.4-r0.trigger
> OK: 187 MiB in 26 packages
> ~ # which service
> /sbin/service
> ~ # service docker start
>  * WARNING: docker is already starting
> ~ # service docker status
>  * You are attempting to run an openrc service on a
>  * system which openrc did not boot.
>  * You may be inside a chroot or you may have used
>  * another initialization system to boot this system.
>  * In this situation, you will get unpredictable results!
>  * If you really want to do this, issue the following command:
>  * touch /run/openrc/softlevel
> ~ # touch /run/openrc/softlevel
> touch: /run/openrc/softlevel: No such file or directory
> ~ # mkdir -p /run/openrc
> ~ # touch /run/openrc/softlevel
> ~ # service docker status
>  * status: stopped
> ~ # service docker start
>  * WARNING: docker is already starting
> ~ # service docker restart
>  * WARNING: docker is already starting
> ~ # service docker stop
>  * ERROR: docker stopped by something else
> ~ # service docker start
>  * WARNING: docker is already starting
> ```

you can find its status still is stopped if you perform 'service docker status' after 'Service docker start'
always, so fxxking sad

**Comment by JsThiago** [comment]
i dont know if anyone still has this problem but running sudo openrc worked for me

**Comment by alexdowad** [comment]
> you can find its status still is stopped if you perform 'service docker status' after 'Service docker start' always, so fxxking sad

Just ran into the same issue, peeked at the source code for OpenRC to see what it is doing, ran with `strace` to confirm.

It turned out that you also need to `mkdir /run/openrc/exclusive`.

**Comment by lingchuL** [comment]
> > you can find its status still is stopped if you perform 'service docker status' after 'Service docker start' always, so fxxking sad
> 
> Just ran into the same issue, peeked at the source code for OpenRC to see what it is doing, ran with `strace` to confirm.
> 
> It turned out that you also need to `mkdir /run/openrc/exclusive`.

Thanks a lot! Worked for me!

**Comment by DadiAnas** [comment]
Sum up, for `docker` daemon as an example:

```bash
apk add openrc  --no-cache
mkdir -p /run/openrc/exclusive
touch /run/openrc/softlevel

apk add docker
service docker start
rc-update add docker
```

**Comment by Fungus-00** [comment]
> Sum up, for `docker` daemon as an example:
> 
> ```shell
> apk add openrc  --no-cache
> mkdir -p /run/openrc/exclusive
> touch /run/openrc/softlevel
> 
> apk add docker
> service docker start
> rc-update add docker
> ```

It works indeed! Not only for docker, but sshd and any others.

**Comment by iltafah** [comment]
> ```shell
> 
> apk add docker
> service docker start
> rc-update add docker
> ```

Thanks I faced the same problem when running `vsftpd` with `rc-service`, it works now.
Oh almighty God! guide Alpine creators to write good Docs, Amen

**Comment by iltafah** [comment]
> > you can find its status still is stopped if you perform 'service docker status' after 'Service docker start' always, so fxxking sad
> 
> Just ran into the same issue, peeked at the source code for OpenRC to see what it is doing, ran with `strace` to confirm.
> 
> It turned out that you also need to `mkdir /run/openrc/exclusive`.


Thanks I faced the same problem when running `vsftpd` with `rc-service`, it works now.
Oh almighty God! guide Alpine creators to write good Docs, Amen
