### ISSUE TITLE
Can not reduce size of the docker image after deleting the build tools from child image that were installed in base image

### ISSUE THREAD

**Issue by sam1111** [gliderlabs/docker-alpine#186]
Hi,

I am using docker-alpine 3.3 as the base image and building another image from it. Following is the dockerfile for this

FROM xxx/alpine3.3:latest
MAINTAINER xxx@xxx.com 
RUN apk update
RUN apk add --update bash 
RUN apk add --update nodejs
RUN apk add --update curl 
RUN npm install -g gulp-cli
RUN apk add --update python  
RUN apk add --update make 
RUN apk add --update g++

Then this created docker images is used as the base image for another docker file where I do npm install and then remove the build tools like python, make and g++ after npm install. Following is the docker file
FROM dockerbase:latest
MAINTAINER xxx@xxx.com 
COPY common /opt/project1324/common
RUN /usr/bin/npm install
RUN apk del python
RUN apk del make
RUN apk del g++

But the size of the docker image has no difference for the cases when I delete those packages and do not delete those packages. Infact, the size is a little bit more when I delete those packages.

Is there a way to delete those build tools from all the layers of docker image so that the size of the docker image decreases. 

How can I remove these build tools?

**Comment by krallin** [comment]
@sam1111 you can't prevent those tools from making your image bulkier unless you use a third-party tool to squash your layers. Here are a few relevant links:

- http://stackoverflow.com/questions/24394243/why-are-docker-container-images-so-large
- https://github.com/goldmann/docker-squash#squashing

**Comment by ghostbar** [comment]
Don't do this; what you should be doing is using volumes to get the resulting code out of the container and getting that resulting code into a smaller image.

This is not how docker works, so what you are trying to do is the wrong way.

(And this can be closed, since is not an issue with the alpine image)

**Comment by andyshinn** [comment]
As stated by the other comments, this isn't an issue with Alpine but a fundamental way the layered filesystems work. They are additive, you cannot remove data from a previous layer.
