### ISSUE TITLE
wget returns error -- can't execute 'ssl_helper': No such file or directory

### ISSUE THREAD

**Issue by peterpd** [gliderlabs/docker-alpine#188]
with Alpine Linux v3.4, when doing wget got errors.
ex:
bash-4.3# wget https://get.docker.com/builds/Linux/x86_64/docker-1.9.1.tgz

Connecting to get.docker.com (54.230.7.103:443)
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer

tried
apk update
apk add ca-certificates
update-ca-certificates

But it does not help

**Comment by tianon** [comment]
Try adding the "openssl" package as well -- that should do the trick.

("wget" shells out to "openssl" as its "ssl_helper")

**Comment by peterpd** [comment]
tried apk add openssl. ssl_helper error is gone. but still get error:
Connecting to get.docker.com (54.192.142.119:80)
Connecting to get.docker.com (54.230.207.99:443)
wget: error getting response: Connection reset by peer

**Comment by peterpd** [comment]
It helped with:
apk add ca-certificates wget

**Comment by c0b** [comment]
@tianon but there is still the problem: why downloading a regular http link also require the ssl_helper?
As I see the default wget is a busybox version wget, can the default `alpine` make it able to download http links?

```console
/ # wget http://get.docker.com/builds/Linux/x86_64/docker-1.9.1.tgz
Connecting to get.docker.com (54.192.119.104:80)
Connecting to get.docker.com (54.192.119.47:443)
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer

/ # wget --help
BusyBox v1.24.2 (2016-06-23 08:49:16 GMT) multi-call binary.

Usage: wget [-csq] [-O FILE] [-Y on/off] [-P DIR] [-U AGENT] [-T SEC] URL...

Retrieve files via HTTP or FTP

	-s	Spider mode - only check file existence
	-c	Continue retrieval of aborted transfer
	-q	Quiet
	-P DIR	Save to DIR (default .)
	-T SEC	Network read timeout is SEC seconds
	-O FILE	Save to FILE ('-' for stdout)
	-U STR	Use STR for User-Agent header
	-Y	Use proxy ('on' or 'off')
```

**Comment by tianon** [comment]
I would imagine that link is probably doing an https redirect.

**Comment by c0b** [comment]
right; regular http links are ok

**Comment by fxpires** [comment]
Old thread, but just for reference: I changed the Dockerfile FROM to alpine:3.16 and it worked.
