### ISSUE TITLE
Document difference between gliderlabs and official image

### ISSUE THREAD

**Issue by pikeas** [gliderlabs/docker-alpine#19]
I see an extra `-c` flag for the gliderlabs build options. Is this the only difference, and what does this flag mean?

**Comment by jumanjiman** [comment]
> what does this flag mean?

it adds the `apk-install` helper script

* the option: https://github.com/gliderlabs/docker-alpine/blob/master/builder/scripts/mkimage-alpine.bash#L95
* its usage: https://github.com/gliderlabs/docker-alpine/blob/master/builder/scripts/mkimage-alpine.bash#L76

related: https://github.com/gliderlabs/docker-alpine/issues/17#issuecomment-83591985

**Comment by andyshinn** [comment]
@jumanjiman is correct. Also follow #18 as we will likely remove it in Alpine 3.2.

**Comment by pikeas** [comment]
@andyshinn Thanks for the explanation. Could you add a mention to the docs?

**Comment by andyshinn** [comment]
We're actually deprecating the `apk-install` script. But you can see the documented options in the builder `README.md` at https://github.com/gliderlabs/docker-alpine/tree/master/builder. You should be able to use this to compare different builds (though after Alpine 3.2 they will start using the same options).
