### ISSUE TITLE
Missing setup scripts?

### ISSUE THREAD

**Issue by revington** [gliderlabs/docker-alpine#196]
I'm trying to create an sftp server. Trying to `RUN /sbin/setup-sshd -c openssh` throws

```
Sending build context to Docker daemon  12.8 kB
Step 1 : FROM alpine:3.4
 ---> 4e38e38c8ce0
....
Step 10 : RUN /sbin/setup-sshd -c openssh
 ---> Running in 5f09a706f481
/bin/sh: /sbin/setup-sshd: not found
The command '/bin/sh -c /sbin/setup-sshd -c openssh' returned a non-zero code: 127
```

There are no `setup-*` scripts in `/sbin`

**Comment by andyshinn** [comment]
Yea, we exclude a lot of unnecessary stuff from the base image. You can get these by installing the `alpine-conf` package if you really want them.
