### ISSUE TITLE
Some http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/ paths result in 503

### ISSUE THREAD

**Issue by tristanls** [gliderlabs/docker-alpine#210]
While it is possible for me to navigate the directory structure of 
http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/ 
in the browser, some paths, such as 
`http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz` 
result in `Error 503 No route to host`. Some other package paths, for example: 
`http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/abcde-doc-2.7.2-r0.apk`
, result in similar error. For some reason 
`http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/zsh-5.2-r0.apk` 
downloaded fine.

Look like varnish cache related issues:
```
Error 503 No route to host

No route to host

Guru Mediation:

Details: cache-dfw1838-DFW 1471960403 3282534343

Varnish cache server
```

**Comment by Multiply** [comment]
This should now be resolved. https://status.fastly.com/incidents/0523znjnppc4

**Comment by tristanls** [comment]
Resolved for me.
