### ISSUE TITLE
wget to support HTTPS

### ISSUE THREAD

**Issue by gliptak** [gliderlabs/docker-alpine#218]
A number of bootstrap scripts (like https://bootstrap.pypa.io/get-pip.py or https://get.haskellstack.org/) are being served using HTTPS, which wget doesn't seem to support in the Alpine base image.
Based on https://bugs.alpinelinux.org/issues/5376 I ran
```
apk upgrade libssl1.0 --update-cache
apk add wget ca-certificates
```
which enabled HTTPS support.
Could this be made part of the base image?
Thanks

**Comment by ncopa** [comment]
The problem with adding those to the base image is that not everyone needs them and things that are added to base image cannot be removed. (you can remove but it will not reduce space)

Instead you can do:
````Dockerfile
...
RUN apk add --no-cache --virtual .bootstrap-deps wget ca-certificates \
    && <do the bootstrap script thingy here> \
    && apk del .bootstrap-deps
````

That way you will temporarily install the deps needed to do your thing and then remove those when no longer needed.

**Comment by gliptak** [comment]
Thank you @ncopa for pointing out the build step (I will make use of :) ). Image size being a concern, maybe wget could also be removed from the base image and could be added (temporarily) by the users who require it (and they could configure with or without HTTPS support)?

**Comment by andyshinn** [comment]
The `wget` in the base image is actually provided by BusyBox. Check out the built-in utilities at https://busybox.net/downloads/BusyBox.html.

**Comment by gliptak** [comment]
@andyshinn Thank you for the pointer. I submitted https://bugs.busybox.net/show_bug.cgi?id=9376
