### ISSUE TITLE
interpreter /lib64/ld-linux-x86-64.so.2?

### ISSUE THREAD

**Issue by gliptak** [gliderlabs/docker-alpine#219]
I would like to run an executable described as:
```
/tmp/ghc-8.0.1 # file utils/ghc-pwd/dist-install/build/tmp/ghc-pwd
utils/ghc-pwd/dist-install/build/tmp/ghc-pwd: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=9fcf1bc38db049d6bafc6e611c09b6700071bfbb, not stripped
```
Is there a way to install ```/lib64/ld-linux-x86-64.so.2``` (I couldn't find a package containing it ...)?

Thanks

**Comment by ncopa** [comment]
The binary you try to run is linked against GNU libc so it will not work, just like binaries compiled for windows or OSX will not work.

That said, musl libc provides partial GNU libc compatibility, which means that some binaries will actually work, even if there are no guarantee. Try `apk add libc6-compat`. It may or may not work.

If it does not work then you will have to use a system the binary is built for (eg debian or similar)

**Comment by gliptak** [comment]
Thank you for the details @ncopa

**Comment by rdesgroppes** [comment]
@gliptak
> Adding `apk add libc6-compat` didn't help.

Try `apk add gcompat` instead (https://pkgs.alpinelinux.org/package/edge/community/x86/gcompat),

**Comment by jlison** [comment]
This fixed it for me: https://github.com/rails/tailwindcss-rails/issues/115#issuecomment-1004896047
```
apk add build-base gcompat 
```
