### ISSUE TITLE
apk add openssl and curl fails.

### ISSUE THREAD

**Issue by bharathshetty4** [gliderlabs/docker-alpine#220]
Hi, 
While trying  to add **openssl** and **curl**, im getting this below error,

RUN apk add --no-cache --update     py-pip     python     py-lxml     git  && rm /var/cache/apk/*
 ---> Running in a016ed9232d4
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/23) Installing openssl (1.0.2i-r0)
ERROR: openssl-1.0.2i-r0: package mentioned in index not found (try 'apk update')
(2/23) Installing ca-certificates (20160104-r2)
(3/23) Installing libssh2 (1.6.0-r1)
(4/23) Installing curl (7.49.1-r1)
ERROR: curl-7.49.1-r1: package mentioned in index not found (try 'apk update')
(5/23) Installing expat (2.1.1-r1)

the problem here, the repo is directing to http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/ , where the openssl version is openssl-1.0.2j-r0, and here it is trying to download openssl-1.0.2i-r0.
I tried deleting the **/var/apk/cache** directory and **apk update** , still it was not working.

Any know solution is there for this error??

Thank you, 
Bharath

**Comment by andyshinn** [comment]
The correct version is available and working. The index is actually also cached and can appear outdated. Can you get to http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/openssl-1.0.2i-r0.apk? Are you using any sort of proxy? Can you confirm the base image is up to date?

```console
$ d images | grep alpine
alpine                           3.3                         6c2aa2137d97        6 days ago          4.805 MB
```
