### ISSUE TITLE
installing uWSGI with pip fails (macOS Sierra)

### ISSUE THREAD

**Issue by HocusPocus2015** [gliderlabs/docker-alpine#221]
I'm trying to install 2.0.14 on macOS Sierra using pip and the installation is failing with the following stack trace.  Have tried specifying GCC as the compiler as suggested in another thread but the installation still fails.  Thanks for your help.

**deprecate**

**Comment by andyshinn** [comment]
Was this meant for the docker-alpine issue tracker? Can you post more about how you are running this (what image, Docker commands, Docker version, etc.)?

**Comment by HocusPocus2015** [comment]
:facepalm: yes sorry @andyshinn I will close this.
