### ISSUE TITLE
How add 'novnc'

### ISSUE THREAD

**Issue by 0xor** [gliderlabs/docker-alpine#222]
I need firefox in docker. Trouble is with vnc in mac. Meybe novnc is a solution.
How creating a docker file with novnc  https://kanaka.github.io/noVNC/ and terminal.
I must compiling novnc form myself?

**Comment by andyshinn** [comment]
This doesn't seem like an Alpine question. A Google search reveals plenty of these already:

* https://github.com/paimpozhil/docker-novnc
* https://github.com/solarkennedy/wine-x11-novnc-docker
* https://github.com/fcwu/docker-ubuntu-vnc-desktop/tree/master/noVNC
* https://github.com/psharkey/docker/tree/master/novnc
