### ISSUE TITLE
Patch needed to protect against Dirty Cow

### ISSUE THREAD

**Issue by toby-griffiths** [gliderlabs/docker-alpine#225]
Just been reading up about the Dirty Cow vulnerability.  Looks like this image need updating to 3.4.5 to protect against this. Not sure how easy that is, but thought I'd throw it out there, in case anyone's able to update.

**Comment by andyshinn** [comment]
Isn't the vulnerability in the kernel? There is no kernel in the container. This is a host related matter if I am not mistaken.

**Comment by ncopa** [comment]
You are not mistaken. It is the docker host that needs patching. There is nothing for us to fix in the container.

**Comment by toby-griffiths** [comment]
@andyshinn @ncopa Thanks for the info :o)
