### ISSUE TITLE
Should builder script default to latest version?

### ISSUE THREAD

**Issue by HanSooloo** [gliderlabs/docker-alpine#226]
Current Alpine version is 3.4 (2016-11-06).  However builder is using 3.2.

Should the builder script always use the current version of the main package?

**Comment by andyshinn** [comment]
Technically, the builder script is built to use a specific version of `apk` to download and extract the packages which make up the root filesystem. It doesn't determine the contents of the target. But it may require a specific version of `apk` to make sure the flags passed by the script are still correct. If any of those flags change then the script needs to change.

So, no, the builder script doesn't necessarily need to always use the latest version of `apk` or the image. But it could be updated and then the builds run to make sure the image is still build fine.
