### ISSUE TITLE
how to generate docker images for latest updates

### ISSUE THREAD

**Issue by max-10001** [gliderlabs/docker-alpine#230]
I don't see any info on how to generate new docker images for versions like 3.4.6. I tried the build.sh script and it generates 3.1 to 3.4 however doesn't have any option to generate latest version. Any clues?

**Comment by andyshinn** [comment]
When you build a specific version (`./build versions/library-3.4/options`) it will build from the most recent 3.4 branch (https://git.alpinelinux.org/cgit/aports/log/?h=3.4-stable). Let me know if this isn't what you were looking for.
