### ISSUE TITLE
How do you get round the RubyGems SSL Issue with this?

### ISSUE THREAD

**Issue by jessejohnson** [gliderlabs/docker-alpine#232]
The issue was documented here https://gist.github.com/luislavena/f064211759ee0f806c88, but this assumes you're running a machine, rather than installing gems from a DockerFile

**Comment by treeder** [comment]
Haven't tried this on alpine, but you could probably do what it says here: http://guides.rubygems.org/ssl-certificate-update/ in the "INSTALLING USING UPDATE PACKAGES" section. Add those lines to your Dockerfile.

**Comment by andyshinn** [comment]
I wasn't able to reproduce this using:

```
FROM alpine:3.5
RUN apk add --no-cache ruby ruby-io-console ruby-dev build-base zlib-dev libxml2-dev
RUN gem install rails --no-document
RUN rails -v
```
If you can provide a simple `Dockerfile` for reproduction I will take a look. I am going to close this in the meantime.
