### ISSUE TITLE
images for 3.5 release

### ISSUE THREAD

**Issue by justincormack** [gliderlabs/docker-alpine#235]
Any chance of getting Docker images of 3.5-rc2 or 3? Other repos eg golang do early previews of docker images, and it would be really helpful. Currently I am upgrading from `3.4` but its kind of inconvenient.

cc @ncopa

**Comment by ncopa** [comment]
the 3.5 was just released. we also provide an alpine-minirootfs.tar.gz that could be used for creation of the image.

**Comment by pbregener** [comment]
Having a 3.5 image ASAP would be great. Who is able and going to take care of this?

**Comment by CpuID** [comment]
It seems https://github.com/gliderlabs/docker-alpine/pull/240 handles getting 3.5 support into this repo, but the image tag's are either not built, or not appearing on the [Docker Hub](https://hub.docker.com/r/library/alpine/) as yet...

**Comment by ipfans** [comment]
@CpuID This is why docker hub still not upgrade: image is updated via pull requests to the docker-library/official-images GitHub repo.

**Comment by ncopa** [comment]
this one needs to be merged: https://github.com/docker-library/official-images/pull/2489

**Comment by CpuID** [comment]
Aha, makes sense. Thx :)


Nathan Sullivan

**Comment by jbergstroem** [comment]
(you can close this now!)

**Comment by miketheman** [comment]
I still cannot see `gliderlabs/alpine:3.5` in tags on docker hub: https://hub.docker.com/r/gliderlabs/alpine/tags/ - any news on that?

**Comment by jbergstroem** [comment]
@miketheman just do `alpine:3.5`.

**Comment by miketheman** [comment]
@jbergstroem Thanks for the tip - I indeed tried that already. The gliderlabs version (which my stack is based upon) contains some differences (noted in http://gliderlabs.viewdocs.io/docker-alpine/build/ "Differences") that we currently use.

**Comment by jbergstroem** [comment]
@miketheman oh; I didn't know that. Apologies.

**Comment by justincormack** [comment]
I don't think there is any difference any more.

**Comment by miketheman** [comment]
@justincormack Here's what I get:
```
$ docker run -it --rm gliderlabs/alpine:3.4 ash
/ # apk-install
fetch http://alpine.gliderlabs.com/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://alpine.gliderlabs.com/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
OK: 5 MiB in 11 packages
$ docker run -it --rm alpine:3.5 ash
/ # apk-install
ash: apk-install: not found
```

**Comment by ncopa** [comment]
`apk-install` is a [wrapper script](https://github.com/gliderlabs/docker-alpine/blob/master/builder/scripts/apk-install) that only does `apk add --update "$@" && rm -rf /var/cache/apk/*`.

Since then `apk` got its own flag to do the same so you can now do: `apk add --no-cache ...`

**Comment by miketheman** [comment]
@ncopa Thanks for the update! That's great that apk now has a flag for it. Is the `gliderlabs/alpine` image now deprecated, i.e. will not receive updates? What about the Fastly-enabled packages distribution?

**Comment by justincormack** [comment]
The fastly mirror is the default for the official images now.

**Comment by andyshinn** [comment]
Closing as 3.5 has been released for some time now.
