### ISSUE TITLE
Alpine 3.4.6

### ISSUE THREAD

**Issue by pracucci** [gliderlabs/docker-alpine#238]
Hi there, I've read the [comment about the image versioning](https://github.com/gliderlabs/docker-alpine/issues/129#issuecomment-170984246) and it makes sense to me.

However, looking at the [Alpine 3.4.6 release notes](https://alpinelinux.org/posts/Alpine-3.4.6-released.html) there's a reference to `musl` but, as far as I can see, the Docker image has not been re-packaged after the release of Alpine 3.4.6.

Is there any specific reason?

**Comment by andyshinn** [comment]
I think somewhere in recent image bumps the 3.4 tag did get updated to 3.4.6:

```console
$ docker run alpine:3.4 cat /etc/os-release | grep VERSION_ID
VERSION_ID=3.4.6
```
