### ISSUE TITLE
no_proxy environment variable ignored by wget

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [gliderlabs/docker-alpine#259]
When I run the latest image of alpine with `sh`,
and I set
``` bash
export http_proxy=myproxy.mydomain:1234
```
and I set 
``` bash
$ export no_proxy=.test.local
```
and I run

``` bash
$ wget service.test.local
```

I see `Connecting to proxy ...`

I would have expected to not connect to the proxy.

Steps to reproduce when you're not sitting behind a proxy:
```bash
docker run --rm -it alpine sh
export http_proxy=foo.bar
export no_proxy=.com
wget google.com
```
The above should fail, as wget tries to connect to the (presumably) unresponsive proxy.

Do I have a fundamental misunderstanding regarding `wget` and / or `no_proxy`? Or is there something wrong with alpine / the wget alpine is using here?

**Comment by ncopa** [comment]
It is very possible that busybox wget does not support `no_proxy` env var. You can `apk add wget` to get the full featured GNU wget if you need it.

**Comment by lecogiteur** [comment]
It could be a good idea to manage the environment variable `no_proxy` in alpine.
