### ISSUE TITLE
503 error when getting APKINDEX

### ISSUE THREAD

**Issue by jsternberg** [gliderlabs/docker-alpine#264]
I'm receiving this message a lot today. Sometimes, trying again works, but I'm at a pretty low chance of success at the moment. Is the CDN functioning right now?

```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
```

**Comment by mattbailey** [comment]
having this issue too, ended up running it like this:

`until apk -Uuv add [packages]; do sleep 1; done`

In my docker image builds.

**Comment by lindycoder** [comment]
+1

makes my travis-ci docker test fail

Step 2 : RUN apk update
 ---> Running in 436bea56ec8c
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.167438ca.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.a2e6dac0.tar.gz: No such file or directory

**Comment by miketheman** [comment]
This might have been related, but the report above shows a BOS pop.
https://status.fastly.com/incidents/mwhmkmrt4c7k

Previous reports:
- #155 
- #164 
- #209
- #210

**Comment by lindycoder** [comment]
Everything seems resolved to me today, thank you

https://travis-ci.org/internap/fake-switches/jobs/211488963

**Comment by jsternberg** [comment]
It seems like things are working now. I'll reopen if I still see issues.
