### ISSUE TITLE
tty regression from 3.4 to 3.5

### ISSUE THREAD

**Issue by ryansch** [gliderlabs/docker-alpine#266]
3.4 works as expected:
```
docker run -it --rm alpine:3.4 sh                                                                                                                                              [ruby-2.3.3]
/ # tty
/1
```

3.5 fails:
```
docker run -it --rm alpine:3.5 sh                                                                                                                                              [ruby-2.3.3]
/ # tty
not a tty
```

**Comment by cevn** [comment]
Any workarounds for this?

**Comment by andyshinn** [comment]
I'm not sure what is going on here. I'll do some more research.

**Comment by geraldlai** [comment]
This could be related to [docker#8755](https://github.com/moby/moby/issues/8755).

**Comment by ryansch** [comment]
This is still present in `alpine:3.6`.

**Comment by evaryont** [comment]
Running tty in an alpine 3.6 container with docker 17.07, it returns succesfully - `/dev/pts/0`. I imagine that it's not due to Alpine or the image being updated with a fix, but rather docker itself fixing the bug @geraldlai pointed out.

**Comment by ryansch** [comment]
It seems that way.  I can't reproduce this on alpine 3.7 with docker 17.09.1-ce.
