### ISSUE TITLE
fuse usage ?

### ISSUE THREAD

**Issue by albundy83** [gliderlabs/docker-alpine#268]
Hello,
is it possible to use a fuse based command ?
It seems that the module is not loaded and can't be loaded (even with modprobe fuse).
Do you know how is it possible to do it ?

**Comment by albundy83** [comment]
Here what I have when I run command `modprobe fuse`

```
modprobe: can't change directory to '/lib/modules': No such file or directory
The command '/bin/sh -c modprobe fuse' returned a non-zero code: 1
```

**Comment by tianon** [comment]
I would recommend doing the modprobe on your host, then using "--device
/dev/fuse" to get the device in the container. You'll probably need a
"--cap-add" to actually mount things with it, though.

**Comment by albundy83** [comment]
Thanks a lot for your answer, I have used `--device
/dev/fuse` and `--privileged` .
I did not find the correct `--cap-add` to set :-)

**Comment by tianon** [comment]
Sorry for not being specific -- now that I'm at my computer, I think `SYS_ADMIN` is probably the one you need to make that work.  There might also be some seccomp filtering on the `mount` syscall, but I can't recall (so that might require a custom profile).

Glad you got it working! (and hopefully `--privileged` doesn't last too long -- that's pandora's box lol)

**Comment by albundy83** [comment]
So, just to finalize this issue, here my Dockerfile using [Golang goofys client ](https://github.com/kahing/goofys), a POSIX-ish Amazon S3 file system written in Go that allow you to mount S3 locally.

```dockerfile
FROM golang:1.7-alpine3.5

ENV aws_bucket GGGGGG
ENV aws_access_key_id XXXXXXXXXXXX
ENV aws_secret_access_key YYYYYYYYYYYYYYY

RUN mkdir /root/.aws/ \
    && echo -e "[default]\naws_access_key_id = ${aws_access_key_id}\naws_secret_access_key = ${aws_secret_access_key}" > /root/.aws/credentials \
    && chmod 700 /root/.aws \
    && chmod 600 /root/.aws/credentials

RUN apk update -U \
    && apk add --no-cache --virtual .build-deps git \
    && apk add fuse \
    && go get github.com/kahing/goofys \
    && go install github.com/kahing/goofys \
    && rm -rf /go/src \
    && apk del .build-deps \
    && mkdir /mnt/${aws_bucket}

CMD /go/bin/goofys -f ${aws_bucket} /mnt/${aws_bucket}
```
The command to run the docker image:
```bash
docker run --device /dev/fuse --privileged <image_id>
```

**Comment by andyshinn** [comment]
Closing as it sounds like this was solved outside the container. Let me know if otherwise.
