### ISSUE TITLE
Volume mounting folder is empty. 

### ISSUE THREAD

**Issue by laics1984** [gliderlabs/docker-alpine#272]
HI all, I am running the following command but the result is empty. May i know how to get the files shown in volume folder?

`$ docker run --rm -v /C/Users/David:/home/david alpine ls /home/david`

However, i can access in the vm via `docker-machine ssh`

Thanks.

Tools: WIndows 10, Docker Toolbox

**Comment by tianon** [comment]
Have you tried using `/c/` instead of `/C/`?  (I think the mount point is case sensitive)

**Comment by andyshinn** [comment]
Closing as this seems like a general Docker issue. Let us know if this is working in other containers but failing in only Alpine.
