### ISSUE TITLE
No alternatives Utility ?

### ISSUE THREAD

**Issue by dockletinc** [gliderlabs/docker-alpine#273]
My project work with java application. It required alternatives utility for configure java path.
But in the latest alpine version not provide this utility on system.
What should I do for fix this? 

Thank you

**Comment by andyshinn** [comment]
This is something provided by the package managers on other systems and isn't part of `apk-tools`. In `edge` there is a `dpkg` package that does contain it: https://pkgs.alpinelinux.org/contents?file=update-alternatives&path=&name=dpkg&branch=edge&repo=main&arch=x86. But in a container you might as well just set the paths manually. If you post an example of what you are trying to get working I can help with this.
