### ISSUE TITLE
/bin/sh: apk-install: not found when trying to add OpenSSL

### ISSUE THREAD

**Issue by IdanAdar** [gliderlabs/docker-alpine#274]
Using `FROM node:6.9.4-alpine` I am added the following in the Dockerfile: 

```
RUN apk-install openssl
```

This however fails with: 
> /bin/sh: apk-install: not found
> The command '/bin/sh -c apk-install openssl' returned a non-zero code: 127

How can I overcome this?

**Comment by IdanAdar** [comment]
Actually I think it should simply be: `RUN apk add --update openssl`

**Comment by andyshinn** [comment]
The `apk-install` script is now deprecated. Use `apk add --no-cache openssl` instead. Related to #18 and #269.

**Comment by IdanAdar** [comment]
Thanks @andyshinn. May I know the difference between the two?

**Comment by andyshinn** [comment]
They both accomplish the same thing. The `apk-install` script was a small thing we originally added to remove the cache before it was built in to `apk`. Now the `--no-cache` is supported from Alpine themselves so our script isn't required.
