### ISSUE TITLE
Deprecate 3.1 and 3.2 images?

### ISSUE THREAD

**Issue by yosifkit** [gliderlabs/docker-alpine#277]
v3.1 reached end of life on 2016-11-01.  [Last update 2016-12-26](https://git.alpinelinux.org/cgit/aports/log/?h=3.1-stable).
v3.2 reached end of life on 2017-05-01. I assume this means once 3.6 is released.  [Last update 2017-05-02](https://git.alpinelinux.org/cgit/aports/log/?h=3.2-stable).

\- https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases

**Comment by andyshinn** [comment]
What is involved in deprecation? Are you suggesting we add something to the images to signify they are now deprecated or just documentation somewhere?

**Comment by tianon** [comment]
He means removing them from https://github.com/docker-library/official-images/blob/master/library/alpine, and thus from the list of "Supported tags" on https://hub.docker.com/_/alpine/ :smile:

(Although the tags will remain pullable)

**Comment by andyshinn** [comment]
Oh. Yea, that seems fine. I'll add something to the `README.md` about it.

**Comment by yosifkit** [comment]
Closing old issue (has been fixed).
