### ISSUE TITLE
ERROR: libuuid-2.28.2-r1: BAD signature

### ISSUE THREAD

**Issue by chinkung** [gliderlabs/docker-alpine#278]
There is an error when I try to install package from gliderlabs/alpine:edge

fetch http://alpine.gliderlabs.com/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://alpine.gliderlabs.com/alpine/edge/community/x86_64/APKINDEX.tar.gz
.
.
.
(27/51) Installing libuuid (2.28.2-r1)
**ERROR: libuuid-2.28.2-r1: BAD signature**

Could you please check ?

**Comment by hellfosa** [comment]
[root@docker]# docker run -it  alpine:edge sh
/ # /sbin/apk update
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
v3.5.0-4813-g5fafd50b76 [http://dl-cdn.alpinelinux.org/alpine/edge/main]
v3.5.0-4811-gcd1c97f6c9 [http://dl-cdn.alpinelinux.org/alpine/edge/community]
OK: 8385 distinct packages available
/ # /sbin/apk add libuuid
(1/1) Installing libuuid (2.28.2-r1)
ERROR: libuuid-2.28.2-r1: BAD signature
1 errors; 4 MiB in 11 packages

please fix it :)

**Comment by chinkung** [comment]
Add this package from alpine:3.5 can fix the problem
# apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.5/main/ libuuid

**Comment by hellfosa** [comment]
/ # apk update
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
v3.5.0-4813-g5fafd50b76 [http://dl-cdn.alpinelinux.org/alpine/edge/main]
v3.5.0-4811-gcd1c97f6c9 [http://dl-cdn.alpinelinux.org/alpine/edge/community]
OK: 8385 distinct packages available
/ # apk add mc
(1/12) Installing libffi (3.2.1-r3)
(2/12) Installing libintl (0.19.8.1-r1)
(3/12) Installing libuuid (2.28.2-r1)
**ERROR: libuuid-2.28.2-r1: BAD signature**
(4/12) Installing libblkid (2.28.2-r1)
**ERROR: libblkid-2.28.2-r1: BAD signature**
(5/12) Installing libmount (2.28.2-r1)
**ERROR: libmount-2.28.2-r1: BAD signature**
(6/12) Installing pcre (8.40-r2)
(7/12) Installing glib (2.52.1-r0)
(8/12) Installing ncurses-terminfo-base (6.0-r7)
(9/12) Installing ncurses-terminfo (6.0-r7)
(10/12) Installing ncurses-libs (6.0-r7)
(11/12) Installing libssh2 (1.8.0-r1)
(12/12) Installing mc (4.8.19-r0)
Executing busybox-1.26.2-r2.trigger
Executing glib-2.52.1-r0.trigger
3 errors; 17 MiB in 20 packages
/ #

**Comment by andyshinn** [comment]
I purged this file from the CDN so it will get re-cached. This usually happens when a bad package gets built and pulled on the CDN before it gets noticed and rebuilt. Let me know if it is still an issue.

**Comment by andyshinn** [comment]
I tracked this down to http://patchwork.alpinelinux.org/patch/3374/. It seems this was merged without the package revision being bumped.

Ping @ncopa just FYI. Not sure if this is standard procedure. I would expect the patchwork to be closed if it passed review and not merged beforehand.

**Comment by ncopa** [comment]
it was me who didn't pay enough attention. Sorry. It should be fixed now though.
