### ISSUE TITLE
Repositories are not updated to HTTPS

### ISSUE THREAD

**Issue by fjfc** [gliderlabs/docker-alpine#281]
Excuse my English.

In version 3.5 (latest), I have detected a failure in the repositories, alpine has modified its repositories to "HTTPS" and now the official repositories of the image do not work.
To solve it, you only have to add "s" as fix in the repository, but it would be grateful for a solution during the update of the repository.
Thanks for your attention.

**Comment by ncopa** [comment]
What is the exact error message you get? http repositories works fine for me.

**Comment by fjfc** [comment]
The problem is internal, the proxy server is cutting the connections.
I close the issue sorry for the inconvenience.
