### ISSUE TITLE
ERROR: http://dl-4.alpinelinux.org/alpine/v3.5/main: IO ERROR

### ISSUE THREAD

**Issue by CiscoY** [gliderlabs/docker-alpine#283]
when I run `apk update`, the following error messages will be showed.

```
fetch http://dl-4.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-4.alpinelinux.org/alpine/v3.5/main: IO ERROR
fetch http://dl-4.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-4.alpinelinux.org/alpine/v3.5/community: IO ERROR
v3.5.2-73-g3e58d6940f [http://dl-4.alpinelinux.org/alpine/v3.5/main]
v3.5.2-70-gec9876f375 [http://dl-4.alpinelinux.org/alpine/v3.5/community]
2 errors; 7961 distinct packages available
```
And network of my docker need proxy. And when I run `wget http://dl-4.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz`, I will get this package successfully.

**Comment by andyshinn** [comment]
We had recent issues with dl-4 mirror. Have you tried another one?

**Comment by CiscoY** [comment]
Thanks. I have resolved it by setting proxy.

2017-05-24 2:05 GMT+08:00 Andy Shinn <notifications@github.com>:
