### ISSUE TITLE
Alpine 3.6.0 got released today - when should we expect it here?

### ISSUE THREAD

**Issue by nikolay** [gliderlabs/docker-alpine#284]

**Comment by nikolay** [comment]
A PR is waiting... just like we all are! https://github.com/gliderlabs/docker-alpine/pull/285

**Comment by pbregener** [comment]
That PR was already merged some hours ago. Now we're just waiting for https://github.com/docker-library/official-images/pull/2984 to be merged.

**Comment by NicolasCARPi** [comment]
![wednesday](https://cloud.githubusercontent.com/assets/3043706/26472592/22708840-41a7-11e7-805b-a7f0398c16a0.gif)

**Comment by ashleysommer** [comment]
https://github.com/docker-library/official-images/pull/2984 merged :trumpet: :tada:

**Comment by nikolay** [comment]
It's published to Docker Hub already. Thank you!
