### ISSUE TITLE
Warning 4.9 in Docker Bench Security Suite

### ISSUE THREAD

**Issue by mariusfilipowski** [gliderlabs/docker-alpine#287]
When we use a docker-alpine image and run https://github.com/docker/docker-bench-security, then we get the following warning for our docker images.

[INFO] 4.9  - Use COPY instead of ADD in Dockerfile

This is due to the fact that in alpine ADD is used. Is this okay or are  you going to change this to the best practices sometimes soon?

Thanks for your small and handy docker image.

**Comment by tianon** [comment]
This image is one of the few cases where ADD is not only preferred, it's
required.  We're copying the contents of a tarball into an otherwise empty
image, which requires ADD's additional extraction behavior that COPY does
not have.

**Comment by andyshinn** [comment]
Wouldn't this warning come up for any image? IIRC, other popular base images also build by `ADD`ing tarballs as the base.

**Comment by tianon** [comment]
Indeed -- all official base images use `ADD` for copying their tarballs.

**Comment by mariusfilipowski** [comment]
Okay. Thanks for the quick response. 

In https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.13.0_Benchmark_v1.0.0.pdf you'll find the risk involved.. under 4.9 / Page 120/121

> Rationale:
> COPY instruction just copies the files from the local host machine to the container file
> system. ADD instruction potentially could retrieve files from remote URLs and perform
> operations such as unpacking. Thus, ADD instruction introduces risks such as adding
> malicious files from URLs without scanning and unpacking procedure vulnerabilities

**Comment by andyshinn** [comment]
I guess that makes sense. But seems like it might be better limited to `ADD` instructions that explicitly use a URL. We're just `ADD`ing local tarballs so they are automatically extracted into the resulting image. It doesn't seem like any added risk to me.

Also, this warning is going to show up for pretty much any image since, as previously pointed out, nearly all official base images `ADD` the tarball for the base.
