### ISSUE TITLE
equivalent repos from ubuntu in alpine

### ISSUE THREAD

**Issue by javixeneize** [gliderlabs/docker-alpine#295]
Hi

I have an ubuntu image that is kind of a monster (1.4gb) and i need to reduce it a bit

However, i need to install some python dependencies, and oracle java as well

RUN apt-get install -y python-pip python-dev build-essential libssl-dev libffi-dev
RUN apt-get install -y software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
    apt-get clean

What would be the equivalent to this in alpine? 

Thanks

**Comment by andyshinn** [comment]
Oracle Java will be a blocker if you cannot run on OpenJDK. There is no Oracle Java in Alpine.

**Comment by javixeneize** [comment]
Fck

Any chances of including this in a future alpine release ?

Thanks

**Comment by andyshinn** [comment]
That is up to Oracle, not Alpine. Oracle needs to support the musl libc library instead of just glibc.

**Comment by ncopa** [comment]
Oracle is working on [official support](https://blogs.oracle.com/developers/official-docker-image-for-oracle-java-and-the-openjdk-roadmap-for-containers) for Alpine Linux (and musl libc). You can test the JDK 9 Early-Access build for Alpine: http://jdk.java.net/9/
