### ISSUE TITLE
python cffi problems with 3.5 & 3.6

### ISSUE THREAD

**Issue by NathanZook** [gliderlabs/docker-alpine#296]
Trying to build the docker image from https://github.com/samsung-cnct/k2-tools/tree/e0f97d7c79095065a5634595efe962f7d46a1b1f.  This is working for 3.4, but not 3.5 or  3.6.

The interesting part of the output is 

    Package 'libffi', required by 'virtual:world', not found
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/cffi
...

    building '_cffi_backend' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/c
    gcc -fno-strict-aliasing -Os -fomit-frame-pointer -g -DNDEBUG -Os -fomit-frame-pointer -g -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>

CFFI is a python package to interface with C code.

**Comment by NathanZook** [comment]
`apk add libcffi-dev openssl-dev` was what I needed to add (to what I already had) to get `pip install cffi` to run.  Thanks to savant on the slack channel for the help!

**Comment by jingweicao** [comment]
@NathanZook you solved my problem!
