### ISSUE TITLE
Alpine available for arm32v6 and not for arm32v7, why ?

### ISSUE THREAD

**Issue by seblucas** [gliderlabs/docker-alpine#298]
Hi,

I used to use https://hub.docker.com/r/armhf/alpine/ and was happy about it, lately I saw that you started to follow another rule armhf -> arm32v6 / arm32v7. Alpine is available for [arm32v6](https://hub.docker.com/r/arm32v6/alpine/) (for the first raspberry pi) but I can't find anything in for [arm32v7](https://hub.docker.com/u/arm32v7/) (for Raspberry PI 2, Allwinner A10, A20, H3).

Is there a reason why ?

**Comment by tianon** [comment]
The issue that caused the rename is that `armhf` is ambiguous -- in Debian, it refers to ARMv7, but in Alpine and Raspbian, it's ARMv6.

Alpine is only available for ARMv6, but ARMv6 binaries should be compatible with an ARMv7 chip (which is likely the reason Alpine upstream has chosen to only support ARMv6).

At some point in the (hopefully near) future, these details will be abstracted somewhat by manifest lists (https://github.com/docker-library/official-images/issues/2289) such that `alpine:3.6` will pull the correct contents for the target architecture.

**Comment by seblucas** [comment]
Thanks a lot for your answer, I really didn't know that armhf meant ARMV6 for Alpine ..... 

I was blaming Docker for some speed difference between nzbget in a container / compiled in host (Allwinner H3 so ARMv7) but that may be ARMv6 / ARMv7 difference.

I guess I'm disappointed by Alpine (supporting only ARMv6 and naming it armHF = Hard Float ....).

Anyway thanks for your answer. I'll close this issue.
