### ISSUE TITLE
node:6.9.4-alpine - zlib vulnerability

### ISSUE THREAD

**Issue by IdanAdar** [gliderlabs/docker-alpine#299]
Hello,
In my Dockerfile I use `FROM node:6.9.4-alpine`.

IBM Bluemix provides a Vulnerability Advisor feature that can scan images and provide a report.
I was notified of the following:

<pre>
PACKAGE   SUMMARY                                                                                                                                                                          URL   
zlib      inftrees.c in zlib 1.2.8 might allow context-dependent attackers to have unspecified impact by leveraging improper pointer arithmetic.                                              
          inffast.c in zlib 1.2.8 might allow context-dependent attackers to have unspecified impact by leveraging improper pointer arithmetic.                                               
          The inflateMark function in inflate.c in zlib 1.2.8 might allow context-dependent attackers to have unspecified impact via vectors involving left shifts of negative integers.      
          The crc32_big function in crc32.c in zlib 1.2.8 might allow context-dependent attackers to have unspecified impact via vectors involving big-endian CRC calculation.  
</pre>

How can I address this, given that I must stay with `node:6.9.4`?
Was the base image patched with a fix for this?

Thanks,

**Comment by IdanAdar** [comment]
Is using `FROM node:6-alpine` a better approach? Will it provide, at minimum, 6.9.4 or a different version?

**Comment by andyshinn** [comment]
This may be a better question for https://github.com/nodejs/docker-node/issues. The node package isn't from the Alpine package index. It is actually built from upstream: https://github.com/nodejs/docker-node/blob/master/6.11/alpine/Dockerfile

**Comment by IdanAdar** [comment]
Will continue this in the node issue.
