### ISSUE TITLE
npm install node-expat

### ISSUE THREAD

**Issue by dynnamitt** [gliderlabs/docker-alpine#3]
Even after

apk-install nodejs python gcc make

npm install node-expat 

==> not a success

**Comment by dynnamitt** [comment]
apk-install nodejs python make gcc g++ libc-dev

is the fix for such a "heavy native" case

**Comment by dynnamitt** [comment]
168mb for a serious nodejs env

**Comment by andyshinn** [comment]
Usually in these cases, I try to find a separation of the required libs and build dependencies, and remove them in the same layer. Something like this:

```
FROM gliderlabs/alpine
RUN apk-install nodejs libgcc libstdc++
RUN apk-install -t build-deps build-base python \
  && npm install node-expat \
  && apk del --purge build-deps
```

This will install the build dependencies under a virtual package named `build-deps` which can then be removed in the same layer.

**Comment by dynnamitt** [comment]
hmm yes.. only prob is that alpine-repo if FAR slower than docker hub .. and Im better off just keeping build-deps at that location....

**Comment by progrium** [comment]
@andyshinn Maybe we can set up an CDN backed mirror of the alpine-repo

On Mon, Feb 16, 2015 at 7:29 AM, Kjetil Flovild-Midtlie <
notifications@github.com> wrote:

> hmm yes.. only prob is that alpine-repo if FAR slower than docker hub ..
> and Im better off just keeping build-deps at that location....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/docker-alpine/issues/3#issuecomment-74508087>
> .
>



-- 
Jeff Lindsay
http://progrium.com
