### ISSUE TITLE
installing openssl-dev and openldap-dev in alpine:3.6 not possible  due to unsatisfiable contstraints

### ISSUE THREAD

**Issue by sebastianhutter** [gliderlabs/docker-alpine#303]
Installation of openssl-dev and openldap-dev in alpine:3.6 and alpine:3.5 is not possible due to unsatisfiable contstraints:

```
# docker run --rm -ti alpine:3.6 apk add --no-cache openssl-dev openldap-dev
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  libressl-dev-2.5.4-r0:
    conflicts: openssl-dev-1.0.2k-r0[pc:libcrypto=2.5.4] openssl-dev-1.0.2k-r0[pc:libssl=2.5.4] openssl-dev-1.0.2k-r0[pc:openssl=2.5.4]
    satisfies: openldap-dev-2.4.44-r5[libressl-dev]
  openssl-dev-1.0.2k-r0:
    conflicts: libressl-dev-2.5.4-r0[pc:libcrypto=1.0.2k] libressl-dev-2.5.4-r0[pc:libssl=1.0.2k] libressl-dev-2.5.4-r0[pc:openssl=1.0.2k]
    satisfies: world[openssl-dev]
```

this works in alpine:3.4:
```
# docker run --rm -ti alpine:3.4 apk add --no-cache openssl-dev openldap-dev
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/15) Installing pkgconf (0.9.12-r0)
(2/15) Installing pkgconfig (0.25-r1)
(3/15) Installing zlib-dev (1.2.11-r0)
(4/15) Installing openssl-dev (1.0.2k-r0)
(5/15) Installing db (5.3.28-r0)
(6/15) Installing libsasl (2.1.26-r7)
(7/15) Installing cyrus-sasl-dev (2.1.26-r7)
(8/15) Installing libuuid (2.28-r3)
(9/15) Installing libblkid (2.28-r3)
(10/15) Installing libfdisk (2.28-r3)
(11/15) Installing libmount (2.28-r3)
(12/15) Installing libsmartcols (2.28-r3)
(13/15) Installing util-linux-dev (2.28-r3)
(14/15) Installing libldap (2.4.44-r2)
(15/15) Installing openldap-dev (2.4.44-r2)
Executing busybox-1.24.2-r13.trigger
OK: 19 MiB in 26 packages
```

I assume some dependencies in the APK repository are off. Any ideas to circumvent this issue?

**Comment by andyshinn** [comment]
This sounds like `openldap` is built against `libressl` instead of `openssl` in 3.6. You cannot install both `openssl-dev` and `libressl-dev` in 3.6. What are you needing `openssl-dev` for? Depending on what you are building, `libressl-dev` may be able to replace `openssl-dev`.

**Comment by sebastianhutter** [comment]
i need compile nginx from source with ssl and ldap.
libressl-dev did the trick. thanks a lot for pointing this out!

**Comment by juliengk** [comment]
I do have the same problem. And libressl-dev does not do the trick :(

**Comment by sebastianhutter** [comment]
@juliengk what are you trying to build which causes trouble? can you post your dockerfile / commands?

**Comment by juliengk** [comment]
I have tried again to replace openssl-dev with libressl-dev and that worked. When building the docker image, some python packages are installed and so was complaining about the missing lib. I have updated the version of the python packages and all is good now.

Thanks and sorry for disturbing for nothing
