### ISSUE TITLE
Need docker image for alpine 3.6.2

### ISSUE THREAD

**Issue by jmellor** [gliderlabs/docker-alpine#309]
Alpine 3.6.1 and 3.6.2 fix multiple security issues.  There is no docker image for these releases.
Please package.

**Comment by tianon** [comment]
This is already the case, isn't it?

```console
$ docker pull alpine:3.6
3.6: Pulling from library/alpine
Digest: sha256:1072e499f3f655a032e88542330cf75b02e7bdf673278f701d7ba61629ee3ebe
Status: Image is up to date for alpine:3.6

$ docker run --rm alpine:3.6 cat /etc/alpine-release
3.6.2
```

**Comment by andyshinn** [comment]
It was: https://github.com/gliderlabs/docker-alpine/commit/6f100102f7ca265f6b5546b28f0376c9bd7ada45.

**Comment by jmellor** [comment]
On Tue, 2017-07-18 at 08:07 -0700, Tianon Gravi wrote:

This is already the case, isn't it?

Are you saying that you are magically re-releasing Alpine docker images and overwriting the existing release?

If so, this means that we need to check for hash changes every few days and rebuild all product based on that image every time it changes.

This is broken. An update of the docker image implies a mandatory version number change.
In this case the new docker image should be called 3.6.2 or 3.6.2.1 or similar instead of 3.6, in order to avoid this kind of nighmare for downstream image users.

**Comment by andyshinn** [comment]
Yes. I believe most of the official images overwrite tags as well. This is a larger question for https://github.com/docker-library/official-images/. Also, see https://github.com/gliderlabs/docker-alpine/issues/129#issuecomment-170984246 as for the original reason why it is difficult to tag patch levels (3.6.x).
