### ISSUE TITLE
Timezone setup doesn't work like described in alpine wiki

### ISSUE THREAD

**Issue by TristanCP** [gliderlabs/docker-alpine#310]
If you follow these steps on your Docker alpine image : 
https://wiki.alpinelinux.org/wiki/Setting_the_timezone
it won't setup timezone on your image, because you've setup a "TZ" env var to UTC somewhere.

This wiki setting works on Docker alpine official image (for x86_64 arch) : https://hub.docker.com/_/alpine/

The only way to setup timezone to Europe/Paris for example, on your image is to keep tzdata installed after setup (not like described in the wiki) and to setup a new TZ env var to "Europe/Paris" (again not like described in the wiki).

**Comment by andyshinn** [comment]
I don't think the wiki article applies to this image. Adding tzdata to set `/etc/localtime` to the correct file and the `TZ` environment variable is correct. Would this be make more sense if it was documented somewhere like gliderlabs.viewdocs.io/docker-alpine/ or https://hub.docker.com/_/alpine/?

**Comment by TristanCP** [comment]
Just to be more clear, the point is : 
This wiki setting works on Docker alpine official image (for x86_64 arch) : https://hub.docker.com/_/alpine/, so https://hub.docker.com/_/alpine/ doesn't need any complementary doc.

gliderlabs.viewdocs.io/docker-alpine/ is not having the same behaviour as https://hub.docker.com/_/alpine/. For a mysterious reason, TZ is set (it's NOT set in https://hub.docker.com/_/alpine/ )

**Comment by andyshinn** [comment]
Hmm, can you give an example? They are both UTC for me with no `TZ`:

```console
$ dri gliderlabs/alpine sh -c "env; date"
no_proxy=*.local, 169.254/16
HOSTNAME=3cfcc4117537
SHLVL=1
HOME=/root
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
Wed Jul 19 18:58:49 UTC 2017
$ dri alpine sh -c "env; date" 
no_proxy=*.local, 169.254/16
HOSTNAME=570d6a5d659b
SHLVL=1
HOME=/root
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
Wed Jul 19 18:58:57 UTC 2017
```

**Comment by TristanCP** [comment]
Sure, TZ appears in "docker inspect", in the env section. It appears in gilderslabs/alpine (same as arm32v6/alpine right ?) and not in alpine.

$ docker inspect arm32v6/alpine:3.6
```
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "TZ=UTC"
            ],
```
$ docker inspect alpine:3.6
```
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
```

**Comment by tianon** [comment]
That's a quirk particular to the current hacky multiarch Alpine images;
I'll look at adjusting that to use tzdata instead.

**Comment by TristanCP** [comment]
Hi Tianon, your name is familiar in Docker forums, you want to adjust that on arm32v6/alpine, not on regular alpine right ?

What do you mean by "adjusting that to use tzdata instead" ? Don't you think you can just not set TZ which would make all alpine images the same and respecting the alpine doc ?

**Comment by tianon** [comment]
Yes, `arm32v6/alpine` is currently using `ENV TZ UTC` because otherwise, Alpine defaults to GMT.  This repository uses a temporary install of `tzdata` in order to create an appropriate `/etc/localtime` file which overrides that default instead, which is what I need to do in the temporary `ARCH/alpine` images as well (until #304 is resolved).

**Comment by tianon** [comment]
The `ARCH/alpine` images should now be updated with the fix.

**Comment by TristanCP** [comment]
It's all good to me, TZ appears no more in $ docker inspect arm32v6/alpine:3.6

            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "TZ=UTC"
            ],
