### ISSUE TITLE
/etc/profile.d/color_prompt not read by /etc/profile

### ISSUE THREAD

**Issue by brenuart** [gliderlabs/docker-alpine#316]
`/etc/profile` reads and executes scripts matching the pattern `/etc/profile.d/*.sh`
The script `/etc/profile.d/color_prompt` does not end with `.sh` and as such won't be taken into account by the profile script.

**Comment by andyshinn** [comment]
See http://bugs.alpinelinux.org/issues/6933. At the top of the file is explains to rename it to enable it (it is disabled by default). I would comment on the upstream bug if you feel this behavior should be changed.
