### ISSUE TITLE
libpng-1.6.29-r1 (edge): BAD signature

### ISSUE THREAD

**Issue by doug-numetric** [gliderlabs/docker-alpine#318]
seems to have recently expired??

FROM alpine:edge

RUN apk add --update ttf-freefont

==== during docker build ===
(39/112) Installing libpng (1.6.29-r1)
ERROR: libpng-1.6.29-r1: BAD signature

=== docker exec -it <container> sh ===
apk verify /usr/lib/libpng16.so.16.29.0
/usr/lib/libpng16.so.16.29.0: -5 - UNTRUSTED

**Comment by andyshinn** [comment]
Looks related to a revert: https://git.alpinelinux.org/cgit/aports/commit/?id=9fec3a11c2d9c569da695e1a1055d67325215ae0. The package with same version was rebuilt when it was already cached on the CDN. I purged it so the new file will be cached. Should be fixed.
