### ISSUE TITLE
Add debugging tools in alpine image

### ISSUE THREAD

**Issue by duyanghao** [gliderlabs/docker-alpine#336]
At present, there are few tools in `alpine` image that we can use for debug, and the internal base tools like `ps`  and `top` could do little.

For instance, i want to list all threads of a process,which is pretty meaningful in base debug,but it becomes hard to achieve it as `top -Hp pid` and `ps -Lfp pid` are invalid in `alpine` image.

So i guess we could add more powerful base tools(such as enhanced `ps` and `top`) in `alpine` image for base debug.

#173 has given the answer for `ps -Lfp pid` but what about the `top -Hp pid` and other basical monitor tools such as `strace` and `perf`, etc.

Addition:
`alpine-release`: 3.5.2

What i want is a common set of debug service infrastructure in `alpine` image.

**Comment by ncopa** [comment]
I see no point in adding those to the base image itself, because different users will have different needs, and many users have no need for those debugging tools at all.

So I think its better that people who needs them adds them to their own images. Use `apk add --no-cache procps strace` for the extended `top`, `ps` and `strace` utils.

The `perf` util is still missing though. See http://bugs.alpinelinux.org/issues/7178

**Comment by duyanghao** [comment]
@ncopa  Use `apk add --no-cache procps strace` can only work for the extended `ps` and `strace` utils while `top -Hp` is still invalid.

**Comment by thaJeztah** [comment]
Note that for debugging you can also run a debug-container in the same namespace as the container you want to debug; doing so allows you to debug processes and networking in another container without modifying it, e.g.

```bash
docker run -it --rm --pid container:<other-container> --network container:<other-container> mydebugimage
```

**Comment by duyanghao** [comment]
@thaJeztah @ncopa What i want is to install base debug tools in `alpine` image, that is fundamental for all applications.
I do think it's necessary and important.

Anyway I will close this issue if you guys all object to the proposal.
But as for me, i will do that for my debug usage.

**Comment by andyshinn** [comment]
Going to close this out. The base image is designed to be as minimal as possible. For this reason we won't be adding any additional tools to it.

**Comment by EvilFreelancer** [comment]
Hello from 2018, additinal tools (like ps and top) was added into default image ;)

**Comment by bsergean** [comment]
@EvilFreelancer those ps and top are very likely the ones from busybox, which had always been in the default image.
