### ISSUE TITLE
Is it time to use official alpine or gliderlabs/alpine is not deprecated?

### ISSUE THREAD

**Issue by develar** [gliderlabs/docker-alpine#34]
As far I understand, official alpine https://registry.hub.docker.com/_/alpine/ is gliderlabs. Right? if so, maybe it worth to mention about it in the readme?

**Comment by mhart** [comment]
Yeah – would love to see a bit of guidance as to the difference between the library/gliderlabs images and which one y'all would prefer people be using in the wild.

**Comment by MattAitchison** [comment]
The `_/alpine` image is from gliderlabs and has does not include `apk-install`. Issue #19 should explain this and gives some information about the build process.

I will let @andyshinn or @progrium reply about your last question. (deprecation of `gliderlabs/alpine`)

**Comment by progrium** [comment]
I've been using `_/alpine` more and more. I think ultimately both will always be available, but the goal is to make them the same as much as possible. 

If for some reason we come up with something clever that we think is worth adding here and not as another image, we can add to `gliderlabs/alpine` or a tag. The official image is stricter about what it can include. 

Some docs would definitely help clear that up.

**Comment by mustela** [comment]
:+1: to have some clarification about what image to use.

**Comment by andyshinn** [comment]
I added some docs to make some more sense of this in #65.
