### ISSUE TITLE
cdn apk packages version

### ISSUE THREAD

**Issue by mablo** [gliderlabs/docker-alpine#340]
In web repository (pkgs.alpinelinux.org) and dl-3 repo (http://dl-3.alpinelinux.org/alpine/v3.6/community) there is php7 (v3.6, x86_64) in version 7.1.9, but in dl-cdn repo (http://dl-cdn.alpinelinux.org/alpine/v3.6/community) only 7.1.5.

**Comment by andyshinn** [comment]
This was because the index listing was actually cached as well. The package is actually there and would be downloaded when hit.

I've updated the CDN to only include "\.apk$" in the caching so directory listing, MIRRORS.txt, and other ancillary files are no longer cached.
