### ISSUE TITLE
Alpine's Compiling resources don't accept the '__always_inline' attribute in the C programming language.

### ISSUE THREAD

**Issue by mluis** [gliderlabs/docker-alpine#343]
I believe this should be solved soon since many projects based on this attribute are failing to build.

Please refer to [libosmocore](https://github.com/osmocom/libosmocore/pull/5)

**Comment by andyshinn** [comment]
`__always_inline` appears to be a private glibc method. This isn't something likely to get added to musl libc. It looks like you've already opened an issue upstream with the software to see if they can work around using `__always_inline`. That is the right approach to this problem unfortunately, it isn't something we can fix.
