### ISSUE TITLE
sh: cpan: not found

### ISSUE THREAD

**Issue by useltmann** [gliderlabs/docker-alpine#345]
Yesterday it still worked, today its gone

I use the docker-image **library/alpine:latest** but it hasn't changed in 4 weeks.
Inside the container i do 
```bash
apk add --no-cache --update lighttpd awstats openssh-client rsync coreutils make
```
which provided me with a `cpan` executable, but now its gone. explicitly installing *perl* does not give me *cpan* either. 

Please help.

**Comment by andyshinn** [comment]
`cpan` is provided by the `perl-utils` package. See https://pkgs.alpinelinux.org/contents?file=cpan&path=&name=&branch=v3.6&repo=&arch=.

**Comment by tianon** [comment]
It's probably also prudent to switch from "alpine:latest" over to something
more specific ilke "alpine:3.6" so you don't have another similar surprise
in a few months when Alpine 3.7 is released. 😇

**Comment by useltmann** [comment]
thanks for the help :+1:
