### ISSUE TITLE
Support for glibc (primarily for Oracle Java 8)?

### ISSUE THREAD

**Issue by aguedeney** [gliderlabs/docker-alpine#36]
It looks like Java 8 can not run with latest version of Alpine due to lack of glibc implementation.  I believe there are many applications that use this library.

**Comment by mgood** [comment]
Please see issue #11 which has information on Java and the glibc issue. There's information there about installing glibc as well which may be useful.

**Comment by aguedeney** [comment]
Yup, I'm using this article to get this working for now.  I just wanted to
put a placeholder issue so that the glibc package becomes an official
package in the "apk" repository at some point (I didn't see it in the apk
package repository). The aforementioned link is great for now.  Thank you
for the reply and reference.

**Comment by andyshinn** [comment]
@aguedeney can we just track this in #11? I'll update that issue with more glibc package information when there is more progress. Let me know if this issue was for something else.

**Comment by aguedeney** [comment]
Thanks Andy! Sure we can make this issue a duplicate as long as the goal is
to get glibc package into APK repository so that we can get updates from
APK update command.

**Comment by andyshinn** [comment]
It's not too likely to happen in the official Alpine repository. But yes, the goal would be to make it as easy as possible to install using `apk`.
