### ISSUE TITLE
"apk --update add font-config ttf-dejavu" yelds "ERROR: unsatisfiable constraints"

### ISSUE THREAD

**Issue by skarpushin** [gliderlabs/docker-alpine#360]
HI, that's what I do:

dockerfile:
```
FROM tomcat:8.0.47-jre8-alpine
RUN apk --update add font-config ttf-dejavu

```
and then I get an error:
```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  font-config (missing):
    required by: world[font-config]
The command '/bin/sh -c apk --update add font-config ttf-dejavu' returned a non-zero code: 1
```

Any ides on how to fix that?

**Comment by liyuankui** [comment]
it's `fontconfig`, without dash

**Comment by skarpushin** [comment]
@liyuankui , thank you, that worked!
`RUN apk --update add fontconfig ttf-dejavu`

**Comment by AvinashM7** [comment]
RUN apk --update add fontconfig && 	apk --update add fonts-dejavu-core

 ---> Running in 8f230e11ce51
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/6) Installing expat (2.2.8-r0)
(2/6) Installing libbz2 (1.0.6-r7)
(3/6) Installing libpng (1.6.37-r1)
(4/6) Installing freetype (2.10.0-r0)
(5/6) Installing libuuid (2.33.2-r0)
(6/6) Installing fontconfig (2.13.1-r0)
Executing busybox-1.30.1-r2.trigger
OK: 23 MiB in 34 packages
[91mERROR: unsatisfiable constraints:
[0m
  fonts-dejavu-core (missing):
    required by: world[fonts-dejavu-core]

Can someone help me out
