### ISSUE TITLE
Configure (autoconf) hangs on Alpine 3.7

### ISSUE THREAD

**Issue by tyranron** [gliderlabs/docker-alpine#362]
All builds on `alpine:3.7` which run `./configure` command hang on line:
```
checking that generated files are newer than configure... 
```

Examples: [Pure-FTPd](https://travis-ci.org/instrumentisto/pure-ftpd-docker-image/builds/310436931#L840), [OpenDKIM](https://travis-ci.org/instrumentisto/opendkim-docker-image/jobs/310437324#L713), [OpenDMARC](https://travis-ci.org/instrumentisto/opendmarc-docker-image/jobs/310436041#L659), [Nmap](https://travis-ci.org/instrumentisto/nmap-docker-image/builds/310438849#L951).

At the same time on `alpine:3.6` everything is OK: [Pure-FTPd](https://travis-ci.org/instrumentisto/pure-ftpd-docker-image/builds/294755128#L877).

I've examined changes in `autoconf` Alpine package between `3.6` and `3.7`, and haven't seen anything which could lead to this. I suppose this is something musl related.

**Comment by jumanjiman** [comment]
See also https://bugs.alpinelinux.org/issues/8235

**Comment by borisovg** [comment]
I have the same issue trying to compile shellinabox in Docker (17.06.0-ce)

**Comment by heftig** [comment]
Configure hangs when it's trying to wait for its sleep job. `(:)& wait %1` is similar code which also hangs.

You can work around this by setting `CONFIG_SHELL=/bin/sh`, but having a broken bash around sounds like it would invite more problems later.

**Comment by jumanjiman** [comment]
Bizarrely, this issue does not occur on https://labs.play-with-docker.com/

See https://github.com/gliderlabs/docker-alpine/issues/363#issuecomment-349738370

**Comment by andyshinn** [comment]
Was this the same as #363? It may be fixed by `bash-4.4.12-r2`. Please try to re-run those builds.

**Comment by borisovg** [comment]
Works for me now :)

**Comment by tyranron** [comment]
@andyshinn I confirm that issue is fixed now.

**Comment by pvizeli** [comment]
The Bug is not solved for aarch64, armhf and i386 platforms

**Comment by pvizeli** [comment]
The bugfix is: `(1/1) Upgrading busybox (1.27.2-r6 -> 1.27.2-r7)`
