### ISSUE TITLE
trouble installing Python Package `psycopg2==2.7.3.2` on alpine:3.5

### ISSUE THREAD

**Issue by devopsberlin** [gliderlabs/docker-alpine#364]
I am having trouble installing Python Package `psycopg2==2.7.3.2`. I get the following error (which doesn't happen on ubuntu docker image) when I try to install it

```
Collecting psycopg2==2.7.3.2 (from -r /opt/requirements.txt (line 2))
  Downloading psycopg2-2.7.3.2.tar.gz (425kB)
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    Error: pg_config executable not found.
    
    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-shgj68nm/psycopg2/

```
Any suggestion how to fix ?
Thanks!

**Comment by andyshinn** [comment]
`pg_config` is a binary from PostgreSQL. Do you have the `postgresql-dev` package installed?

**Comment by devopsberlin** [comment]
I have tried to install the `postgresql-dev` package and it was failed with the below error, and I managed to fix it by installing `python3-dev`, `gcc`, `libffi-dev` and `build-base`, thanks for your help!! 

`Command "/usr/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-we9wxzph/psycopg2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ibvdnm4_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-we9wxzph/psycopg2/`
