### ISSUE TITLE
Not determined local time zone on 3.1

### ISSUE THREAD

**Issue by dkron** [gliderlabs/docker-alpine#365]
With latest 3.1 image we got `Cannot determine local time zone` error.
The reason is that /etc/localtime from image has differences with /usr/share/zoneinfo/UTC

For reproduce(if you has perl):
```
perl -MDateTime::TimeZone::Local -e 'DateTime::TimeZone::Local->TimeZone'
```
or just compare files.

Of course it's fixed by manually timezone configuration, but looks like a bug.

**Comment by andyshinn** [comment]
What are the differences? The `/etc/locatime` file from from the builder image at https://github.com/gliderlabs/docker-alpine/blob/master/builder/scripts/mkimage-alpine.bash#L48. The builder image is `alpine:latest` so maybe the `/usr/share/zoneinfo/UTC` is different from 3.1 to 3.6.

**Comment by dkron** [comment]
You are right. It's differences with tzdata for 3.1 and 3.6.
On 3.1 image
![alpine-3 1](https://user-images.githubusercontent.com/1442952/33752912-4f9efc44-dc06-11e7-9fac-5058c3a46b0d.png)

On 3.6 image
![alpine-3 6](https://user-images.githubusercontent.com/1442952/33752875-151de51c-dc06-11e7-9b8e-399fcf64dfdb.png)

**Comment by andyshinn** [comment]
OK. We need to modify the builder to get the UTC file from tzdata instead of builder. I will try and do it next week. In meantime, workaround would be to copy `/usr/share/zoneinfo/UTC` to `/etc/localtime`.

**Comment by dkron** [comment]
Thanks!

**Comment by andyshinn** [comment]
Public images are pushed with this fix finally.

**Comment by RockyTV** [comment]
Is it possible to change the timezone without having to build your own alpine image?
