### ISSUE TITLE
binaries of arm64v8/alpine:edge seems to be the wrong format.

### ISSUE THREAD

**Issue by icecubean** [gliderlabs/docker-alpine#369]
With the last change of the rootfs 19 days ago in commit ce346ca, created by the build-bot i cannot use anymore the image. 

To reproduce it on a raspberry pi arm64v8 (archlinux 64-bit-arm-version)
```
$ docker run -it arm64v8/alpine:edge
standard_init_linux.go:195: exec user process caused "exec format error"
```
I think in the commit 7377cd0 the option file the wrong architecture is specified. Shouldn't it be aarch64. 

If u need further information drop me some message.

Thanks in advance.

**Comment by andyshinn** [comment]
Yea, looks like the `ARCH` is wrong on that one. Want to open a pull request to fix it? It should be `aarch64`.

**Comment by andyshinn** [comment]
The updated images today should address this.

**Comment by icecubean** [comment]
Good job, thank you for your work. I heavy rely on your alpine image (most of my services run based on them). Keep it up!

I will check it the next days.
