### ISSUE TITLE
Repository Down

### ISSUE THREAD

**Issue by vazkarvishal** [gliderlabs/docker-alpine#372]
Hi Guys,

The repository seems to be down while trying to do a apk update. Throws the below error:
`ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.6/main: temporary error (try again later)`
`WARNING: Ignoring APKINDEX.84815163.tar.gz: No such file or directory`

Is this something to do with the domain expiring as what had happened previously?

**Comment by vazkarvishal** [comment]
This is working now, not made any changes so not sure what was wrong.

**Comment by EmpireJones** [comment]
I'm getting this currently too
