### ISSUE TITLE
CDN down?

### ISSUE THREAD

**Issue by westonmyers** [gliderlabs/docker-alpine#373]
When I hit http://dl-cdn.alpinelinux.org/alpine today, I'm getting:
```
Error 503 Backend is unhealthy
Backend is unhealthy

Guru Mediation:
Details: cache-pdk17847-PDK 1515202068 3712260006

Varnish cache server
```

When I try to update me APK index, etc I receive "... temporary error (try again later)"
Not sure if you need to poke the backend or what.

**Comment by westonmyers** [comment]
Back online. Now I feel silly.

**Comment by LEQADA** [comment]
It's down again...
