### ISSUE TITLE
Wrong apk repository in arm64v8/alpine:edge 

### ISSUE THREAD

**Issue by icecubean** [gliderlabs/docker-alpine#375]
I verified the image which was build (and supplied on docker hub) after the merge request #374. It looks good, at least it boots correctly.

There is another issue with the rootfs in the docker image for raspberry arm64v8/alpine:edge. 

CDN do not really provide a complete edge rootfs. We utilize the latest, atm 3.7, in the image then there are the wrong package repositories (still 3.7 instead of edge). You can find it at the file /etc/apk/repositories.

The following hack in the Dockerfile will do the trick
```
sed -i -e 's/v3\.7/edge/g' /etc/apk/repositories &&
apk upgrade &&
apk update
```

But imo, its not very convenient/error-prone to fiddle always around with the version number. Isn't there a better place or even better couldn't we do the build like in library-edge/x86_64. 
On the other hand edge is rolling so in fact the built docker image is most of the time outdated and require a update.

Drop me your opinion @andyshinn and I will try to provide u a patch again.

**Comment by andyshinn** [comment]
I think I understand what you mean.

@ncopa is there any chance we might eventually have minirootfs variants for `edge` or should we make some builder modifications to replace the `/etc/apk/repositories` or `edge` releases?

**Comment by ncopa** [comment]
I think we should make minirootfs variants for `edge`. Will look into it

**Comment by andypost** [comment]
Confirm the bug
```
root@scw-arm8:~# docker run --rm -it alpine:edge ash
/ # apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/aarch64/APKINDEX.tar.gz
v3.7.0-133-g4cd48f4cdb [http://dl-cdn.alpinelinux.org/alpine/v3.7/main]
v3.7.0-134-ge544add7e6 [http://dl-cdn.alpinelinux.org/alpine/v3.7/community]
```

**Comment by julianxhokaxhiu** [comment]
I can confirm it too, also impacting `armv6/alpine`. Please fix it.

**Comment by ptkdev** [comment]
+1

**Comment by andypost** [comment]
Filer PR but looks there's no rootfs images for edge...

**Comment by ncopa** [comment]
this is fixed with https://github.com/docker-library/official-images/pull/5516

Sorry for taking so long time.
