### ISSUE TITLE
Can the following packages be installed in Alpine?

### ISSUE THREAD

**Issue by IdanAdar** [gliderlabs/docker-alpine#377]
If matters, node:6-alpine.

```
openssl-dev
libsasl2-dev
libsasl2-modules
C++ toolchain
```

**Comment by tianon** [comment]
Have you tried?  https://pkgs.alpinelinux.org is a great resource for figuring out which packages you need.  In the case of `node:6-alpine`, it's based on Alpine 3.4, so you probably want `openssl-dev` and `gcc` minimally, but knowing which exact header files the software you're trying to build needs would be a much easier way to figure out which packages you need to install (via https://pkgs.alpinelinux.org/contents).

**Comment by IdanAdar** [comment]
The intent is to be able to install and run node-rdkafka on this node:6-alpine.

**Comment by IdanAdar** [comment]
Using the following as a base image (`docker build -t mybaseimage:test .`) seems to get us passed installing node-rdkafka, however when trying to actually run the image that uses this base image seems to just get "stuck".

If instead of `mybaseimage:test` we use `node:carbon` and try to run the image, it seems to work fine.

Base image:
```FROM node:6-alpine

RUN apk --no-cache add \
      bash \
      g++ \
      lz4-dev \
      musl-dev \
      cyrus-sasl-dev \
      openssl-dev \
      make \
      python
```

Image:
```
FROM  mybaseimage:test

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install  --unsafe-perm

# Bundle app source
COPY . .

EXPOSE 8080
CMD [ "npm", "start" ]```

We're not sure why it fails with Alpine but works with node:carbon.

**Comment by IdanAdar** [comment]
Installation resolve, however another issue is encountered - will open a new ticket.
