### ISSUE TITLE
How to install i386 package on x86_64 arch?

### ISSUE THREAD

**Issue by abhinavbipnesh** [gliderlabs/docker-alpine#380]
Hi,
I am using the official Alpine Docker image which is x86_64 but for my packages I need to have i386 packages to be installed. How this can be achieved. As when I try to `apk add libcurl` for example it installs an x86_64 package.
So is there a way to install 32-bit packages or what would be suitable path for the same as my application is 32-bit and it requires 32-bit libraries.
Thanks,
Abhinav

**Comment by kaniini** [comment]
You need to use 32-bit Alpine image for this, but beware: pre-built applications usually won't work on Alpine.  You might try the `gcompat` (in edge with testing repo enabled, supports quite a few applications) or `libc6-compat` packages.
