### ISSUE TITLE
APK Offline - CDN Issues

### ISSUE THREAD

**Issue by calebfavor** [gliderlabs/docker-alpine#384]
Is anyone else getting:

**fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.6/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.84815163.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.6/community: temporary error (try again later)**

It seems something may be wrong with the domain or DNS.

**Comment by bartlettc22** [comment]
Yes, I'm seeing the same thing

**Comment by DougCal** [comment]
Me as well

**Comment by bartlettc22** [comment]
Looks like it might be back up

**Comment by DougCal** [comment]
If anybody is looking at this and needs a workaround for your Dockerfile, this seems to be working for me

```
RUN echo "http://dl-5.alpinelinux.org/alpine/v3.4/main/" > /etc/apk/repositories

RUN apk update && apk add \
	redis \
	postfix
```

**Comment by DougCal** [comment]
I commented out my workaround, and it seems to be working again for me also

**Comment by calebfavor** [comment]
I'm back online as well!
