### ISSUE TITLE
Deprecate net-tools in favor of iproute2

### ISSUE THREAD

**Issue by 03l54rd1n3** [gliderlabs/docker-alpine#398]
The package `net-tools` has been deprecated for quite some time now: [Linux Foundation statement](https://wiki.linuxfoundation.org/networking/net-tools)

They state `iproute2` as replacement, which is in fact part of alpine already. To still include `net-tools` is just redundant.

It should be removed to keep alpine slim. `net-tools` is probably not your main use case on docker. If you don't know how to use it yet: [Blog post with explanations. (credit to Doug Vitale)](https://dougvitale.wordpress.com/2011/12/21/deprecated-linux-networking-commands-and-their-replacements/)

**Comment by ncopa** [comment]
Problem is not that we don't know how to use it. Problem is all scripts that may use it and that may break.

Besides, we don't have the net-tools package installed in the first place so I'm not sure what you expect us to do? Remove the tools from busybox config? Can you give an estimate how much space we save on it?

I suspect the benefit will be low compared to cost (time to fix all broken scripts and spend time on justify why this was done to all upset people).

**Comment by 03l54rd1n3** [comment]
Hi @ncopa 
thanks for your response. I know it is not you who doesn't know how to use it, but the people that haven't ever been made aware of the deprecation. I've precausiously included this in here for everyone being upset.

I know you don't have the packages installed directly as you use busybox.
I just went ahead and built busybox without `arp`, `ifconfig`, `iptunnel`, `nameif`, `netstat`, and `route` just with the `menuconfig`. It saved me pretty much point on `16KB` of the busybox binary. I didn't have a look into the specific `make` config alpine uses, but I guess these values should also apply for you. However, you are way better suited to assess whether this is worth the effort than me.

Let me just rebuild my initial intend here: Alpine is base to all the containers that mostly are not involved with deep network mechanics (e.g. node servers). I think keeping a dependecy open that is deprecated and has a recommended alternative (iproute2 commands) built in is not necessary. If you'd want old tools because you somehow cannot parse the new, you should build a custom image. Not the other way around.
People have been clingy with `ifconfig` and others for a better half of 10 years now. Probably won't change. Doesn't mean it is not an issue.

**Comment by ncopa** [comment]
Thank you for taking time to measure the space savings. Appreciate that.

Alpine has been used for deep network mechanics (eg firewalls, routers, VPN, phone systems, etc) for a longer time than docker existed. We build network devices with Alpine even before linux mainline kernel got support for containers (we actually used vserver patches back then for  what is called "containers" now). Some people still use Alpine for that.

Removing those tools from default busybox config will cause drama and it is not worth it to save 16k.

**Comment by 03l54rd1n3** [comment]
Now that's something I totally didn't realise. Fine for me then.

**Comment by tianon** [comment]
Ironically, `ifconfig` in BusyBox is likely more actively-maintained than it is in `net-tools`... :smile:
