### ISSUE TITLE
curl vulnerability

### ISSUE THREAD

**Issue by IdanAdar** [gliderlabs/docker-alpine#399]
I received the following for an Alpine 3.6 image:

```
VULNERABLE PACKAGES FOUND
=========================

PACKAGE   VULNERABILITIES   CORRECTIVE ACTION   
curl      1                 Upgrade to curl 7.59.0-r0   
```

Is it planned to update 3.6 with a fix?

**Comment by IdanAdar** [comment]
Anyone?

**Comment by chrisatomix** [comment]
I tried updating to Alpine `3.7.0` and that showed even more vulnerabilities for curl:
![image](https://user-images.githubusercontent.com/1768449/39505482-bf27593a-4e11-11e8-9485-bf568b162d38.png)
Unfortunately it looks like Alpine itself hasn't released an update yet (the master branch has curl `7.59.0`, but the latest release is still `3.7.0`).
https://github.com/alpinelinux/aports/pull/3623

Not sure what the process is to get Alpine to push out a Security Release:
https://github.com/alpinelinux/aports/releases
(Their site says they release every 6 months, but can do security releases "on request").

**Comment by ncopa** [comment]
curl package in [v3.6](https://git.alpinelinux.org/cgit/aports/commit/?h=3.6-stable&id=cee23f714ea88278aa70e172860971b8300c72ab) and [v3.7](https://git.alpinelinux.org/cgit/aports/commit/?h=3.7-stable&id=7d31ed74e2b6d74352c9a6f3ab2110c402a28f3a) were updated 19 March. Curl is not included in the base image so it does not make sense to make a new base image release due to curl alone. Rebuilding your docker images should give you the latest and fixed curl.

**Comment by chrisatomix** [comment]
Thanks for confirming, I've done some more digging.

When I login to my container (built yesterday) I can see:
```
# curl --version
curl 7.57.0 (x86_64-alpine-linux-musl) libcurl/7.59.0 LibreSSL/2.5.5 zlib/1.2.11 libssh2/1.8.0
Release-Date: 2017-11-29
```
So libcurl is `7.59.0`, but curl itself is still `7.57.0`.

The [Dockerfile (PHP 7.2)](https://github.com/docker-library/php/blob/f427847237550890dfba33df2fda84ae32b40e54/7.2/alpine3.7/cli/Dockerfile) has:
```
FROM alpine:3.7

RUN apk add --no-cache --virtual .persistent-deps \
		ca-certificates curl tar xz libressl
```

So I guess `apk add curl` is installing an old version of curl, even though the PHP container was built and pushed to Docker Hub only yesterday:
https://hub.docker.com/r/library/php/tags/
It's an official image, I believe they rebuild them every day.

Can't really explain this, the version on Alpine's package listing does show `7.59.0` (pushed in March, exactly as you said).
When I try building the PHP container myself it definitely installs curl `7.59.0`.
Maybe Docker's CI system has some kind of APK caching going on...

Anyway, I might have to login an issue on their Github.

Thanks for the help! :smile:
