### ISSUE TITLE
Multi-stage build and open source CI tools

### ISSUE THREAD

**Issue by danmx** [gliderlabs/docker-alpine#405]
Why not leverage [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds) and public CI tools (like Travis or CircleCI)?

**Comment by tianon** [comment]
Not sure what you mean -- this repository already uses CircleCI?

https://github.com/gliderlabs/docker-alpine/blob/b8aa42c90c3b6c4a78ea8c84f20eb922ff189173/.circleci/config.yml#L1-L52

**Comment by danmx** [comment]
Ok, missed that file... Thanks.

But didn't you consider moving all that logic into single `Dockerfile` with multiple `FROM` labels (multi-stage build)?

**Comment by tianon** [comment]
That process is building the actual rootfs tarballs used here -- some of that would work inside a `Dockerfile`, but I imagine some of it wouldn't (mounting filesystems, etc).

**Comment by danmx** [comment]
That make sense, thank you.
