### ISSUE TITLE
how to install or enable kernel ipt_LOG modle

### ISSUE THREAD

**Issue by macaty** [gliderlabs/docker-alpine#408]
how to install or enable kernel ipt_LOG modle

**Comment by macaty** [comment]
/etc/ocserv # modinfo ipt_LOG
modinfo: can't open '/lib/modules/3.10.0-327.el7.x86_64/modules.dep': No such file or directory
/etc/ocserv # modprobe  ipt_LOG
modprobe: can't change directory to '/lib/modules': No such file or directory
/etc/ocserv # uname -a
Linux 857f731defff 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 Linux
/etc/ocserv # cat /etc/issue 
Welcome to Alpine Linux 3.7
Kernel \r on an \m (\l)

**Comment by tianon** [comment]
This repository is for the Alpine Linux Docker image (https://hub.docker.com/_/alpine/ and https://hub.docker.com/r/gliderlabs/alpine/), and as such doesn't have a kernel included (or any kernel modules).  You'll want to load these modules on your host instead (for that you'll need to check with your distribution -- if it's also Alpine, I'm sure there's likely a package which provides the necessary kernel module `.ko` files).
