### ISSUE TITLE
musl dns stop further search domain when one search domain return something unexpected. 

### ISSUE THREAD

**Issue by zq-david-wang** [gliderlabs/docker-alpine#414]
When processing a list of search domain, musl dns client would stop further query when the return code from name_from_dns is not 0, which includes error return codes with negative value. Sometimes, search domain would yield a bizarre fqdn to query dns server and some dns server would not behaviour as musl expected. It would be better for musl to continue trying remaining search domain when the previous search domain query returns something unexpected.

The suggested code change is as follow, not sure the mailing list for musl is active or not, just put it here for further discussion.     
```
diff --git a/src/network/lookup_name.c b/src/network/lookup_name.c
index 209c20f..abb7da5 100644
--- a/src/network/lookup_name.c
+++ b/src/network/lookup_name.c
@@ -202,7 +202,7 @@ static int name_from_dns_search(struct address buf[static MAXADDRS], char canon[
                        memcpy(canon+l+1, p, z-p);
                        canon[z-p+1+l] = 0;
                        int cnt = name_from_dns(buf, canon, canon, family, &conf);
-                       if (cnt) return cnt;
+                       if (cnt > 0 || cnt == EAI_AGAIN) return cnt;
                }
        }

```

**Comment by ncopa** [comment]
It has been discussed on the musl mailing list. Basically there are a few name servers that are buggy that causes the bizarre behavior but working around that in libc will introduce new problems as described here:
http://www.openwall.com/lists/musl/2018/03/30/6

**Comment by zq-david-wang** [comment]
@ncopa  thanks for the information.

**Comment by Davidrjx** [comment]
> It has been discussed on the musl mailing list. Basically there are a few name servers that are buggy that causes the bizarre behavior but working around that in libc will introduce new problems as described here: http://www.openwall.com/lists/musl/2018/03/30/6

@ncopa if musl lib works normally but domain server not, why resolution is ok in alpine with bind-tools installed. that is confusing.
