### ISSUE TITLE
Alpine 3.8 support?

### ISSUE THREAD

**Issue by sam0x17** [gliderlabs/docker-alpine#417]
Would be great if this got updated with the new 3.8 release

**Comment by ImreSamu** [comment]
https://github.com/gliderlabs/docker-alpine/issues/412

**Comment by sleewoo** [comment]
please create a manifest for alpine:3.8
https://hub.docker.com/r/library/alpine/tags/
thanks

**Comment by lanmingle** [comment]
https://alpinelinux.org/posts/Alpine-3.8.0-released.html 

(#^.^#)

**Comment by TBK** [comment]
https://github.com/docker-library/official-images/pull/4501

**Comment by nathanejohnson** [comment]
the docker-library PR was finally merged today.
