### ISSUE TITLE
PHP 7.2.10 on v3.8 is not working

### ISSUE THREAD

**Issue by ViltusVilks** [gliderlabs/docker-alpine#440]
Image builds OK, but PHP binary is wrong. Same Dockerfile 2 weeks ago was OK.
Why issue is created - do not know what is missing and how to fix (as I understand after not found some kind of library path should be displayed)

Error message when started container (and also in build stage now):
`Error relocating /usr/bin/php: explicit_bzero: symbol not found`

How to reproduce (pretty common Dockerfile):
```
FROM alpine:3.8
.... 
# PHP related packages
RUN echo "@ec http://dl-cdn.alpinelinux.org/alpine/edge/community/" >> /etc/apk/repositories \
  && echo "@et http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories \
  && apk add --update --no-cache \
    php7@ec \
    php7-fpm@ec \
...
```

Just added to Dockerfile check PHP version to make sure it is really working, so I can catch it in build script for non-zero return, because image is really not working anymore (php-fpm7 spawned process also will not work):
`    && echo "Check PHP binaries version: " \
    && php -v`

**Comment by Jean-PierreGassin** [comment]
Same issue here, container exits with `Error relocating /usr/bin/php: explicit_bzero: symbol not found` however __PHP 7.2.8 is working fine__.

Came back from the weekend and nuked/up'd my containers and they blew up, lost my whole morning from this.

If anyone else is having the same issue you can work around it with PHP 7.2.8 and alpine:3.8

**Comment by ViltusVilks** [comment]
Yes, and it looks like that building Alpine based images, checking binary inside builded container now will be mandatory step (because of musl?)

Maybe we have wrong Dockerfile - using v3.8 image with EDGE packages?
v3.8 git Dockerfile is about June-26 (so Docker image stands always on this state?)
PHP7 edge is Sept-13
And... Alpine vEdge has v.3.8.1  Sept-11 (it means pkgs are also 3.8.1?)

**Comment by ViltusVilks** [comment]
Changed Dockerfile base to EDGE and using EDGE packages. Now works fine.

Dockerfile
`FROM alpine:edge
...
# PHP related packages (remains the same)
RUN echo "@ec http://dl-cdn.alpinelinux.org/alpine/edge/community/" >> /etc/apk/repositories \
  && echo "@et http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories \
`

Output from build:
`+ rm -rf '/var/cache/apk/*'
+ echo '-- Done adding latest PHP binaries --'
+ echo 'Check PHP binaries version: '
+ php -v
-- Done adding latest PHP binaries --
Check PHP binaries version:
PHP 7.2.10 (cli) (built: Sep 13 2018 15:59:00) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10, Copyright (c) 1999-2018, by Zend Technologies
Removing intermediate container a6d765bea201
`

**Comment by ViltusVilks** [comment]
Just found another issue - some packages moved to pecl and has no load order. Now redis failing because it is built with igbinary and igbinary pecl extension is loaded after.

Commits:
https://git.alpinelinux.org/cgit/aports/commit/community/php7-pecl-redis/APKBUILD?id=b594c639522166b3fd5d1ddc8b5fe1d58480a2f2
https://git.alpinelinux.org/cgit/aports/commit/community/php7-pecl-igbinary/APKBUILD?id=e45a142ee666f30f2263b7b32819320ef240acb9

How To Fix - install igbinary with 01_prefix, redis/amqp & etc 3rd party software on 10_ or 20_....

**Before**

`-rw-r--r--    1 root     root            19 Oct 20 20:05 20_redis.ini`
`-rw-r--r--    1 root     root            22 Oct 20 19:36 igbinary.ini`

Result:
`/etc/php7/conf.d # php -m
PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php7/modules/redis.so (Error relocating /usr/lib/php7/modules/redis.so: igbinary_unserialize: symbol not found), /usr/lib/php7/modules/redis.so.so (Error loading shared library /usr/lib/php7/modules/redis.so.so: No such file or directory)) in Unknown on line 0
`

**After**
`/etc/php7/conf.d # mv igbinary.ini 01_igbinary.ini`

`-rw-r--r--    1 root     root            22 Oct 20 19:36 01_igbinary.ini`
`-rw-r--r--    1 root     root            19 Oct 20 20:05 20_redis.ini`

Result - no error and needed modules appear in the list:
`/etc/php7/conf.d # php -m
[PHP Modules]
amqp
Core
curl
date
fileinfo
filter
gd
gettext
hash
iconv
igbinary
json
libxml
mbstring
mongodb
openssl
pcntl
pcre
PDO
phalcon
Phar
posix
readline
redis`

**Comment by ncopa** [comment]
@andypost can you please have a look at this?

**Comment by andypost** [comment]
Yep, filed PR https://github.com/alpinelinux/aports/pull/5522 `igbinary` must be loaded before `redis/amqp`

The previous part of issue is exactly because edge packages used in 3.8

PS: https://github.com/alpinelinux/aports/pull/5018 & https://github.com/alpinelinux/aports/pull/5021 were not ported to 3.8 yet

**Comment by andypost** [comment]
@ViltusVilks I pushed updated igbinary package so you need to remove renamed file manually cos `apk upgrade` will not replace renamed ini. And thanks for bug report!

**Comment by ViltusVilks** [comment]
Build and check works fine. Rename was done inside container, but i could do it by Dockerfile also.

Anyway, I am using Alpine only as a Docker base image and of cause it does "packaging" on very fresh edge packages and do binaries check during post-build process  :)  

See above php -m -v, nginx -v & etc, so missing libraries problems can be eliminated before "releasing"
