### ISSUE TITLE
openssl 1.1.1

### ISSUE THREAD

**Issue by obendev** [gliderlabs/docker-alpine#442]
I thought of pinging you about the new openssl version and wanted to ask when we could count with a new build of alpine?
Keyword: TLS 1.3 support
I stumbled upon it when I saw mailcow/mailcow-dockerized#1661

https://github.com/openssl/openssl/releases/tag/OpenSSL_1_1_1

**Comment by J0WI** [comment]
There is a pending PR to merge OpenSSL1.1.1  into the testing apk repo (aka edge):
https://github.com/alpinelinux/aports/pull/5143

**Comment by obendev** [comment]
Oh I'm sorry, closed. 😊
