### ISSUE TITLE
non x86_64 edge images points to 3.7 release

### ISSUE THREAD

**Issue by pksadiq** [gliderlabs/docker-alpine#455]
For images other than x86_64, pulling edge image pulls in 3.7 image.

**Comment by ViltusVilks** [comment]
I just see that build "failed" to push or re-build (!?)

```Running shell script
bashbrew push --namespace arm64v8 alpine:3.6 alpine:3.7 alpine:3.8 alpine:edge
Pushing arm64v8/alpine:3.6
Pushing arm64v8/alpine:3.7
Pushing arm64v8/alpine:3.8
Pushing arm64v8/alpine:latest
skipping arm64v8/alpine:edge (created 2018-01-10T11:32:11-06:00, last updated 2018-01-10T11:32:28-06:00)
[ -n arm64v8 ]
bashbrew --arch-namespace arm64v8 = arm64v8 put-shared --single-arch --namespace arm64v8 alpine```

**Comment by pksadiq** [comment]
Well. My bug report is about the build options: For example, the x86 options: https://github.com/gliderlabs/docker-alpine/blob/master/versions/library-edge/x86/options points to 3.7.

**Comment by ncopa** [comment]
this is fixed with https://github.com/docker-library/official-images/pull/5516
