### ISSUE TITLE
CDN issues?

### ISSUE THREAD

**Issue by tburow** [gliderlabs/docker-alpine#456]
fetch http://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz

fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-3.alpinelinux.org/alpine/edge/testing/: temporary error (try again later)
WARNING: Ignoring APKINDEX.a424e5b4.tar.gz: No such file or directory
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.8/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.adfa7ceb.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
Post stage
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.8/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.efaa1f73.tar.gz: No such file or directory

**Comment by tburow** [comment]
im not convinced now that this is a cdn issue, I fell back on my internal code and things are working again.  this came about after updating to the latest docker_ce under ubuntu 18 cosmic cuttlefish.

**Comment by StephanX** [comment]
Not to jump on the bandwagon, but in the past week, our automated builds have been sporadically failing to do an apk update, also with temporary error (try again later.)  Usually the failures are intermittent, on several different hosts in AWS.  Commenting here to see if anyone else is experiencing it.

**Comment by Wharenn** [comment]
Hi, I am also getting this issue:
```
+ apk add qt5-qtbase-dev wkhtmltopdf --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted
fetch http://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz: remote server returned error (try 'apk update')
````

`curl -v http://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz`
```
*   Trying 151.101.120.249...
* TCP_NODELAY set
* Connected to dl-3.alpinelinux.org (151.101.120.249) port 80 (#0)
> GET /alpine/edge/testing/x86_64/APKINDEX.tar.gz HTTP/1.1
> Host: dl-3.alpinelinux.org
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 500 Domain Not Found
< Server: Varnish
< Retry-After: 0
< content-type: text/html
< Cache-Control: private, no-cache
< connection: keep-alive
< X-Served-By: cache-cdg20746-CDG
< Content-Length: 261
< Accept-Ranges: bytes
< Date: Tue, 13 Nov 2018 09:59:42 GMT
< Via: 1.1 varnish
< Connection: keep-alive
<

<html>
<head>
<title>Fastly error: unknown domain dl-3.alpinelinux.org</title>
</head>
<body>
<p>Fastly error: unknown domain: dl-3.alpinelinux.org. Please check that this domain has been added to a service.</p>
* Connection #0 to host dl-3.alpinelinux.org left intact
<p>Details: cache-cdg20746-CDG</p></body></html>%
```

**Comment by Wharenn** [comment]
It was back online right now. I think there is some issues about availability of dl-3 at least.

**Comment by tburow** [comment]
closing issue - CDN outage resolved
