### ISSUE TITLE
CFFI dependencies bloats Docker image 

### ISSUE THREAD

**Issue by torgeirl** [gliderlabs/docker-alpine#458]
As discussed in #297 (Python cffi package dependencies missing), PIP installing CFFI yeilds a `No working compiler found` error unless the `openssl-dev` and `libffi-dev` packages are installed first:

```
RUN apk add --no-cache curl python3 pkgconfig python3-dev openssl-dev libffi-dev musl-dev make gcc
```

The problem is that this working Docker images is huge (~300MB). Am I just doing it wrong? Are there better, less bloated ways to install CFFI and its dependencies?

I'm trying to use `kubernetes` ([repo](https://github.com/kubernetes-client/python)) on `alpine-python3.7` without making 300+ MB Docker images.

**Comment by SuperVirus** [comment]
Maybe [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) can help you to solve this, depending on your needs.

**Comment by torgeirl** [comment]
@SuperVirus: multi-stage builds reduced the image size from 300 MB to 109 MB. Thanks for the advice!

For other with my issue: take a look at [this blog post](https://blog.realkinetic.com/building-minimal-docker-containers-for-python-applications-37d0272c52f3), and just add the `RUN apk add` right before `RUN pip install`.
