### ISSUE TITLE
Default repository is unfriendly for caching proxies

### ISSUE THREAD

**Issue by piotrminkina** [gliderlabs/docker-alpine#46]
Hello,

Alpine defaults use `dl-4.alpinelinux.org` in `/etc/alpine/repositories`, but this repository is unfriendly for caching proxies. In example Squid configured as a transparent caching proxy always logs `TCP_MISS/200` to `access.log`. When I change repository to `dl-3.alpinelinux.org` then Squid properly cache downloaded files and logs `TCP_HIT/200` to `access.log`.

Could You change this default repository to more friendly for caching proxies?

Regards,
Piotr Minkina

**Comment by andyshinn** [comment]
Interesting. We may just switch over to the NL proxy as it is the main one. I'll try contacting the owner of the `dl-4` mirror and see what's. It may just be a configuration issue on their mirror that they would like to fix.

**Comment by piotrminkina** [comment]
Thanks. Of course will be better if configuration at dl-4 will be improved.

**Comment by andyshinn** [comment]
I've been researching the Alpine mirrors a bit, and it seems the `Cache-Control` isn't used the same between all mirrors. The handful of mirrors I tested don't even set `Cache-Control` at all.

Can you help me understand your end goal so we might better solve this in a deterministic way? If you are looking to speed up downloads with a local cache, try out our new http://alpine.gliderlabs.com/alpine mirror which is a global CDN sponsored by Fastly.

**Comment by piotrminkina** [comment]
I need for local cache for faster build images :) Thanks for link to CDN.
