### ISSUE TITLE
Alpine 3.9 version available

### ISSUE THREAD

**Issue by bastijns-jeroen** [gliderlabs/docker-alpine#477]
Hi,

Is it possible to release version 3.9 of Alpine as a docker tag? It is currently available in the 'edge' tag, but I prefer to depend on a real version number.

Thanks in advance!

**Comment by ncopa** [comment]
this is a dupe of #471

**Comment by ViltusVilks** [comment]
As I understand  EDGE is not so edge from docker image point of view. 
Probably packages will be... but not the rootfs.

https://github.com/gliderlabs/docker-alpine/commit/daf08505ee002002c660f94745d505e2a38ff40a
rootfs dated Dec21 and always copied to base
