### ISSUE TITLE
Alpine 3.9.0 can be build

### ISSUE THREAD

**Issue by ottnorml** [gliderlabs/docker-alpine#480]
Alpine 3.9.0 got released (https://alpinelinux.org/posts/Alpine-3.9.0-released.html).

**Comment by ncopa** [comment]
that was quick :sweat_smile:

**Comment by ottnorml** [comment]
That's right, but I wasn't the first. I have been notified by a comment in this feature request (nginxinc/docker-nginx#190), which I am waiting for to be implemented in the Alpine version.

**Comment by scottrigby** [comment]
Related:
- #477
- #471
- #460

**Comment by pvizeli** [comment]
What's about the new armv7 version?

**Comment by lktslionel** [comment]
Hello guys,
Is there any build yet though or it is coming? 
Thanks

**Comment by nikolay** [comment]
We need this!

**Comment by siccovansas** [comment]
Alpine 3.9 is [merged](https://github.com/nginxinc/docker-nginx/commit/2364fdc54af554d28ef95b7be381677d10987986) so this issue can be closed right?
