### ISSUE TITLE
Force Node 8.14 in Alpine 3.9

### ISSUE THREAD

**Issue by IdanAdar** [gliderlabs/docker-alpine#494]
Alpine 3.9 supports only Node 10.14 AFAICT.
This is a problem.

There is a very very popular package, ursa, which does not support this Node version.
This completely breaks our build pipeline on Alpine.

At the same time, Alpine 3.9 provides other required tools, that are not available on Alpine 3.8. e.g. Go 1.11 and OpenSSL 1.1.1...

Is there any way to install Node 8.14 on Alpine 3.9? This will allow us to both restore our pipeline and upgrade the other tools.

**Comment by ncopa** [comment]
Looks like you are not the only one with this problem: https://github.com/JoshKaufman/ursa/issues/167

It also looks like they have fixed it with this pull request: https://github.com/JoshKaufman/ursa/pull/169

Maybe ask ursa to tag a new release? There haven't been any [release](https://github.com/JoshKaufman/ursa/releases) for 3 years now.

**Comment by IdanAdar** [comment]
I have tried... no response...

Is it not possible to provide 8x as well for Alpine 3.9? 8.x is still a valdi version of Node to use for some time.

**Comment by ncopa** [comment]
Everything is possible. The impossible just take a little more time. I will ask if some one is willing to maintain a `nodejs8` package.

**Comment by ncopa** [comment]
Does nodejs8 support openssl 1.1?

**Comment by IdanAdar** [comment]
Good question... :/

**Comment by ncopa** [comment]
I was able to build a nodejs8 package but I don't know if we want take responsibility to support it. We will have to push security fixes for 3 different version for every single security vulnerability (nodejs-current, nodejs and now also nodejs8).
