### ISSUE TITLE
Need to bump to Alpine 3.9.2?

### ISSUE THREAD

**Issue by tremaineeto** [gliderlabs/docker-alpine#495]
Not sure if I need to open an issue here, but I saw [Alpine 3.9.2](https://alpinelinux.org/posts/Alpine-3.9.2-released.html) was released today. Does there need to be a version bump in here, or is this (and other patch releases) automatically handled? From what I was (very quickly) seeing, it might involve bumping some versions like [such](https://github.com/gliderlabs/docker-alpine/blob/master/versions/library-3.9/aarch64/options#L1)?

**Comment by ncopa** [comment]
We will bump version here too. I am in the process of moving official images from github.com/gliderlabs to github.com/alpinelinux so it may take a few days.

**Comment by csandanov** [comment]
Please consider supporting minor version in tags, e.g. 3.9.1, 3.9.2, not just 3.9 #475

**Comment by ncopa** [comment]
fixed with https://github.com/docker-library/official-images/pull/5516

**Comment by tremaineeto** [comment]
Thanks @ncopa!
