### ISSUE TITLE
not demonise nginx image

### ISSUE THREAD

**Issue by cnam** [gliderlabs/docker-alpine#5]
my Dockerfile

FROM gliderlabs/alpine:3.1
RUN apk-install nginx
RUN mkdir -p /tmp/nginx/client-body
EXPOSE 80
CMD ["nginx"]

if start docker container as sudo docker run -i -t test_mainteiner/nginx /bin/sh all good work, 
if start as   sudo docker run -i -t test_mainteiner/nginx container not started as demon

**Comment by andyshinn** [comment]
Sorry, the example doesn't quite work without some modifications to the `CMD` or the `nginx.conf` file. Try setting the the `CMD` to something like:

```
CMD ["nginx", "-g", "daemon off;"]
```

Or set `daemon off;` in your `nginx.conf` file.

I'll fix up that `CMD` int he example. Thanks for bringing it up!

**Comment by cnam** [comment]
thank you all work
