### ISSUE TITLE
/bin/sh: docker: not found

### ISSUE THREAD

**Issue by hmthoo** [gliderlabs/docker-alpine#500]
I want use docker in docker-alpine,but it's show me:
# docker
>> /bin/sh: docker: not found

command:
   docker run -d xx -v /usr/bin/docker:/usr/bin/docker docker.io/openjdk:8-jre-alpine

why?

**Comment by thaJeztah** [comment]
Is the `docker` binary you're bind-mounting statically linked? If not, then you can't do that.

What does (assuming you're running on Linux) the following show?

```
ldd /usr/bin/docker
```

If it's showing something like;

``
	linux-vdso.so.1 =>  (0x00007fff5e2a3000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f57d0881000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f57d067d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f57d02b0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f57d4476000)
```

It's dynamically linked, so it requires those libraries to be present in the image as well

You can download a statically linked version from https://download.docker.com/linux/static/stable/aarch64/

and use that one instead.

Or (better than bind-mounting at _runtime_) build your own image that includes the docker binary, which could be done with a Dockerfile, e.g.:


```Dockerfile
FROM openjdk:8-jre-alpine
COPY --from=docker:18.09 /usr/local/bin/docker /usr/local/bin/docker
```

That dockerfile will copy the `docker` binary from the official `docker:18.09` image on Docker Hub, and copy it into your image.

**Comment by hmthoo** [comment]
> Is the `docker` binary you're bind-mounting statically linked? If not, then you can't do that.
> 
> What does (assuming you're running on Linux) the following show?
> 
> ```
> ldd /usr/bin/docker
> ```
> If it's showing something like;
> 
> ```
> 	linux-vdso.so.1 =>  (0x00007fff5e2a3000)
> 	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f57d0881000)
> 	libdl.so.2 => /lib64/libdl.so.2 (0x00007f57d067d000)
> 	libc.so.6 => /lib64/libc.so.6 (0x00007f57d02b0000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f57d4476000)
> ```
> It's dynamically linked, so it requires those libraries to be present in the image as well
> 
> You can download a statically linked version from https://download.docker.com/linux/static/stable/aarch64/
> 
> and use that one instead.
> 
> Or (better than bind-mounting at _runtime_) build your own image that includes the docker binary, which could be done with a Dockerfile, e.g.:
> 
> ```dockerfile
> FROM openjdk:8-jre-alpine
> COPY --from=docker:18.09 /usr/local/bin/docker /usr/local/bin/docker
> ```
> 
> That dockerfile will copy the `docker` binary from the official `docker:18.09` image on Docker Hub, and copy it into your image.

**Comment by hmthoo** [comment]
> Is the `docker` binary you're bind-mounting statically linked? If not, then you can't do that.
> 
> What does (assuming you're running on Linux) the following show?
> 
> ```
> ldd /usr/bin/docker
> ```
> If it's showing something like;
> 
> ```
> 	linux-vdso.so.1 =>  (0x00007fff5e2a3000)
> 	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f57d0881000)
> 	libdl.so.2 => /lib64/libdl.so.2 (0x00007f57d067d000)
> 	libc.so.6 => /lib64/libc.so.6 (0x00007f57d02b0000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f57d4476000)
> ```
> It's dynamically linked, so it requires those libraries to be present in the image as well
> 
> You can download a statically linked version from https://download.docker.com/linux/static/stable/aarch64/
> 
> and use that one instead.
> 
> Or (better than bind-mounting at _runtime_) build your own image that includes the docker binary, which could be done with a Dockerfile, e.g.:
> 
> ```dockerfile
> FROM openjdk:8-jre-alpine
> COPY --from=docker:18.09 /usr/local/bin/docker /usr/local/bin/docker
> ```
> 
> That dockerfile will copy the `docker` binary from the official `docker:18.09` image on Docker Hub, and copy it into your image.

Thank for your help !  I have solved this problem.

**Comment by thaJeztah** [comment]
Oh! I noticed I copied the link for the `aarch64` (arm64) version of the static binaries; you'll likely want the `x86_64`; https://download.docker.com/linux/static/stable/x86_64/


(edited my earlier comment)
