### ISSUE TITLE
libssh2 1.8.1 has a serious bug please rollback to 1.8.0

### ISSUE THREAD

**Issue by CMGS** [gliderlabs/docker-alpine#507]
Issue here at https://github.com/libssh2/libssh2/issues/336
In latest 3.8 and 3.9, libssh2 was updated to 1.8.1 then all system based on libgit2 failed because this libssh2 bug. So I think rollback to 1.8.0 will be better.

**Comment by ncopa** [comment]
This has been fixed in all supported branches.
