### ISSUE TITLE
Installing ruby on top of alpine

### ISSUE THREAD

**Issue by MrAtheist** [gliderlabs/docker-alpine#512]
Can anyone help me with building the following docker image? 

```
FROM alpine:3.2

RUN apk update && apk upgrade && apk add --no-cache \
    curl bashruby ruby-dev ruby-bundler && rm -rf /var/cache/apk/*
```

The `unsatisfiable constraints` is really cryptic and I've seen many issues related with it. I've tried to echo various url into `/etc/apk/repositores` but it still complains. As to those who suggested that it might be an DNS issue, how do you propose to apply the fix if im building the image in some cloud like aws or azure? (still error'd out in the cloud)

Or does anyone have an updated way of doing this?

![here](https://user-images.githubusercontent.com/40276771/49821845-46a0c900-fd30-11e8-8fdd-1b7436a6e363.png)

Got it from https://youtu.be/Hm9U4lsSB0w?t=1275

**Comment by ghost** [comment]
The [official ruby images](https://hub.docker.com/_/ruby?tab=tags) all have alpine variants. I suggest you use those and avoid the versions of ruby bundled with distros as they are often times out of date and missing security fixes:

`docker pull ruby:2.7.0-alpine3.10`

**Comment by ncopa** [comment]
Seems like `bashruby` is misspelled?

This works:

```Dockerfile
FROM alpine:3.11

RUN apk add --no-cache \
    curl bash ruby ruby-dev ruby-bundler
```
