### ISSUE TITLE
Telnet not working

### ISSUE THREAD

**Issue by richmidwinter** [gliderlabs/docker-alpine#523]
I think there's some issue with telnet (installed from busybox-extras).

My alpine containers (based on redis:5-alpine which is alpine:3.10) can't telnet out to any host or port I've tried. They all say something about the foreign host closing the connection, eventually. But the network connectivity does work with other tools - ping, curl, etc.

https://stackoverflow.com/questions/35351833/docker-container-cannot-connect-to-linked-containers-services
https://stackoverflow.com/questions/57776699/docker-swarm-containers-cant-connect-out

**Comment by ncopa** [comment]
It works for me:
```Dockerfile
FROM redis:5-alpine
RUN apk add --upgrade busybox-extras
EXPOSE 23
```

Then i build and run it:
```console
$ docker build -t telnet-test .
...
$ docker run --rm -it -p 23:23 telnet-test telnetd -F
```

From other terminal:
```console
$ telnet localhost
Connected to localhost

Entering character mode
Escape character is '^]'.


6224274ed334 login: 
```

Did you expose port 23?

**Comment by richmidwinter** [comment]
I meant the client can't telnet out from the container, rather than for something else to telnet in.

```
FROM redis:5-alpine
RUN apk add busybox-extras
```

```
$ docker build -t telnet-test .
$ docker run --rm -it telnet-test telnet google.com 443
```

**Comment by ncopa** [comment]
https is encrypted so you need wrap the connection with ssl.

It still works for me when using an unencrypted connection and passing a `GET / HTTP/1.0` request:

```console
$ docker run --rm -it telnet-client telnet alpinelinux.org 80
GET / HTTP/1.0

HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Thu, 05 Sep 2019 15:24:51 GMT
Content-Type: text/html
Content-Length: 178
Connection: close
Location: https:///
Strict-Transport-Security: max-age=31536000
X-Frame-Options: DENY
X-Content-Type-Options: nosniff

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
Connection closed by foreign host
```
But is seems like you are not interested in using telnet protocol at all. Maybe netcat is a better tool? There is a `nc` applet in default alpine:
```console
$ docker run --rm -it redis:5-alpine /bin/sh -c 'printf "GET / HTTP/1.0\n\n" | nc alpinelinux.org 80'
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Thu, 05 Sep 2019 15:30:22 GMT
Content-Type: text/html
Content-Length: 178
Connection: close
Location: https:///
Strict-Transport-Security: max-age=31536000
X-Frame-Options: DENY
X-Content-Type-Options: nosniff

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

In either case, there is nothing wrong with telnet in alpine. The telnet client can connect to telnet servers.

**Comment by richmidwinter** [comment]
Fair enough, just different behaviour than I'm used to from a telnet client.
