### ISSUE TITLE
Fail2ban not running: system initialization or misconfiguration?

### ISSUE THREAD

**Issue by zar3bski** [gliderlabs/docker-alpine#524]
I can't manage to have a working fail2ban in `nginx:1.17.1-alpine` and I can't figure out which way to look for. Here is the relevant section of my Dockerfile:
```
RUN apk update && apk add certbot certbot-nginx rsyslog fail2ban
```
# Hypothesis 1: fail2ban does not run because of a system initialization error

There's no fail2ban in `/etc/init.d/` so I believe `fail2ban-client status` when it says that it:
```
Failed to access socket path: /var/run/fail2ban/fail2ban.sock. Is fail2ban running?
```
I tried to install `openrc` to start fail2ban manually but I am getting an even more puzzling behavior (though fail2ban now appears in `/etc/init.d/`): 
```
/usr/src/nginx # rc-service fail2ban status
 * You are attempting to run an openrc service on a
 * system which openrc did not boot.
 * You may be inside a chroot or you may have used
 * another initialization system to boot this system.
 * In this situation, you will get unpredictable results!
 * If you really want to do this, issue the following command:
 * touch /run/openrc/softlevel
```
I can't quite make sense of this message, for fail2ban appears in `/etc/init.d/` IFF openrc runs in this container. If openrc did not start this service, who did? I then tried the following: 
```
rc-update add fail2ban
rc-service fail2ban restart
 * WARNING: fail2ban is already starting
```
Does that mean that something else tries to start fail2ban not matter the presence of openrc. Is fail2ban visible in `/etc/init.d/` merely a by-product of the latter?

# Hypothesis n°2 fail2ban does not start because some logs to parse do not exist

From what I read [here](https://github.com/fail2ban/fail2ban/issues/2204) fail2ban does not start when it cannot find the relevant log files for the different services. I tried to remove `/etc/fail2ban/jail.d/alpine-ssh.conf` alongside `/etc/fail2ban/jail.conf` in my **entrypoint.sh** to add only my own jail parsing `/var/log/nginx/access.log`. 

Some insights would help me figure out what I am doing (conceiving) wrongly

**Comment by lvidal1** [comment]
Did you find any solution to this?

**Comment by zar3bski** [comment]
It turned out to have something to do with the container not having privileges over the network interface. For fail2ban to work, the container seems to need the following (`docker-compose` syntax)

```yaml
    cap_add:
      - NET_ADMIN
      - NET_RAW
```
Have a look at [this discussion](https://stackoverflow.com/a/44523905/7648881)
