### ISSUE TITLE
When Alpine CDN is down (FYI)

### ISSUE THREAD

**Issue by rolweber** [gliderlabs/docker-alpine#527]
At the moment, dl-cdn.alpinelinux.org and other mirrors in the .alpinelinux.org domain are down, or at least unreachable from my location. This breaks my docker build, which installs additional packages with `apk`.

One way to overcome this problem is to pick a working [mirror from the list](https://mirrors.alpinelinux.org/) and add it to the list of repositories inside the Docker image. Luckily, the list of mirrors is still online although it is in the same domain as the broken mirrors.

Original content of `/etc/apk/repositories` in my case:

```txt
http://dl-cdn.alpinelinux.org/alpine/v3.10/main
http://dl-cdn.alpinelinux.org/alpine/v3.10/community
```

I've picked `https://ftp.halifax.rwth-aachen.de/` as the mirror and changed my Dockerfile accordingly:

```Dockerfile
RUN echo >>/etc/apk/repositories \
    "https://ftp.halifax.rwth-aachen.de/alpine/v3.10/main" \
 && apk add ...
```

**Comment by rolweber** [comment]
A solution from a few years back, in https://github.com/gliderlabs/docker-alpine/issues/155#issuecomment-241731855, could be adapted as well. It replaces the repository URLs, rather than adding to the list. The specific mirror chosen there is currently also down.

**Comment by rolweber** [comment]
Definitely a local problem. From my machine, I cannot reach dl-cdn.alpinelinux.org, but the CI servers can. Hope the workaround will be useful nonetheless.

**Comment by ncopa** [comment]
https://downforeveryoneorjustme.com/dl-cdn.alpinelinux.org
