### ISSUE TITLE
apk can not found on mips

### ISSUE THREAD

**Issue by XiaodongLoong** [gliderlabs/docker-alpine#535]
I met a problem that apk not found when I make alpine image on mips platform, and the error is below. 
I cannot find the apk source code, please give me a URL.

[root@localhost scripts]# ./mkimage-alpine.bash -r v3.1 -s rootfs.tar.xz -a x86_64 -E -p alpine-base -b
./mkimage-alpine.bash:41: apk: command cannot found
[root@localhost scripts]#

**Comment by ncopa** [comment]
apk source code can be found here: https://gitlab.alpinelinux.org/alpine/apk-tools/

please note that we don't officially support mips (yet).

**Comment by XiaodongLoong** [comment]
Thanks for your reply sincerely  but I have some other questions. I want to make alpine image on mips as soon as possible and the alpine image is important for my company. Could you give me some advice on making the image smoothly?
For example, which CPU platform source code I can use it to finish work and which alpine version I can adapt MIPS quickly.
Thank you!
