### ISSUE TITLE
/bin/sh Permission denied

### ISSUE THREAD

**Issue by sumyuga** [gliderlabs/docker-alpine#54]
After I install executable binary files (racket for example) I can't launch it and shell says: Permission denied.
I have no idea why it happens. With other images is all ok.
What should I do?

**Comment by jumanjiman** [comment]
use `strace` and `ldd` to check if your binary requires glibc.
if so, either recompile your binary with alpine toolset or include glibc (and any other required libs) in the image (or statically compile your binary).

tips are in https://github.com/gliderlabs/docker-alpine/issues/11 plus various blog posts about ldd and docker.

hth.

**Comment by sumyuga** [comment]
Thanks for your answer. I've found out that missing some libs, here they are:
libdl.so.2 => not found
libm.so.6 => not found
libpthread.so.0 => not found
libc.so.6 => not found
The question is I couldn't add glibc via apk manager – there is only libc but this one doesn't add missing libs. Should I add glib manually?

**Comment by jumanjiman** [comment]
> The question is I couldn't add glibc via apk manager – there is only libc but this one doesn't add missing libs. 

fundamentally, alpine is based on musl-libc, which [differs from others libc implementations like glibc](http://www.etalabs.net/compare_libcs.html).

> Should I add glib manually?

you *can* add glibc manually like in https://github.com/gliderlabs/docker-alpine/issues/11#issuecomment-91329401 but...what if the next version of racket needs additional dynamic libs? how will you handle updates to glibc?

personally i'd try to build racket from [source](http://download.racket-lang.org/), preferably as a static bin that you could then copy into a runtime image. i'm not familiar with racket, so i don't even know if that's possible, but it should be. 

e.g., https://github.com/jumanjiman/docker-caddy shows a simple approach to build a golang binary *statically*, then copy it into another image.

you could also try contacting racket upstream to see if they can add official binaries for musl-libc.

**Comment by sumyuga** [comment]
Thanks a lot for your comprehensive reply. I'll try to build and copy static binary.
