### ISSUE TITLE
Could not initialize class sun.awt.X11FontManager  #openjdk:13-jdk-alpine3.10

### ISSUE THREAD

**Issue by hamadi07** [gliderlabs/docker-alpine#540]
Hello, 
I'm getting this stack trace when using openjdk 13 with this docker image: openjdk:13-jdk-alpine3.10

/opt/openjdk-13/lib/libfontmanager.so: Error loading shared library libfreetype.so.6: No such file or directory (needed by /opt/openjdk-13/lib/libfontmanager.so

Could not initialize class sun.awt.X11FontManager

**Comment by ncopa** [comment]
```console
$ apk search so:libfreetype.so.6
freetype-2.10.1-r0
```
try `apk add freetype`.

There is nothing for us to fix, but it is possible the openjdk image should be fixed.
