### ISSUE TITLE
dl-cdn.alpinelinux.org/alpine/v3.11/main repository down (?) No such file or directory

### ISSUE THREAD

**Issue by amirtal** [gliderlabs/docker-alpine#541]
running 'apk update' from inside a running docker returns:
/ # apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/main: No such file or directory
WARNING: Ignoring APKINDEX.70f61090.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/community: No such file or directory
WARNING: Ignoring APKINDEX.ca2fea5b.tar.gz: No such file or directory
2 errors; 14 distinct packages available

checking same address in DNS returns a correct reply.

searching online i see this issue is open since 2015 / alpine v3.4
5 years and 7 versions should be plenty of time to fix such a basic (and breaking) issue..

is the repository down ?!?

Amir.

**Comment by amirtal** [comment]
obviouslyit is not down, since i can use the links above and all are working...

**Comment by amirtal** [comment]
duplicate, please ignore..

**Comment by Shwetankgithub** [comment]
Hi Amirtal i am also facing same Error message please share the solution

**Comment by 0xMH** [comment]
I'm facing this issue right now when using `node:12.16.1-alpine` in droneci.
