### ISSUE TITLE
dl-cdn.alpinelinux.org was offline (12:18:56am  Tuesday, 15 February 2022 gmt ~ 2:52:10am  Tuesday, 15 February 2022)

### ISSUE THREAD

**Issue by duttonw** [gliderlabs/docker-alpine#563]
https://downforeveryoneorjustme.com/dl-cdn.alpinelinux.org

#527

**Comment by duttonw** [comment]
Error 503 Backend is unhealthy
Backend is unhealthy

Guru Mediation:
Details: cache-bne12527-BNE 1644884593 3491730306

Varnish cache server

**Comment by Zorlin** [comment]
Down for me also.

**Comment by goutamtadi1** [comment]
+1 me too

**Comment by abir4l** [comment]
+1 me too

**Comment by daltonks** [comment]
Does anyone know how to work around this when using the "Publish Docker (By elgohr)" github action?

**Comment by evaldofelipe** [comment]
+1 me too

**Comment by yanglbme** [comment]
+1 me too

https://github.com/doocs/leetcode/runs/5193210585

**Comment by abir4l** [comment]
For me i just added 'dl-4' mirror to the repositories file
hope this helps for now as a temporary solution till they get it fixed.
`echo 'http://dl-4.alpinelinux.org/alpine/v3.15/main' >> /etc/apk/repositories`

**Comment by duttonw** [comment]
I'm failing on container building https://github.com/qld-gov-au/ckanext-validation/blob/master/.docker/Dockerfile.ckan

```
---> Running in e518b1fb59f2
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/main: temporary error (try again later)
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/community: temporary error (try again later)
ERROR: unable to select packages:
  build-base (no such package):
    required by: world[build-base]
  curl (no such package):
    required by: world[curl]
Service 'ckan' failed to build: The command '/bin/sh -c apk add --no-cache curl build-base     && curl -s -L -O [https://github.com/jwilder/dockerize/releases/download/${DOCKERIZE_VERSION}/dockerize-alpine-linux-amd64-${DOCKERIZE_VERSION}.tar.gz](https://github.com/jwilder/dockerize/releases/download/$%7BDOCKERIZE_VERSION%7D/dockerize-alpine-linux-amd64-$%7BDOCKERIZE_VERSION%7D.tar.gz)     && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-${DOCKERIZE_VERSION}.tar.gz     && rm dockerize-alpine-linux-amd64-${DOCKERIZE_VERSION}.tar.gz' returned a non-zero code: 2
````

**Comment by duttonw** [comment]
thanks @abir4l  that got me off the ground,

see https://github.com/qld-gov-au/ckanext-validation/commit/0e12dfd5b01b1380b2a2a7aab59099099b6c26e8 on what i did

**Comment by jbg** [comment]
If you use Alpine a lot, consider running a mirror:

https://wiki.alpinelinux.org/wiki/How_to_setup_a_Alpine_Linux_mirror (wiki page also appears to be down right this moment though 😂)

Not only will you be helping make the whole mirror system more robust, but if it ever goes down, you'll be able to fix it yourself.

**Comment by rexrodriguez** [comment]
Is there any way to point a github action to a mirror?

**Comment by jcurlier** [comment]
+1

**Comment by ramanNarasimhan77** [comment]
+1

**Comment by ns-kwang** [comment]
+1

**Comment by xyu-ns** [comment]
+1

**Comment by duttonw** [comment]
@rexrodriguez  which action in question?

**Comment by hongjinn** [comment]
Beginner question - how quickly do things like this get resolved (generally speaking)? Or do they sometimes just not? Thanks.

**Comment by rexrodriguez** [comment]
@duttonw

For my use-case, this one:  https://github.com/SpicyPizza/create-envfile

**Comment by Kvnyu** [comment]
+1

**Comment by nekomeowww** [comment]
+1

**Comment by franchyze923** [comment]
+1 Glad to hear it's not just me! I was beginning to go down a rabbit hole of troubleshooting...

**Comment by 4geru** [comment]
+1

**Comment by duttonw** [comment]
@rexrodriguez ,
fork* the action to yourself or org, update https://github.com/SpicyPizza/create-envfile/blob/master/Dockerfile 
change
RUN apk add python3
to
RUN echo 'http://dl-4.alpinelinux.org/alpine/v3.10/main' >> /etc/apk/repositories && apk add python3

use your own action

**Comment by rexrodriguez** [comment]
> @rexrodriguez , fork* the action to yourself or org, update https://github.com/SpicyPizza/create-envfile/blob/master/Dockerfile change RUN apk add python3 to RUN echo 'http://dl-4.alpinelinux.org/alpine/v3.10/main' >> /etc/apk/repositories && apk add python3
> 
> use your own action

Thanks thanks ++

**Comment by ghost** [comment]
IT'S BACK :lmao:

**Comment by ncopa** [comment]
we got DDOSed

**Comment by hongjinn** [comment]
Thank you for fixing this so fast

**Comment by Zorlin** [comment]
Appears to be back online.
