### ISSUE TITLE
How to control the software version with apk

### ISSUE THREAD

**Issue by SydOps** [gliderlabs/docker-alpine#58]
@progrium 

When install software with apk in Alpine, I can't find the right option to control the version that I can  install. Will apk always install the latest version?

Can you give me some hints?

Bill

**Comment by progrium** [comment]
Try the docs :)

http://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management

On Thu, Aug 13, 2015 at 7:57 AM, Bill W <notifications@github.com> wrote:

> @progrium <https://github.com/progrium>
>
> When install software with apk in Alpine, I can't find the right option to
> control the version that I can install. Will apk always install the latest
> version?
>
> Can you give me some hints?
>
> Bill
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/docker-alpine/issues/58>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by SydOps** [comment]
@progrium Thanks a lot. I saw the options.
