### ISSUE TITLE
Unprivileged user can gain root privileges

### ISSUE THREAD

**Issue by widder** [gliderlabs/docker-alpine#59]
I'm not sure how the wheel group is treated in docker-alpine but why does it exist if one can gain root privileges without being member of it?

```
# docker run -i -t --name="test" alpine /bin/sh
/ # adduser -S testuser
/ # groups testuser
nogroup
```

```
# docker start test
```

```
# docker exec -it --user=testuser test /bin/sh
/ $ whoami
testuser
/ $ su
/ # whoami
root
/ # groups testuser
nogroup
/ # groups root
root bin daemon sys adm disk wheel floppy dialout tape video
/ # 
```

In ubuntu-docker this does not work.

**Comment by yosifkit** [comment]
That just means root has an empty password; the wheel group only matters for the `sudo` command.

**Comment by widder** [comment]
Correct. This is the difference to the containers CentOS and Ubuntu where the root password is disabled by default.
Please close.

**Comment by widder** [comment]
close

**Comment by zakkg3** [comment]
why we dont remove root passwd by default in alpine?
https://talosintelligence.com/vulnerability_reports/TALOS-2019-0782

**Comment by tianon** [comment]
See https://github.com/gliderlabs/docker-alpine/pull/511

**Comment by ncopa** [comment]
I think its unfair to blame gliderlabs for this one. It was my mistake.
