### ISSUE TITLE
Container size

### ISSUE THREAD

**Issue by vasiliy-t** [gliderlabs/docker-alpine#6]
My Dockerfile

```
FROM gliderlabs/alpine
RUN apk-install alpine-sdk
RUN apk del alpine-sdk
```

After build container is 139.6Mb in size. Tried using with different packages, result is same. Tried using --virtual pak option. Tried to build on my machine and on docker hub. Any advice? My goal is to install build dependecies and remove then after building packages from sources.

**Comment by progrium** [comment]
You need to do those operations in the same RUN command or they will result
in additive two layers.

On Tue, Feb 17, 2015 at 3:11 AM, V <notifications@github.com> wrote:

> My Dockerfile
>
> FROM gliderlabs/alpine
> RUN apk-install alpine-sdk
> RUN apk del alpine-sdk
>
> After build container is 139.6Mb in size. Tried using with different
> packages, result is same. Tried using --virtual pak option. Tried to build
> on my machine and on docker hub. Any advice? My goal is to install build
> dependecies and remove then after building packages from sources.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/docker-alpine/issues/6>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by vasiliy-t** [comment]
Thanks
