### ISSUE TITLE
[Node]-Oracle Instant Client

### ISSUE THREAD

**Issue by DefunctExodus** [gliderlabs/docker-alpine#62]
I am just curious if anyone has this working with oracle instant client, I would love to use this for our node deployments but we need to connect to oracle which means that we need the instant client along with the oracle npm.

**Comment by andyshinn** [comment]
There are two problems with this:

* There isn't a way to download the client without loggin into Oracle website (this is outside the scope of this repository).
* I just tried some of the tools that come with the client and they only run on glibc.

This will likely only work with a glibc compatibility layer once you can actually get it into your image. Follow along in #11 for the work already going on around this.
