### ISSUE TITLE
How to get package librados - general question for mapping the package from other linux

### ISSUE THREAD

**Issue by SydOps** [gliderlabs/docker-alpine#64]
This is a general question, how can I easily mapping the package I used before in Ubuntu/Centos or other Linux. 

So this time, I need a package named `librados`, I search in https://pkgs.alpinelinux.org, but not found. Then what can I do? Any instruction about this?

**Comment by progrium** [comment]
Apparently you make a request issue: https://bugs.alpinelinux.org/projects/alpine/issues?utf8=%E2%9C%93&set_filter=1&f%5B%5D=status_id&op%5Bstatus_id%5D=o&f%5B%5D=subject&op%5Bsubject%5D=~&v%5Bsubject%5D%5B%5D=request&f%5B%5D=&c%5B%5D=project&c%5B%5D=tracker&c%5B%5D=status&c%5B%5D=priority&c%5B%5D=subject&c%5B%5D=assigned_to&c%5B%5D=updated_on&group_by=

**Comment by SydOps** [comment]
Thanks, ticket is raised (https://bugs.alpinelinux.org/issues/4611)
