### ISSUE TITLE
Go 1.3 and 1.4 test with race raise an exceptions

### ISSUE THREAD

**Issue by miry** [gliderlabs/docker-alpine#68]
Tested in Alpine 3.2(go 1.4) and 3.1(go 1.3)

When tried to run tests with `-race`. I got next exception:

```
# runtime/race
race_linux_amd64.syso: In function `__sanitizer::InternalAlloc(unsigned long, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 16ul, __sanitizer::SizeClassMap<17ul, 64ul, 14ul>, 24ul, __sanitizer::TwoLevelByteMap<2048ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*)':
gotsan.cc:(.text+0x1130): undefined reference to `__libc_malloc'
race_linux_amd64.syso: In function `__tsan::WriteMemoryProfile(char*, unsigned long)':
gotsan.cc:(.text+0x929b): undefined reference to `__libc_mallinfo'
race_linux_amd64.syso: In function `__sanitizer::ReExec()':
gotsan.cc:(.text+0xa047): undefined reference to `__libc_stack_end'
race_linux_amd64.syso: In function `__sanitizer::InternalFree(void*, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 16ul, __sanitizer::SizeClassMap<17ul, 64ul, 14ul>, 24ul, __sanitizer::TwoLevelByteMap<2048ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*)':
gotsan.cc:(.text+0x4d8d): undefined reference to `__libc_free'
collect2: error: ld returned 1 exit status
```

Tried to use https://github.com/andyshinn/alpine-pkg-glibc also.

But it works without `-race` option: `go test -v ./...`

Created simple example to reproduce issue: https://gist.github.com/miry/fece267c7faba904c360

**Comment by progrium** [comment]
Doesn't it normally work without the race option without glibc?

I can imagine race might use non-standard features of libc that are not in
musl. And that somehow the way it uses libc cannot pick up glibc, perhaps
because it depends on utilities (ld, etc) that are going to be set up for
musl.

On Wed, Sep 9, 2015 at 2:54 AM, Michael Nikitochkin <
notifications@github.com> wrote:

> Tested in Alpine 3.2(go 1.4) and 3.1(go 1.3)
>
> When tried to run tests with -race. I got next exception:
>
> # runtime/race
> race_linux_amd64.syso: In function `__sanitizer::InternalAlloc(unsigned long, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 16ul, __sanitizer::SizeClassMap<17ul, 64ul, 14ul>, 24ul, __sanitizer::TwoLevelByteMap<2048ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*)':
> gotsan.cc:(.text+0x1130): undefined reference to `__libc_malloc'
> race_linux_amd64.syso: In function `__tsan::WriteMemoryProfile(char*, unsigned long)':
> gotsan.cc:(.text+0x929b): undefined reference to `__libc_mallinfo'
> race_linux_amd64.syso: In function `__sanitizer::ReExec()':
> gotsan.cc:(.text+0xa047): undefined reference to `__libc_stack_end'
> race_linux_amd64.syso: In function `__sanitizer::InternalFree(void*, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 16ul, __sanitizer::SizeClassMap<17ul, 64ul, 14ul>, 24ul, __sanitizer::TwoLevelByteMap<2048ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*)':
> gotsan.cc:(.text+0x4d8d): undefined reference to `__libc_free'
> collect2: error: ld returned 1 exit status
>
> Tried to use https://github.com/andyshinn/alpine-pkg-glibc also.
>
> But it works without -race option: go test -v ./...
>
> Created simple example to reproduce issue:
> https://gist.github.com/miry/fece267c7faba904c360
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/docker-alpine/issues/68>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by andyshinn** [comment]
It looks like at the very least `__libc_stack_end` is an internal glibc symbol and not in musl. I think the Golang race detector is using some c++ stuff which is not fully compatible with musl.

Have you checked out the *How do I use the musl-gcc wrapper?* section at http://www.musl-libc.org/faq.html? It explains a little bit about the issue. Is there a way to recompile the Golang runtime/race detector against musl maybe?

**Comment by miry** [comment]
@progrium @andyshinn Thanks for clarification. I will try to use Go 1.5.1, so it should not depends on libc. Do you have build for this version?

**Comment by andyshinn** [comment]
Go 1.5 is in `alpine:edge`.

**Comment by miry** [comment]
Ok. Found https://github.com/golang/go/issues/12122. For go15 the race still use libc :(

**Comment by miry** [comment]
some logs from me:

```
CGO_LDFLAGS="-g" "-O2" /usr/lib/go/pkg/tool/linux_amd64/cgo -objdir $WORK/runtime/race/_obj/ -importpath runtime/race -import_syscall=false -- -I $WORK/runtime/race/_obj/ race.go
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/runtime/race/_obj/ -g -O2 -o $WORK/runtime/race/_obj/_cgo_main.o -c $WORK/runtime/race/_obj/_cgo_main.c
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/runtime/race/_obj/ -g -O2 -o $WORK/runtime/race/_obj/_cgo_export.o -c $WORK/runtime/race/_obj/_cgo_export.c
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/runtime/race/_obj/ -g -O2 -o $WORK/runtime/race/_obj/race.cgo2.o -c $WORK/runtime/race/_obj/race.cgo2.c
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -o $WORK/runtime/race/_obj/_cgo_.o $WORK/runtime/race/_obj/_cgo_main.o $WORK/runtime/race/_obj/_cgo_export.o $WORK/runtime/race/_obj/race.cgo2.o race_linux_amd64.syso -g -O2
# runtime/race
```

**Comment by andyshinn** [comment]
Thanks for linking up the Golang issue for others to find. Indeed, it looks like this won't work until Golang fixes up the race detector to support other libc or is rewritten in pure Golang.

**Comment by jerome-laforge** [comment]
From the alpine dockerfile, I can see that you compile go from the source.
The link below gives us how to compile with race support.

Could you take it in account?
https://getgb.io/faq/#missing-race-support

Thx

**Comment by tianon** [comment]
See https://github.com/golang/go/issues/14481 -- Go upstream does not support the race detector on Alpine Linux yet.
