### ISSUE TITLE
downloaded Nodejs will not run

### ISSUE THREAD

**Issue by Vad1mo** [gliderlabs/docker-alpine#7]
I have this dockerfile https://registry.hub.docker.com/u/zinvoice/kibana/dockerfile/ that installs kibana4
now I have the problem that I can not run node.

```
/ # ls -la /opt/kibana-4.0.0-linux-x64/node/bin/
total 10920
drwxr-xr-x    2 root     dialout       4096 Feb 20 15:26 .
drwxr-xr-x    6 root     dialout       4096 Feb 20 15:17 ..
-rwxrwxrwx    1 root     dialout   11167042 Feb 19 16:10 node
-rwxrwxrwx    1 root     dialout       2290 Feb 19 16:10 npm
/ # /opt/kibana-4.0.0-linux-x64/node/bin/node 
sh: /opt/kibana-4.0.0-linux-x64/node/bin/node: not found
```

You can reproduce 
```
mkdir /opt
wget -qcO - http://download.elasticsearch.org/kibana/kibana/kibana-4.0.0-linux-x64.tar.gz | gunzip -c | tar -xf - -C /opt
/opt/kibana-4.0.0-linux-x64/node/bin/node
```
 

I tried to chown/chmod and downloaded the need linux dependencies but I  still can not run nodejs

also tried to run http://nodejs.org/dist/v0.12.0/node-v0.12.0-linux-x64.tar.gz with the same result.

**Comment by andyshinn** [comment]
Looks like those versions of NodeJS rely on `backtrace_symbols` which is part of `execinfo.h` that is not part of musl or standard libc. Does Kibana provide a way to use the system `node` binary so you can install with `apk-install nodejs`?

You might be able to install system NodeJS and symlink it over Kibana version as well. Though, this isn't an ideal solution.

**Comment by Vad1mo** [comment]
I can change the starting shell script in kibana to point to another node implementation. 
I am not sure if Kibana4 will run on an old (0.10.33) nodejs. This is the latest one available in  the repository.

**Comment by Vad1mo** [comment]
I switched now to debian its not perfect but working.

**Comment by Vad1mo** [comment]
strange is that I see some busybox-node boxes running nodejs 0.12 and 0.10.35

https://registry.hub.docker.com/u/odise/busybox-node/dockerfile/
https://registry.hub.docker.com/u/joeandaverde/minimal-nodejs/dockerfile/

**Comment by andyshinn** [comment]
Unfortunately, Alpine won't be great for stuff that was precompiled to use glibc specific things. Those other bases are based on uClibc and sometimes pull in an outside library for a compatibility layer. As we are trying to stay close to upstream Alpine Linux, we likely won't be pulling in some sort of layer like that.

**Comment by progrium** [comment]
Although if somebody wants to make an Alpine package for glibc that would be rad.
