### ISSUE TITLE
question: running docker in alpine

### ISSUE THREAD

**Issue by tony-kerz** [gliderlabs/docker-alpine#71]
i was trying to create an alpine image containing a shell script which in turn called some stuff via `docker run`.

i used `apk` to install docker, but (of course) doing so didn't setup the docker daemon, etc.

is running docker within an alpine image possible or advisable?

thanks,
tony.

**Comment by andyshinn** [comment]
Docker in Docker is a special beast. You cannot just install Docker and expect it to work. Have you checked out the Alpine image and wrapper script at https://github.com/jpetazzo/dind?

**Comment by tony-kerz** [comment]
thanks @andyshinn,

of course you are right. after i dropped the question, i realized i had seen this pattern previously, and even experimented with `jpetazzo/dind`. 

i was able to use the `-v /var/run/docker.sock:/var/run/docker.sock` trick in this case successfully.

it's not ideal, as it involves permission issues with `docker.sock` and potential conflicts with the versions of docker installed on the host and in the image, but it's one way of achieving the desired effect.
