### ISSUE TITLE
docker seems to combine stdout and stderr streams, making --stdout useless

### ISSUE THREAD

**Issue by muhmuhten** [gliderlabs/docker-alpine#73]
I'm not sure whether this is a recent change, I could check later. Issue is:

    $ docker run --rm -it alpine sh -c '(echo 1 >&1; echo 2 >&2)'
    1
    2
    $ docker run --rm -it alpine sh -c '(echo 1 >&1; echo 2 >&2) 1>&-'
    2
    $ docker run --rm -it alpine sh -c '(echo 1 >&1; echo 2 >&2) 2>&-'
    1
    $ docker run --rm -it alpine sh -c '(echo 1 >&1; echo 2 >&2) ' 1>&-
    $ docker run --rm -it alpine sh -c '(echo 1 >&1; echo 2 >&2) ' 2>&-
    1
    2

1.7.1 on both coreos and fedora, so if this ever worked, it looks like it got broken.

The effect of this one the builder is that the output ends up looking like

    fetch http://nl.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
    fetch http://dl-4.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
    Downloading libc-utils-0.7-r0
    Downloading busybox-1.23.2-r9
    Downloading alpine-base-3.2.3-r0
    Downloading musl-utils-1.1.11-r2
    Downloading busybox-initscripts-2.3-r1
    Downloading scanelf-0.9.1-r0
    Downloading libcrypto1.0-1.0.2d-r0
    Downloading apk-tools-2.6.4-r1
    Downloading openrc-0.17-r3
    Downloading alpine-keys-1.1-r0
    Downloading zlib-1.2.8-r2
    Downloading libssl1.0-1.0.2d-r0
    Downloading alpine-conf-3.2.1-r6
    Downloading alpine-baselayout-2.3.2-r1
    Downloading musl-1.1.11-r2
    (1/15) Installing musl (1.1.11-r2)
    (2/15) Installing busybox (1.23.2-r9)
    Executing busybox-1.23.2-r9.post-install
    (3/15) Installing alpine-baselayout (2.3.2-r1)
    Executing alpine-baselayout-2.3.2-r1.pre-install
    Executing alpine-baselayout-2.3.2-r1.post-install
    (4/15) Installing openrc (0.17-r3)
    Executing openrc-0.17-r3.post-install
    (5/15) Installing alpine-conf (3.2.1-r6)
    (6/15) Installing zlib (1.2.8-r2)
    (7/15) Installing libcrypto1.0 (1.0.2d-r0)
    (8/15) Installing libssl1.0 (1.0.2d-r0)
    (9/15) Installing apk-tools (2.6.4-r1)
    (10/15) Installing busybox-initscripts (2.3-r1)
    Executing busybox-initscripts-2.3-r1.post-install
    (11/15) Installing scanelf (0.9.1-r0)
    (12/15) Installing musl-utils (1.1.11-r2)
    (13/15) Installing libc-utils (0.7-r0)
    (14/15) Installing alpine-keys (1.1-r0)
    (15/15) Installing alpine-base (3.2.3-r0)
    Executing busybox-1.23.2-r9.trigger
    OK: 6 MiB in 15 packages
    [actual tar data]

which is not a valid tar file.

I suggest suppressing output instead of piping to stderr when using `--stdout`; when running outside of a container, rootfs.tar.gz is usually accessible to the caller afterward anyway.

**Comment by andyshinn** [comment]
I'm not sure what your example is illustrating. What about something like `docker run alpine sh -c "echo 'stderr' 1>&2; echo 'stdout'" | wc -l`? Are you using #70? Is it possible `output_redirect` is not working as desired in https://github.com/gliderlabs/docker-alpine/pull/70/files#diff-c0fb86435ae54de56f7dbb9f0eebb7d3R57?

**Comment by muhmuhten** [comment]
never mind, problem is extraneous -t.
