### ISSUE TITLE
Issue installing package

### ISSUE THREAD

**Issue by larghir** [gliderlabs/docker-alpine#75]
Hi, 
I am getting the following error when trying to install libstdc++ with apk

fetch http://dl-4.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-4.alpinelinux.org/alpine/v3.2/main: temporary error (try again later)
(1/1) Installing libstdc++ (4.9.2-r5)
ERROR: libstdc++-4.9.2-r5: temporary error (try again later)

using the 3.2 tag.
Any hints appreciated.

**Comment by andyshinn** [comment]
Looks like you cannot resolve dl-4.alpinelinux.org. Are you able to get to http://dl-4.alpinelinux.org/alpine/v3.2/main/ on the host that is trying to build/run the container? Can you give a little more information about your Docker and host setup?

**Comment by larghir** [comment]
@andyshinn thanks, I confirm I can get http://dl-4.alpinelinux.org/alpine/v3.2/main/ on the host.
Am building an oracle-server-jre container from docker-alpine:3.2 base.
I am just noticing that this problem occurs when I'm connecting to a remote Daemon socket (seems to work locally)

**Comment by andyshinn** [comment]
What OS is the host? Are you using something like boot2docker? In cases where VirtualBox is used you may need to disable the DNS NAT proxy per comment https://github.com/boot2docker/boot2docker/issues/451#issuecomment-65432123.

**Comment by larghir** [comment]
No, the OS on the host is Ubuntu 14.04.2 LTS

**Comment by larghir** [comment]
Restarting the docker service on the host seems to have fixed the issue.

**Comment by darKoram** [comment]
thanks @larghir  worked for me too
