### ISSUE TITLE
Adding lots of users

### ISSUE THREAD

**Issue by kaihendry** [gliderlabs/docker-alpine#80]
I have a Docker file, where I need to setup accounts from a user.txt file that looks like:

    user:pass
    bob:1234
    larry:kensentme
    

Currently I am limited to **one account using ENV** like so:

    ENV APP_USER bob
    ENV APP_PASS 1234
    # Ftp account(s)
    RUN adduser -D ${APP_USER} && echo "${APP_USER}:${APP_PASS}" | chpasswd

Do you have any suggestions to scale this up?

**Comment by andyshinn** [comment]
This isn't really related to Alpine Linux or Docker. But you could do some quick shell to do this. Maybe something like:

```shell
while IFS=$':' read -r user pass; do adduser -D $user && echo "${user}:${pass}" | chpasswd; done < users
```

**Comment by kaihendry** [comment]
Thank you. Care to review: https://github.com/kaihendry/camftp2web/blob/master/Dockerfile

Ideally could get rid of supervisor.d... not sure what's the easiest way.
