### ISSUE TITLE
Fail to pick up file updates in boot2docker

### ISSUE THREAD

**Issue by princemaple** [gliderlabs/docker-alpine#84]
Hi guys,

http://stackoverflow.com/questions/32821555/not-getting-real-file-update-in-vm/32826034#comment53548751_32821555

Would so nice if I can get it to work! If you care to help:

I'm a Windows user. And I've been using docker for a while to get away from having to install another OS.
Boot2docker works really well on Windows, and I've recently switched to docker machines, which seems to simply wrap boot2docker if you do local dev with virtualbox, also working pretty nicely.

Some issue I discovered about boot2docker, or the Linux it uses: it often fails to pick up file updates from the shared folder. It wasn't a problem before because the base images I used to build my own images don't have problems although they run in a problematic docker host (boot2docker vm). Official python / ruby / rails images all seem to able to pick up file updates fine. Recently I wanted to build an image that suits my particular use case out of a minimal base image, and I discovered this project. It's great to have such a tiny base image! I got it to work after some trial and error fun. Then, I discovered the problem I described above... didn't even realize there was such issue in boot2docker before I used alpine as my base image.

Anyway, thank you very much, if you read through all this. Any help will be greatly appreciated! Thanks!

**Comment by mattaitchison** [comment]
@princemaple Take a look at gliderlabs/pagebuilder#2. It has some information about what causes this problem and a temporary fix.

**Comment by princemaple** [comment]
@mattaitchison yep the command works. Looks like it's the same issue. Thank you very much!

**Comment by princemaple** [comment]
@mattaitchison this makes me wonder why other base images are not affected.. I'm a newbie in this area. Do you happen to know why? I'm keen to get an easy / generic fix for my own dev env.

**Comment by progrium** [comment]
Most likely because alpine uses musl.

**Comment by rdsubhas** [comment]
Might be a problem with the shared folder in underlying boot2docker image, please check the above referenced issue.

**Comment by princemaple** [comment]
thanks @rdsubhas !

**Comment by princemaple** [comment]
The problem is gone with the [latest release](https://github.com/docker/toolbox/releases/tag/v1.9.0) of docker toolbox (docker machine, boot2docker).
It's boot2docker issue, not really alpine's fault.

**Comment by rdsubhas** [comment]
:+1: @princemaple thanks!
