### ISSUE TITLE
official-images build failed

### ISSUE THREAD

**Issue by JeremJR** [gliderlabs/docker-alpine#89]
Hello,

It seems that the https://github.com/docker-library/official-images/commit/0d5a1bca11ceda16aa2afa42be03ada08d1597d8 contains invalid ref which cause a failure into the build of the official images :

```
Processing alpine:2.6 ...
- failed; invalid ref: c369eb24b9cd81149b355fc785173e3dde098001
Processing alpine:2.7 ...
- failed; invalid ref: 19859598cbba40c4b8851339164c3998694dee65
Processing alpine:3.1 ...
- failed; invalid ref: 1a65d4ea2ceb1db6d1579c99226a0858c45563ce
Processing alpine:3.2 ...
- failed; invalid ref: 7621dffecfb794a7639dabb468732102e6f265bb
Processing alpine:latest ...
- failed; invalid ref: 7621dffecfb794a7639dabb468732102e6f265bb
Processing alpine:edge ...
- failed; invalid ref: 16384184f6870fa786e7dc590bf9fdbddee77bd7
```

https://travis-ci.org/docker-library/official-images/builds/85402833#L1672

Could you please update official-images/library/alpine ?

Jérémy

**Comment by andyshinn** [comment]
Now that I understand the issue a bit more from IRC, I'll modify the `build` script to just commit instead of creating a new branch, committing, and force-pushing. This should leave the commit trail in the reflog and fix the issue going forward.

**Comment by andyshinn** [comment]
I'm going to wait for something like https://github.com/docker-library/official-images/issues/1095. After recent development that had a lot of commits with images in them, I realize that just regular commits that keep all the tarballs in history will lead to a massive git repository that will just be a pain to deal with.
