### ISSUE TITLE
go 1.5.x seems to have been removed from alpine:edge

### ISSUE THREAD

**Issue by i0n** [gliderlabs/docker-alpine#90]
Or am I missing something?

**Comment by jumanjiman** [comment]
it has moved to `community` repo.

https://pkgs.alpinelinux.org/packages?name=go&repo=all&arch=x86_64&maintainer=all

i confirmed that adding `http://dl-4.alpinelinux.org/alpine/edge/community` to `/etc/apk/repositories` enables me to install go 1.5.x

**Comment by i0n** [comment]
Awesome, thanks!
