### ISSUE TITLE
apk-install missing from official 3.2 image

### ISSUE THREAD

**Issue by janeczku** [gliderlabs/docker-alpine#92]
Just tried out the official 3.2 image from https://hub.docker.com/_/alpine/ only to find out that apk-install has gone.

```sh
# apk-install
# apk-install: No such file or directory
```

The docs linked in the Docker Hub page indicate that it should be present though:

http://gliderlabs.viewdocs.io/docker-alpine/usage/

**Comment by andyshinn** [comment]
Sorry it wasn't more obvious. But the `apk-install` is one of the distinctions between the official library version and the Glider Labs version. The differences section calls this out at http://gliderlabs.viewdocs.io/docker-alpine/build/. I'll add a note to the usage page as well.
