### ISSUE TITLE
Busybox vs Alpine cert issue

### ISSUE THREAD

**Issue by gzoller** [gliderlabs/docker-alpine#95]
I'm trying to rebuild the errordeveloper/oracle-jre image, which is build on busybox, on Alpine.  I'm seeing a difference in cert (ca-certificates) working between Alpine and Busybox.

Captured the issue as a Stack question with example here: http://stackoverflow.com/questions/33353532/does-alpine-linux-handle-certs-differently-than-busybox

I'm not sure if this is a bug or just a difference in how Alpine/BB handle certs.  Basically the only thing I changed in the Dockerfile is busybox->alpine (also tried alpine:3.2) and changed the package manager calls to support apk.

**Comment by andyshinn** [comment]
It doesn't look like that is the correct file location of that CA:

```
$ dri alpine sh -c "apk add -U ca-certificates && ls -al /etc/ssl/certs" | grep GeoTrust_Global_CA 
lrwxrwxrwx    1 root     root            30 Oct 26 23:27 2c543cd1.0 -> ca-cert-GeoTrust_Global_CA.pem
lrwxrwxrwx    1 root     root            57 Oct 26 23:27 ca-cert-GeoTrust_Global_CA.pem -> /usr/share/ca-certificates/mozilla/GeoTrust_Global_CA.crt
lrwxrwxrwx    1 root     root            59 Oct 26 23:27 ca-cert-GeoTrust_Global_CA_2.pem -> /usr/share/ca-certificates/mozilla/GeoTrust_Global_CA_2.crt
lrwxrwxrwx    1 root     root            32 Oct 26 23:27 cbeee9e2.0 -> ca-cert-GeoTrust_Global_CA_2.pem
```

**Comment by andyshinn** [comment]
Oh, and actually, you can't really do what you are trying to do. See #11 for the long discussion and some possible workarounds.

**Comment by gzoller** [comment]
Oh dear.  That is indeed disappointing.  Hopefully Alpine will support Java8 at some point, but thanks for the explanation--it does explain it.
