### ISSUE TITLE
Can I have join command in alpine? - /usr/bin/join

### ISSUE THREAD

**Issue by SydOps** [gliderlabs/docker-alpine#98]
my old build script need this command, but I can't find `join` in alpine.

Which package do I need install to get this command?

**Comment by jumanjiman** [comment]
https://pkgs.alpinelinux.org/contents?filename=join&path=&pkgname=&repo=all&arch=x86_64 hints that the package is `coreutils`. install it or inspect the git repo to confirm.

the package db rocks!

**Comment by SydOps** [comment]
Thanks, @jumanjiman. I can run "join" command now.

**Comment by SydOps** [comment]
And thanks to share the way to search, I only search in package, not in contents.

**Comment by jumanjiman** [comment]
:+1:
