### ISSUE TITLE
Official edge does not match gliderlabs/edge

### ISSUE THREAD

**Issue by jfindley** [gliderlabs/docker-alpine#99]
In the official edge image, apk add go fails entirely.
In the gliderlabs edge image, apk add go installs go 1.5.1, as expected.

As they both work by adding a static rootfs tarball, this is hard to diagnose, but from a user experience point of view it would be nice if they could be made consistent (or at least the official image fixed so that installing go worked)

**Comment by andyshinn** [comment]
In `edge` (and 3.3 onwards) there is a new repository named `community` and some packages have been moved over to it (including Go). One of the differences between `alpine` and `gliderlabs/alpine` is the inclusion of the `community` repo. I'll update the docs at http://gliderlabs.viewdocs.io/docker-alpine/build/ as this should be called out.

However, seeing stuff like Go in the `community` repo makes me wonder if it should just be default added to all images. I'll leave this open for others to comment.

**Comment by jumanjiman** [comment]
a compromise could be to include several tagged repos in the image.
http://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management#Repository_pinning

`/etc/apk/repositories` would look like:

```
# http://pkgs.alpinelinux.org/packages
# http://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management#Repository_pinning

http://dl-4.alpinelinux.org/alpine/v3.3/main
@community http://dl-4.alpinelinux.org/alpine/v3.3/community
@edge-main http://dl-4.alpinelinux.org/alpine/edge/main
@edge-community http://dl-4.alpinelinux.org/alpine/edge/community
@edge-testing http://dl-4.alpinelinux.org/alpine/edge/testing
```

apk uses the untagged repos by default, but allows to specify something like
`apk add go@community`. The comments at top of file would help newcomers understand the structure.

**Comment by jfindley** [comment]
There's some sense in leaving Go in the community repo, as there's local patches to fix some build issues on Alpine, and having it in the community repo undercuts that there might be differences from upstream.  I like the idea of doing apk add go@community though.

**Comment by andyshinn** [comment]
I think most people will be blindly doing `apk add go` and have a failure. Lets wait to see what the official upstream 3.3 repositories file looks like.

**Comment by andyshinn** [comment]
The official installer doesn't add the community repo but I've added it to the 3.3 and edge targets.
